"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
type Closure={id:string;competence_date:string;status:string;notes:string|null;closed_by_identity:string|null;reopened_by_identity:string|null;authorized_by_identity:string|null;reopen_reason:string|null};
type Version={id:string;version:number|string;report_type:string;data:Record<string,unknown>;totals:Record<string,unknown>;created_by_identity:string|null;created_at:string;is_preserved:boolean};
async function api(path:string,init?:RequestInit){const r=await fetch(path,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(d.error||`Erro ${r.status}`));return d;}
export default function ClosureWorkspace(){
 const [rows,setRows]=useState<Closure[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[search,setSearch]=useState(""),[selectedId,setSelectedId]=useState(""),[versions,setVersions]=useState<Version[]>([]),[versionsError,setVersionsError]=useState(""),[reason,setReason]=useState("");const [form,setForm]=useState({competence_date:"",notes:""});
 const load=useCallback(async()=>{try{const d=await api("/api/fin/competence-closures");setRows(d.closures||[]);setError("")}catch(e){setError(`Não foi possível ler os fechamentos: ${e instanceof Error?e.message:"falha"}`)}},[]);useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return q?rows.filter(x=>`${x.competence_date} ${x.status}`.toLowerCase().includes(q)):rows},[rows,search]);const selected=rows.find(x=>x.id===selectedId)||null;
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{const d=await api("/api/fin/competence-closures",{method:"POST",body:JSON.stringify({...form,totals:{origem:"interface_sintetica"}})});setNotice(`Competência ${d.closure.competence_date.slice(0,7)} ${d.idempotent_replay?"já estava fechada":"fechada"}; versão preservada.`);await load();setSelectedId(d.closure.id)}catch(e){setNotice(`Falha: ${e instanceof Error?e.message:"inesperada"}`)}finally{setBusy(false)}}
 async function act(action:"reopen"|"close"){if(!selected)return;setBusy(true);try{const d=await api("/api/fin/competence-closures",{method:"PATCH",body:JSON.stringify({id:selected.id,action,reopen_reason:action==="reopen"?reason:undefined,close_reason:action==="close"?reason:undefined,totals:{origem:"interface_sintetica"}})});setNotice(`${action==="reopen"?"Reabertura autorizada":"Novo fechamento"} persistido; versão ${d.version} preservada.`);setReason("");await load();await loadVersions(selected.id)}catch(e){setNotice(`Falha: ${e instanceof Error?e.message:"inesperada"}`)}finally{setBusy(false)}}
 async function loadVersions(id=selectedId){if(!id)return;try{const d=await api(`/api/fin/report-versions?closure_id=${id}`);setVersions(d.versions||[]);setVersionsError("")}catch(e){setVersionsError(`Falha ao ler versões: ${e instanceof Error?e.message:"erro"}`)}}
 return <section data-testid="finance-closure-workspace"><h2>Fechamento e reabertura de competência</h2><p>O fechamento bloqueia lançamentos do mês no banco. Reabrir exige motivo; o autorizador é sempre derivado da sessão pelo servidor e todas as versões ficam preservadas.</p>{error&&<div><p role="alert" data-testid="fin15-read-error">{error}</p><button data-testid="fin15-retry" onClick={()=>void load()}>Tentar novamente</button></div>}
 <form data-testid="fin15-form" onSubmit={submit}><label>Competência <input data-testid="fin15-date" required type="date" value={form.competence_date} onChange={e=>setForm({...form,competence_date:e.target.value})}/></label><input data-testid="fin15-notes" required minLength={10} maxLength={2000} placeholder="Observações do fechamento" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button data-testid="fin15-create" disabled={busy}>Fechar competência</button></form>
 <h3>Selecionar competência</h3><input data-testid="fin15-search" placeholder="Buscar competência ou situação" value={search} onChange={e=>setSearch(e.target.value)}/><select data-testid="fin15-select" aria-label="Competência selecionada" value={selectedId} onChange={e=>{setSelectedId(e.target.value);setVersions([])}}><option value="">Selecione</option>{visible.map(x=><option key={x.id} value={x.id}>{x.competence_date.slice(0,7)} · {x.status}</option>)}</select>
 {selected&&<div data-testid="fin15-detail"><p>{selected.competence_date.slice(0,7)} · <strong data-testid="fin15-status">{selected.status}</strong></p>{selected.reopen_reason&&<p>Última reabertura: {selected.reopen_reason} · autorizador {selected.authorized_by_identity}</p>}<label>Motivo da ação <input data-testid="fin15-reason" minLength={10} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button data-testid="fin15-reopen" disabled={busy||selected.status!=="fechada"} onClick={()=>void act("reopen")}>Reabrir com autorização da sessão</button><button data-testid="fin15-close" disabled={busy||selected.status!=="reaberta"} onClick={()=>void act("close")}>Fechar novamente</button><button data-testid="fin15-versions" onClick={()=>void loadVersions()}>Ver versões preservadas</button></div>}
 {notice&&<p role="status" data-testid="fin15-notice">{notice}</p>}{versionsError&&<p role="alert">{versionsError}</p>}<ul data-testid="fin15-version-list">{versions.map(v=><li key={v.id}>versão {String(v.version)} · {v.report_type} · preservada: {String(v.is_preserved)} · autor {v.created_by_identity||"não informado"}</li>)}</ul>{!error&&rows.length===0&&<p data-testid="fin15-empty">Nenhuma competência encontrada.</p>}</section>
}
