"use client";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
type Closure={id:string;competence_date:string;status:string;notes:string|null;reopen_reason:string|null;authorized_by_identity:string|null};
type Version={id:string;closure_id:string;version:number;report_type:string;created_at:string};
async function api(path:string,init?:RequestInit){const r=await fetch(path,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Erro ${r.status}`);return d;}
export default function ClosureWorkspace(){
 const [rows,setRows]=useState<Closure[]>([]),[versions,setVersions]=useState<Version[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[selected,setSelected]=useState(""),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[form,setForm]=useState({competence_date:"",notes:""});
 const load=useCallback(async()=>{try{const d=await api("/api/fin/competence-closures");setRows(d.closures||[]);setError("");}catch(e){setError(`Não foi possível ler os fechamentos (${e instanceof Error?e.message:"falha"}).`);}},[]);
 const loadVersions=useCallback(async(id:string)=>{try{const d=await api(`/api/fin/report-versions?closure_id=${encodeURIComponent(id)}`);setVersions(d.versions||[]);setError("");}catch(e){setError(`Não foi possível ler as versões (${e instanceof Error?e.message:"falha"}).`);}},[]);
 useEffect(()=>{load();},[load]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return q?rows.filter(x=>`${x.competence_date} ${x.status}`.toLowerCase().includes(q)):rows;},[rows,search]);
 const create=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const id=`ui-close-${globalThis.crypto?.randomUUID?.()||Date.now()}`;const d=await api("/api/fin/competence-closures",{method:"POST",body:JSON.stringify({...form,idempotency_key:id,totals:{origem:"interface_sintetica"}})});setSelected(d.closure.id);setNotice(`Competência ${d.closure.competence_date.slice(0,10)} fechada após persistência. Novos lançamentos no mês estão bloqueados.`);await load();await loadVersions(d.closure.id);}catch(e){setNotice(`Falha ao fechar: ${e instanceof Error?e.message:"erro"}`);}finally{setBusy(false);}};
 const act=async(action:"reopen"|"close")=>{if(!selected)return;setBusy(true);try{const payload=action==="reopen"?{id:selected,action,reopen_reason:reason}:{id:selected,action,close_reason:reason};const d=await api("/api/fin/competence-closures",{method:"PATCH",body:JSON.stringify(payload)});setNotice(`${action==="reopen"?"Reabertura autorizada":"Novo fechamento"} persistido; versão ${d.version} preservada.`);setReason("");await load();await loadVersions(selected);}catch(e){setNotice(`Falha na competência: ${e instanceof Error?e.message:"erro"}`);}finally{setBusy(false);}};
 const current=rows.find(x=>x.id===selected);
 return <section data-testid="fin-closures-workspace"><h2>Fechamento e reabertura de competência</h2><p>Fechamento bloqueia lançamentos do mês no servidor e no banco. Reabertura exige motivo e preserva todas as versões.</p>
 {error&&<p role="alert" data-testid="fin-closures-error">{error}</p>}<button type="button" data-testid="fin-closures-retry" onClick={()=>{load();if(selected)loadVersions(selected);}}>Tentar novamente</button>{notice&&<p role="status" data-testid="fin-closures-notice">{notice}</p>}
 <form onSubmit={create}><label>Competência <input data-testid="fin15-date" required type="date" value={form.competence_date} onChange={e=>setForm({...form,competence_date:e.target.value})}/></label><label>Notas <input required minLength={10} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button data-testid="fin15-close" disabled={busy}>Fechar competência</button></form>
 <label>Buscar por competência/estado <input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Selecionar competência <select data-testid="fin15-select" value={selected} onChange={e=>{setSelected(e.target.value);if(e.target.value)loadVersions(e.target.value);}}><option value="">Selecione</option>{visible.map(x=><option key={x.id} value={x.id}>{x.competence_date.slice(0,10)} · {x.status}</option>)}</select></label>
 {current&&<div><p>Selecionada: {current.competence_date.slice(0,10)} · <strong>{current.status}</strong>{current.authorized_by_identity?" · reabertura auditada":""}</p><label>Motivo da ação sensível <textarea data-testid="fin15-reason" minLength={10} value={reason} onChange={e=>setReason(e.target.value)}/></label>{current.status==="fechada"?<button data-testid="fin15-reopen" disabled={busy||reason.trim().length<10} onClick={()=>act("reopen")}>Reabrir com autorização da sessão</button>:current.status==="reaberta"?<button disabled={busy||reason.trim().length<10} onClick={()=>act("close")}>Fechar novamente</button>:null}</div>}
 <h3>Versões preservadas</h3><ol data-testid="fin15-versions">{versions.map(v=><li key={v.id}>Versão {v.version} · {v.report_type} · {new Date(v.created_at).toLocaleString("pt-BR")}</li>)}</ol>
 </section>;
}
