"use client";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
type Provision={id:string;rule_id:string|null;commission_id:string|null;provision_date:string;amount_cents:number|string;status:string;revision_reason:string|null;reviewed_by_identity:string|null;is_auto_paid:boolean};
type History={id:string;provision_id:string;previous_status:string|null;next_status:string;reason:string;created_at:string;is_auto_paid_attempt:boolean};
const brl=(v:number|string)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)/100);
async function api(path:string,init?:RequestInit){const r=await fetch(path,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Erro ${r.status}`);return d;}
export default function CommissionWorkspace(){
 const [rows,setRows]=useState<Provision[]>([]),[history,setHistory]=useState<History[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[selected,setSelected]=useState(""),[reason,setReason]=useState(""),[revisionReason,setRevisionReason]=useState(""),[busy,setBusy]=useState(false),[form,setForm]=useState({rule_id:"",commission_id:"",provision_date:"",amount_cents:"",notes:""});
 const load=useCallback(async()=>{try{const d=await api("/api/fin/commission-provisions");setRows(d.provisions||[]);setError("");}catch(e){setError(`Não foi possível ler as provisões (${e instanceof Error?e.message:"falha"}).`);}},[]);
 const loadHistory=useCallback(async(id:string)=>{try{const d=await api(`/api/fin/commission-provision-history?provision_id=${encodeURIComponent(id)}`);setHistory(d.history||[]);setError("");}catch(e){setError(`Não foi possível ler o histórico (${e instanceof Error?e.message:"falha"}).`);}},[]);
 useEffect(()=>{load();},[load]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return q?rows.filter(x=>`${x.id} ${x.rule_id||""} ${x.commission_id||""}`.toLowerCase().includes(q)):rows;},[rows,search]);
 const create=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const id=`ui-commission-${globalThis.crypto?.randomUUID?.()||Date.now()}`;const d=await api("/api/fin/commission-provisions",{method:"POST",body:JSON.stringify({...form,rule_id:form.rule_id||null,commission_id:form.commission_id||null,amount_cents:Number(form.amount_cents),idempotency_key:id,is_auto_paid:false})});setSelected(d.provision.id);setNotice(`Provisão ${d.provision.id} persistida. Revisão obrigatória visível; nenhum pagamento foi executado.`);await load();await loadHistory(d.provision.id);}catch(e){setNotice(`Falha ao provisionar: ${e instanceof Error?e.message:"erro"}`);}finally{setBusy(false);}};
 const act=async(status:"em_revisao"|"revisada"|"cancelada")=>{if(!selected)return;setBusy(true);try{const d=await api("/api/fin/commission-provisions",{method:"PATCH",body:JSON.stringify({id:selected,status,reason,revision_reason:status==="cancelada"?undefined:revisionReason,is_auto_paid:false})});setNotice(`Estado ${d.provision.status} persistido e auditado. Pagamento automático permanece proibido.`);setReason("");setRevisionReason("");await load();await loadHistory(selected);}catch(e){setNotice(`Falha na revisão: ${e instanceof Error?e.message:"erro"}`);}finally{setBusy(false);}};
 const current=rows.find(x=>x.id===selected);
 return <section data-testid="fin-commissions-workspace"><h2>Provisão de comissão CRM-25</h2><p><strong>Sem pagamento automático.</strong> Esta jornada somente provisiona, revisa e audita. Não há botão de pagar, gateway ou baixa automática.</p>
 {error&&<p role="alert" data-testid="fin-commissions-error">{error}</p>}<button type="button" data-testid="fin-commissions-retry" onClick={()=>{load();if(selected)loadHistory(selected);}}>Tentar novamente</button>{notice&&<p role="status" data-testid="fin-commissions-notice">{notice}</p>}
 <form onSubmit={create}><label>ID da regra CRM-25 <input data-testid="fin16-rule" required value={form.rule_id} onChange={e=>setForm({...form,rule_id:e.target.value})}/></label><label>ID da comissão (opcional) <input value={form.commission_id} onChange={e=>setForm({...form,commission_id:e.target.value})}/></label><label>Data <input required type="date" value={form.provision_date} onChange={e=>setForm({...form,provision_date:e.target.value})}/></label><label>Valor em centavos <input data-testid="fin16-amount" required type="number" min="0" value={form.amount_cents} onChange={e=>setForm({...form,amount_cents:e.target.value})}/></label><label>Notas <input required minLength={10} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button data-testid="fin16-create" disabled={busy}>Criar provisão</button></form>
 <label>Buscar por registro/regra <input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Selecionar provisão <select data-testid="fin16-select" value={selected} onChange={e=>{setSelected(e.target.value);if(e.target.value)loadHistory(e.target.value);}}><option value="">Selecione</option>{visible.map(x=><option key={x.id} value={x.id}>{x.id.slice(0,8)} · {x.rule_id?.slice(0,8)||"sem regra"} · {brl(x.amount_cents)} · {x.status}</option>)}</select></label>
 {current&&<div data-testid="fin16-review"><p>{brl(current.amount_cents)} · {current.status} · revisão: {current.reviewed_by_identity?"auditada":"obrigatória e pendente"} · pagamento automático: {current.is_auto_paid?"INDEVIDO":"proibido"}</p><label>Motivo da ação <textarea data-testid="fin16-reason" minLength={10} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Motivo da revisão <textarea data-testid="fin16-revision-reason" minLength={10} value={revisionReason} onChange={e=>setRevisionReason(e.target.value)}/></label>{current.status==="provisionada"&&<button disabled={busy||reason.length<10||revisionReason.length<10} onClick={()=>act("em_revisao")}>Iniciar revisão</button>}{current.status==="em_revisao"&&<button disabled={busy||reason.length<10||revisionReason.length<10} onClick={()=>act("revisada")}>Concluir revisão</button>}{!['paga','cancelada'].includes(current.status)&&<button disabled={busy||reason.length<10} onClick={()=>act("cancelada")}>Cancelar com motivo</button>}</div>}
 <h3>Histórico auditável</h3><ol data-testid="fin16-history">{history.map(h=><li key={h.id}>{h.previous_status||"criação"} → {h.next_status} · {h.reason} · automático: {h.is_auto_paid_attempt?"sim":"não"}</li>)}</ol>
 </section>;
}
