"use client";
import styles from "../../../components/ui/UiWorkspace.module.css";
import { financeErrorMessage } from "../../../lib/finance-vocabulary.mjs";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
type Provision={id:string;rule_id:string|null;provision_date:string;amount_cents:number|string;status:string;is_auto_paid:boolean;reviewed_by_identity:string|null;reviewed_at:string|null;revision_reason:string|null;paid_by_identity:string|null};
type History={id:string;previous_status:string|null;next_status:string;previous_amount:number|string|null;next_amount:number|string|null;changed_by_identity:string|null;reason:string;created_at:string;is_auto_paid_attempt:boolean};
const brl=(v:number|string|null)=>v===null?"valor ausente":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)/100);
async function api(path:string,init?:RequestInit){const r=await fetch(path,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(financeErrorMessage(typeof d.error === "string" ? d.error : null, r.status));return d;}
export default function CommissionWorkspace(){
 const [rows,setRows]=useState<Provision[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[search,setSearch]=useState(""),[selectedId,setSelectedId]=useState(""),[history,setHistory]=useState<History[]>([]),[historyError,setHistoryError]=useState(""),[reason,setReason]=useState(""),[revisionReason,setRevisionReason]=useState(""),[revisedAmount,setRevisedAmount]=useState("");const [form,setForm]=useState({rule_id:"",provision_date:"",amount_cents:"",notes:"",idempotency_key:""});
 const load=useCallback(async()=>{try{const d=await api("/api/fin/commission-provisions");setRows(d.provisions||[]);setError("")}catch(e){setError(`Não foi possível ler as provisões: ${e instanceof Error?e.message:"falha"}`)}},[]);useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return q?rows.filter(x=>`${x.rule_id||""} ${x.status} ${x.provision_date}`.toLowerCase().includes(q)):rows},[rows,search]);const selected=rows.find(x=>x.id===selectedId)||null;
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{const key=form.idempotency_key||`fin16-ui-${crypto.randomUUID()}`;const d=await api("/api/fin/commission-provisions",{method:"POST",body:JSON.stringify({...form,rule_id:form.rule_id||null,amount_cents:Number(form.amount_cents),idempotency_key:key,is_auto_paid:false})});setNotice(`Provisão ${d.idempotent_replay?"já persistida; replay sem duplicação":"persistida"}. Revisão humana obrigatória; nenhum pagamento foi executado.`);setForm({...form,idempotency_key:key});await load();setSelectedId(d.provision.id)}catch(e){setNotice(`Falha: ${e instanceof Error?e.message:"inesperada"}`)}finally{setBusy(false)}}
 async function transition(status:string,manual=false){if(!selected)return;setBusy(true);try{const body:Record<string,unknown>={id:selected.id,status,reason,is_auto_paid:false};if(["em_revisao","revisada"].includes(status))body.revision_reason=revisionReason;if(revisedAmount!=="")body.amount_cents=Number(revisedAmount);if(manual)body.manual_payment_confirmation=true;const d=await api("/api/fin/commission-provisions",{method:"PATCH",body:JSON.stringify(body)});setNotice(status==="paga"?"Baixa manual apenas registrada após revisão; nenhum pagamento automático ou externo foi executado.":`Estado ${d.provision.status} confirmado após persistência.`);await load();await loadHistory(selected.id)}catch(e){setNotice(`Falha: ${e instanceof Error?e.message:"inesperada"}`)}finally{setBusy(false)}}
 async function loadHistory(id=selectedId){if(!id)return;try{const d=await api(`/api/fin/commission-provision-history?provision_id=${id}`);setHistory(d.history||[]);setHistoryError("")}catch(e){setHistoryError(`Falha ao ler histórico: ${e instanceof Error?e.message:"erro"}`)}}
 return <section data-testid="finance-commission-workspace"><h2>Provisões de comissão</h2><p data-testid="fin16-no-auto-pay"><strong>Pagamento automático proibido.</strong> A provisão ligada à regra CRM-25 exige revisão humana auditável. Uma baixa manual registra somente o fato informado; não aciona banco, Pix, boleto ou gateway.</p>{error&&<div><p role="alert" data-testid="fin16-read-error">{error}</p><button data-testid="fin16-retry" onClick={()=>void load()}>Tentar novamente</button></div>}
 <form data-testid="fin16-form" onSubmit={submit} className={styles.stack}><input data-testid="fin16-rule" placeholder="ID da regra CRM-25 (opcional)" value={form.rule_id} onChange={e=>setForm({...form,rule_id:e.target.value})}/><input data-testid="fin16-date" required type="date" value={form.provision_date} onChange={e=>setForm({...form,provision_date:e.target.value})}/><label>Valor em centavos <input data-testid="fin16-amount" required type="number" min="0" value={form.amount_cents} onChange={e=>setForm({...form,amount_cents:e.target.value})}/><span data-testid="fin16-amount-preview">{form.amount_cents===""?"Valor não informado":brl(form.amount_cents)}</span></label><textarea data-testid="fin16-notes" required minLength={10} maxLength={2000} placeholder="Base sintética da provisão" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><input data-testid="fin16-key" minLength={8} placeholder="Chave de idempotência (opcional)" value={form.idempotency_key} onChange={e=>setForm({...form,idempotency_key:e.target.value})}/><button data-testid="fin16-create" disabled={busy}>Criar provisão</button></form>
 <h3>Selecionar por regra, data ou situação</h3><input data-testid="fin16-search" placeholder="Buscar provisão" value={search} onChange={e=>setSearch(e.target.value)}/><select data-testid="fin16-select" aria-label="Provisão selecionada" value={selectedId} onChange={e=>{setSelectedId(e.target.value);setHistory([])}}><option value="">Selecione</option>{visible.map(x=><option key={x.id} value={x.id}>{x.rule_id||"sem regra"} · {x.provision_date.slice(0,10)} · {x.status}</option>)}</select>
 {selected&&<div data-testid="fin16-detail"><p><strong data-testid="fin16-status">{selected.status}</strong> · <span data-testid="fin16-value">{brl(selected.amount_cents)}</span> · automático: {String(selected.is_auto_paid)}</p>{selected.revision_reason&&<p data-testid="fin16-review-audit">Revisão: {selected.revision_reason} · autor {selected.reviewed_by_identity} · {selected.reviewed_at&&new Date(selected.reviewed_at).toLocaleString("pt-BR")}</p>}<label>Motivo da ação <input data-testid="fin16-reason" minLength={10} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Motivo da revisão <input data-testid="fin16-revision-reason" minLength={10} value={revisionReason} onChange={e=>setRevisionReason(e.target.value)}/></label><label>Valor revisado em centavos <input data-testid="fin16-revised-amount" type="number" min="0" value={revisedAmount} onChange={e=>setRevisedAmount(e.target.value)}/></label><button data-testid="fin16-start-review" disabled={busy||selected.status!=="provisionada"} onClick={()=>void transition("em_revisao")}>Iniciar revisão</button><button data-testid="fin16-finish-review" disabled={busy||selected.status!=="em_revisao"} onClick={()=>void transition("revisada")}>Concluir revisão</button><button data-testid="fin16-manual-paid" disabled={busy||selected.status!=="revisada"} onClick={()=>void transition("paga",true)}>Registrar baixa manual (não pagar)</button><button data-testid="fin16-history" onClick={()=>void loadHistory()}>Ver histórico auditável</button></div>}
 {notice&&<p role="status" data-testid="fin16-notice">{notice}</p>}{historyError&&<p role="alert">{historyError}</p>}<ul data-testid="fin16-history-list">{history.map(x=><li key={x.id}>{x.previous_status||"início"} → {x.next_status} · {brl(x.next_amount)} · autor {x.changed_by_identity||"não informado"} · motivo: {x.reason} · tentativa automática: {String(x.is_auto_paid_attempt)}</li>)}</ul>{!error&&rows.length===0&&<p data-testid="fin16-empty">Nenhuma provisão encontrada.</p>}</section>
}
