"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type ExportRow={id:string;protocol:string;period_start:string;period_end:string;status:string;total_records:number;total_amount_cents:number|string;file_name:string|null;is_accountant_limited:boolean;access_role:string};
const brl=(v:number|string)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)/100);
async function api(path:string,init?:RequestInit){const r=await fetch(path,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Erro ${r.status}`);return d;}
const key=()=>`ui-exp-${globalThis.crypto?.randomUUID?.()||Date.now()}`;
export default function ExportWorkspace(){
 const [rows,setRows]=useState<ExportRow[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({period_start:"",period_end:"",total_records:"0",total_amount_cents:"0"});
 const load=useCallback(async()=>{try{const d=await api("/api/fin/exports");setRows(d.exports||[]);setError("");}catch(e){setError(`Não foi possível ler as exportações (${e instanceof Error?e.message:"falha"}).`);}},[]);
 useEffect(()=>{load();},[load]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return q?rows.filter(x=>`${x.protocol} ${x.file_name||""}`.toLowerCase().includes(q)):rows;},[rows,search]);
 const create=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setNotice("");try{const id=key();const d=await api("/api/fin/exports",{method:"POST",body:JSON.stringify({...form,total_records:Number(form.total_records),total_amount_cents:Number(form.total_amount_cents),filters:{origem:"interface_financeira",periodo_autorizado:true},totals:{total_amount_cents:Number(form.total_amount_cents)},file_name:`exportacao-${form.period_start}-${form.period_end}.json`,storage_key:`synthetic/fin14/${id}.json`,idempotency_key:id,is_accountant_limited:true})});setNotice(`Exportação ${d.export.protocol} persistida com acesso limitado do contador.`);await load();}catch(e){setNotice(`Falha ao exportar: ${e instanceof Error?e.message:"erro"}`);}finally{setBusy(false);}};
 const transition=async(row:ExportRow,status:string)=>{setBusy(true);try{const d=await api("/api/fin/exports",{method:"PATCH",body:JSON.stringify({id:row.id,status})});setNotice(`Estado ${d.export.status} persistido para ${row.protocol}.`);await load();}catch(e){setNotice(`Falha na exportação: ${e instanceof Error?e.message:"erro"}`);}finally{setBusy(false);}};
 return <section data-testid="fin-exports-workspace"><h2>Exportação do período</h2><p>Arquivo sintético em JSON, limitado ao período e aos totais autorizados para o contador. Nenhum dado ou envio real.</p>
 {error&&<p role="alert" data-testid="fin-exports-error">{error}</p>}<button type="button" data-testid="fin-exports-retry" onClick={load}>Tentar novamente</button>{notice&&<p role="status" data-testid="fin-exports-notice">{notice}</p>}
 <form onSubmit={create}><label>Início <input data-testid="fin14-start" required type="date" value={form.period_start} onChange={e=>setForm({...form,period_start:e.target.value})}/></label><label>Fim <input data-testid="fin14-end" required type="date" value={form.period_end} onChange={e=>setForm({...form,period_end:e.target.value})}/></label><label>Registros <input required type="number" min="0" value={form.total_records} onChange={e=>setForm({...form,total_records:e.target.value})}/></label><label>Total em centavos <input data-testid="fin14-amount" required type="number" min="0" value={form.total_amount_cents} onChange={e=>setForm({...form,total_amount_cents:e.target.value})}/></label><button data-testid="fin14-create" disabled={busy}>Registrar exportação</button></form>
 <label>Buscar por protocolo/arquivo <input data-testid="fin14-search" value={search} onChange={e=>setSearch(e.target.value)}/></label>
 <ul data-testid="fin14-list">{visible.length===0?<li>Nenhuma exportação encontrada.</li>:visible.map(x=><li key={x.id}><strong>{x.protocol}</strong> · {x.period_start.slice(0,10)} a {x.period_end.slice(0,10)} · {brl(x.total_amount_cents)} · {x.status} · acesso: {x.access_role} limitado{x.status==="pendente"&&<button onClick={()=>transition(x,"gerando")}>Iniciar geração</button>}{x.status==="gerando"&&<button onClick={()=>transition(x,"gerado")}>Confirmar geração persistida</button>}{x.status==="gerado"&&<a data-testid={`fin14-download-${x.id}`} href={`/api/fin/export-download?id=${encodeURIComponent(x.id)}`}>Baixar JSON autorizado</a>}</li>)}</ul>
 </section>;
}
