"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type ExportRow = { id:string; protocol:string; period_start:string; period_end:string; status:string; total_records:number|string; total_amount_cents:number|string; file_name:string|null; storage_key:string|null; is_accountant_limited:boolean; access_role:string; generated_at:string|null };
type ExportLog = { id:string; action:string; actor_identity:string|null; created_at:string; meta:Record<string,unknown> };
const brl=(v:number|string)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)/100);
async function api(path:string,init?:RequestInit){const r=await fetch(path,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(d.error||`Erro ${r.status}`));return d;}

export default function ExportWorkspace(){
 const [rows,setRows]=useState<ExportRow[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[search,setSearch]=useState(""),[selectedId,setSelectedId]=useState(""),[logs,setLogs]=useState<ExportLog[]>([]),[logsError,setLogsError]=useState("");
 const [form,setForm]=useState({period_start:"",period_end:"",total_records:"",total_amount_cents:"",file_name:""});
 const load=useCallback(async()=>{try{const d=await api("/api/fin/exports");setRows(d.exports||[]);setError("");}catch(e){setError(`Não foi possível ler as exportações: ${e instanceof Error?e.message:"falha"}`);}},[]);
 useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>{const q=search.trim().toLocaleLowerCase("pt-BR");return q?rows.filter(x=>`${x.protocol} ${x.file_name||""}`.toLocaleLowerCase("pt-BR").includes(q)):rows},[rows,search]);
 const selected=rows.find(x=>x.id===selectedId)||null;
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setNotice("");try{const key=`synthetic/fin14/${form.period_start}-${form.period_end}-${form.file_name}`;const d=await api("/api/fin/exports",{method:"POST",body:JSON.stringify({...form,total_records:Number(form.total_records),total_amount_cents:Number(form.total_amount_cents),filters:{origem:"interface_sintetica"},totals:{total_cents:Number(form.total_amount_cents)},storage_key:key,is_accountant_limited:true})});setNotice(`Exportação ${d.export.protocol} ${d.idempotent_replay?"já persistida; replay sem duplicação":"persistida com acesso limitado"}.`);await load();setSelectedId(d.export.id);}catch(e){setNotice(`Falha: ${e instanceof Error?e.message:"inesperada"}`)}finally{setBusy(false)}}
 async function transition(status:string){if(!selected)return;setBusy(true);try{const d=await api("/api/fin/exports",{method:"PATCH",body:JSON.stringify({id:selected.id,status})});setNotice(`Estado ${d.export.status} confirmado após persistência.`);await load();}catch(e){setNotice(`Falha: ${e instanceof Error?e.message:"inesperada"}`)}finally{setBusy(false)}}
 async function loadLogs(){if(!selected)return;try{const d=await api(`/api/fin/export-logs?export_id=${selected.id}`);setLogs(d.logs||[]);setLogsError("")}catch(e){setLogsError(`Falha ao ler trilha: ${e instanceof Error?e.message:"erro"}`)}}
 return <section data-testid="finance-export-workspace"><h2>Exportação do período</h2><p>Artefato sintético, com filtros e totais conciliáveis. Leitura e download são limitados no servidor; nenhum dado é enviado a contador ou serviço externo.</p>
 {error&&<div><p role="alert" data-testid="fin14-read-error">{error}</p><button data-testid="fin14-retry" onClick={()=>void load()}>Tentar novamente</button></div>}
 <form data-testid="fin14-form" onSubmit={submit} style={{display:"grid",gap:8}}><label>Início <input data-testid="fin14-start" required type="date" value={form.period_start} onChange={e=>setForm({...form,period_start:e.target.value})}/></label><label>Fim <input data-testid="fin14-end" required type="date" value={form.period_end} onChange={e=>setForm({...form,period_end:e.target.value})}/></label><input data-testid="fin14-records" required type="number" min="0" placeholder="Quantidade de registros" value={form.total_records} onChange={e=>setForm({...form,total_records:e.target.value})}/><label>Valor total em centavos <input data-testid="fin14-amount" required type="number" min="0" value={form.total_amount_cents} onChange={e=>setForm({...form,total_amount_cents:e.target.value})}/><span data-testid="fin14-amount-preview">{form.total_amount_cents===""?"Valor não informado":brl(form.total_amount_cents)}</span></label><input data-testid="fin14-file" required minLength={1} placeholder="Nome do arquivo sintético" value={form.file_name} onChange={e=>setForm({...form,file_name:e.target.value})}/><button data-testid="fin14-create" disabled={busy}>Solicitar exportação</button></form>
 <h3>Selecionar por nome ou protocolo</h3><input data-testid="fin14-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar nome ou protocolo"/><select data-testid="fin14-select" aria-label="Exportação selecionada" value={selectedId} onChange={e=>{setSelectedId(e.target.value);setLogs([])}}><option value="">Selecione</option>{visible.map(x=><option key={x.id} value={x.id}>{x.protocol} · {x.file_name||"sem nome"} · {x.status}</option>)}</select>
 {selected&&<div data-testid="fin14-detail"><p>{selected.protocol} · {selected.period_start.slice(0,10)} a {selected.period_end.slice(0,10)} · <strong data-testid="fin14-status">{selected.status}</strong></p><p data-testid="fin14-total">{brl(selected.total_amount_cents)} · {String(selected.total_records)} registros · acesso {selected.access_role} limitado: {String(selected.is_accountant_limited)}</p><button data-testid="fin14-generating" disabled={busy||selected.status!=="pendente"} onClick={()=>void transition("gerando")}>Iniciar geração</button><button data-testid="fin14-generated" disabled={busy||selected.status!=="gerando"} onClick={()=>void transition("gerado")}>Concluir geração sintética</button><button data-testid="fin14-download" disabled={selected.status!=="gerado"} onClick={()=>{window.location.href=`/api/fin/export-download?id=${selected.id}`}}>Baixar artefato limitado</button><button data-testid="fin14-logs" onClick={()=>void loadLogs()}>Ver trilha</button></div>}
 {notice&&<p role="status" data-testid="fin14-notice">{notice}</p>}{logsError&&<p role="alert">{logsError}</p>}<ul data-testid="fin14-log-list">{logs.map(x=><li key={x.id}>{x.action} · autor {x.actor_identity||"não informado"} · {new Date(x.created_at).toLocaleString("pt-BR")}</li>)}</ul>
 {!error&&rows.length===0&&<p data-testid="fin14-empty">Nenhuma exportação encontrada.</p>}</section>
}
