"use client";

import { FormEvent, useEffect, useState } from "react";

type Account = { id:string; protocol:string; contract_id:string|null; client_account_id:string|null; competence_date:string; due_date:string; amount_cents:string|number; amount_paid_cents:string|number; amount_remaining_cents?:string|number; status:string; description?:string|null };
type Rule = { id:string; contract_id:string; recurrence_id:string; amount_cents:string|number; start_date:string; is_approved:boolean; is_active:boolean; suspension_enabled:boolean };
type Payment = { id:string; account_type:string; receivable_id:string|null; payable_id:string|null; amount_cents:string|number; is_estorno:boolean; created_at:string };
type BankStatement = { id:string; protocol:string; source:string; file_name:string; import_date:string; total_transactions:string|number; total_amount_cents:string|number };
type BankTransaction = { id:string; statement_id:string; transaction_date:string; amount_cents:string|number; description:string; bank_ref:string; is_conciliated:boolean };
type Conciliation = { id:string; status:string; bank_ref:string; bank_amount_cents:string|number; receivable_protocol:string|null; payable_protocol:string|null; amount_matched_cents:string|number; suggestion_reason:string|null };

type Tab = "receivables"|"recurrence"|"payments"|"reconciliation";
const money = (value: string|number|undefined) => value == null ? "Dado ausente" : `R$ ${(Number(value)/100).toFixed(2).replace(".",",")}`;
async function api(path:string, init?:RequestInit) {
  const response=await fetch(path, { ...init, headers:{ "Content-Type":"application/json", ...(init?.headers||{}) } });
  const data=await response.json().catch(()=>({}));
  if(!response.ok) throw new Error(data.error || `Erro ${response.status}`);
  return data;
}

export default function FinanceiroWorkspace() {
  const [tab,setTab] = useState<Tab>("receivables");
  const [accounts,setAccounts] = useState<Account[]>([]); const [rules,setRules] = useState<Rule[]>([]); const [payments,setPayments] = useState<Payment[]>([]);
  const [statements,setStatements] = useState<BankStatement[]>([]); const [bankTransactions,setBankTransactions] = useState<BankTransaction[]>([]); const [conciliations,setConciliations] = useState<Conciliation[]>([]);
  const [contractFilter,setContractFilter] = useState(""); const [selected,setSelected] = useState<Account|null>(null); const [busy,setBusy] = useState(false); const [error,setError] = useState(""); const [notice,setNotice] = useState("");
  const [newAccount,setNewAccount] = useState({ client_account_id:"", contract_id:"", competence_date:"", due_date:"", amount_cents:"", description:"" });
  const [newRule,setNewRule] = useState({ contract_id:"", recurrence_id:"", start_date:"", amount_cents:"" }); const [generationClientAccountId,setGenerationClientAccountId] = useState("");
  const [paymentAmount,setPaymentAmount] = useState(""); const [reason,setReason] = useState(""); const [estorno,setEstorno] = useState<Payment|null>(null); const [history,setHistory] = useState<Record<string,unknown>[]>([]);
  const [statementForm,setStatementForm] = useState({ source:"importacao", file_name:"extrato-sintetico.csv", storage_key:"", import_date:"", transaction_date:"", amount_cents:"", description:"", bank_ref:"" });
  const [selectedBankTransactionId,setSelectedBankTransactionId] = useState("");
  const run = async (fn:()=>Promise<void>) => { setBusy(true); setError(""); setNotice(""); try { await fn(); } catch(e) { setError(e instanceof Error?e.message:"Falha inesperada"); } finally { setBusy(false); } };
  const load = () => run(async()=> {
    const [a,r,p,s,t,c] = await Promise.all([
      api(`/api/fin/receivables${contractFilter?`?contract_id=${encodeURIComponent(contractFilter)}`:""}`), api("/api/fin/recurrence-rules"), api("/api/fin/payments"),
      api("/api/fin/bank-statements"), api("/api/fin/bank-transactions"), api("/api/fin/conciliations")
    ]);
    const nextAccounts:Account[]=a.receivables||[]; setAccounts(nextAccounts); setRules(r.rules||[]); setPayments(p.payments||[]); setStatements(s.statements||[]); setBankTransactions(t.transactions||[]); setConciliations(c.conciliations||[]);
    if(selected){ setSelected(nextAccounts.find(item=>item.id===selected.id)||selected); const h=await api(`/api/fin/payment-history?receivable_id=${selected.id}`); setHistory(h.history||[]); }
  });
  useEffect(()=>{ load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const createAccount = async (event:FormEvent) => { event.preventDefault(); await run(async()=> { await api("/api/fin/receivables", {method:"POST",body:JSON.stringify({...newAccount, amount_cents:Number(newAccount.amount_cents), is_recurring:false})}); setNotice("Recebível criado"); setNewAccount({client_account_id:"",contract_id:"",competence_date:"",due_date:"",amount_cents:"",description:""}); await load(); }); };
  const createRule = async (event:FormEvent) => { event.preventDefault(); await run(async()=> { await api("/api/fin/recurrence-rules", {method:"POST",body:JSON.stringify({...newRule, amount_cents:Number(newRule.amount_cents), recurrence_type:"mensal"})}); setNotice("Regra criada e aguardando aprovação"); setNewRule({contract_id:"",recurrence_id:"",start_date:"",amount_cents:""}); await load(); }); };
  const approve = (rule:Rule) => run(async()=> { await api("/api/fin/recurrence-rules",{method:"PATCH",body:JSON.stringify({id:rule.id,is_approved:true})}); setNotice("Regra aprovada"); await load(); });
  const generate = (rule:Rule) => run(async()=> { if(!generationClientAccountId) throw new Error("Informe a conta do cliente para gerar a cobrança"); const date=rule.start_date.slice(0,10); await api("/api/fin/generate-recurring",{method:"POST",body:JSON.stringify({recurrence_rule_id:rule.id,competence_date:date,due_date:date,client_account_id:generationClientAccountId,contract_id:rule.contract_id,amount_cents:Number(rule.amount_cents)})}); setNotice("Cobrança gerada"); await load(); });
  const pay = async (event:FormEvent) => { event.preventDefault(); if(!selected) return; await run(async()=> { const data=await api("/api/fin/payments",{method:"POST",body:JSON.stringify({account_type:"receber",receivable_id:selected.id,amount_cents:Number(paymentAmount),reason,is_partial:true})}); setNotice(data.note||"Baixa registrada"); setPaymentAmount(""); setReason(""); await load(); }); };
  const doEstorno = async () => { if(!selected||!estorno) return; await run(async()=> { await api("/api/fin/payments",{method:"POST",body:JSON.stringify({account_type:"receber",receivable_id:selected.id,amount_cents:Number(estorno.amount_cents),reason,is_estorno:true,previous_payment_id:estorno.id})}); setNotice("Estorno registrado"); setEstorno(null); setReason(""); await load(); }); };
  const openAccount = (account:Account) => run(async()=> { setSelected(account); const data=await api(`/api/fin/payment-history?receivable_id=${account.id}`); setHistory(data.history||[]); });
  const importStatement = async (event:FormEvent) => { event.preventDefault(); await run(async()=> {
    const key = statementForm.storage_key || `synthetic-extract-${Date.now()}`;
    await api("/api/fin/bank-statements", { method:"POST", body:JSON.stringify({
      source:statementForm.source, file_name:statementForm.file_name, file_url:`synthetic://${key}`, storage_key:key, import_date:statementForm.import_date,
      transactions:[{ transaction_date:statementForm.transaction_date, amount_cents:Number(statementForm.amount_cents), description:statementForm.description, bank_ref:statementForm.bank_ref }]
    })});
    setNotice("Extrato sintético importado sem acessar banco ou provedor externo");
    setStatementForm({source:"importacao",file_name:"extrato-sintetico.csv",storage_key:"",import_date:"",transaction_date:"",amount_cents:"",description:"",bank_ref:""});
    await load();
  }); };
  const suggestConciliation = () => run(async()=> { if(!selected) throw new Error("Selecione um recebível antes de sugerir a conciliação"); if(!selectedBankTransactionId) throw new Error("Selecione um movimento do extrato"); await api("/api/fin/conciliations", {method:"POST",body:JSON.stringify({receivable_id:selected.id,bank_transaction_id:selectedBankTransactionId,source:"importacao"})}); setNotice("Sugestão criada; confirme-a explicitamente"); await load(); });
  const confirmConciliation = (conciliation:Conciliation) => run(async()=> { await api("/api/fin/conciliations", {method:"PATCH",body:JSON.stringify({id:conciliation.id,status:"conciliada"})}); setNotice("Conciliação confirmada; nenhum pagamento foi criado"); await load(); });
  return <main data-testid="financeiro-workspace" style={{padding:"2rem",maxWidth:1200,margin:"auto"}}>
    <header><h1>Financeiro</h1><p>Contas, recorrência, pagamentos e conciliação sintética com auditoria transacional.</p></header>
    <nav aria-label="Abas financeiras" style={{display:"flex",gap:8,margin:"1rem 0",flexWrap:"wrap"}}>{[["receivables","Recebíveis"],["recurrence","Recorrência"],["payments","Pagamentos"],["reconciliation","Conciliação"]].map(([id,label])=><button key={id} data-testid={`finance-tab-${id}`} onClick={()=>setTab(id as Tab)} aria-selected={tab===id}>{label}</button>)}</nav>
    {error&&<p role="alert" data-testid="finance-error">{error}</p>}{notice&&<p role="status" data-testid="finance-notice">{notice}</p>}{busy&&<p data-testid="finance-loading">Carregando...</p>}
    {tab==="receivables"&&<section data-testid="finance-receivables"><h2>Recebíveis</h2><form onSubmit={createAccount}><input required placeholder="ID da conta do cliente" value={newAccount.client_account_id} onChange={e=>setNewAccount({...newAccount,client_account_id:e.target.value})}/><input placeholder="ID do contrato" value={newAccount.contract_id} onChange={e=>setNewAccount({...newAccount,contract_id:e.target.value})}/><input required type="date" aria-label="Competência" value={newAccount.competence_date} onChange={e=>setNewAccount({...newAccount,competence_date:e.target.value})}/><input required type="date" aria-label="Vencimento" value={newAccount.due_date} onChange={e=>setNewAccount({...newAccount,due_date:e.target.value})}/><input required type="number" min="1" placeholder="Valor em centavos" value={newAccount.amount_cents} onChange={e=>setNewAccount({...newAccount,amount_cents:e.target.value})}/><button disabled={busy}>Criar recebível</button></form><hr/><form onSubmit={e=>{e.preventDefault();load()}}><input data-testid="finance-contract-filter" placeholder="Filtrar por contrato" value={contractFilter} onChange={e=>setContractFilter(e.target.value)}/><button>Filtrar</button></form><AccountTable accounts={accounts} onSelect={openAccount}/></section>}
    {tab==="recurrence"&&<section data-testid="finance-recurrence"><h2>Recorrência</h2><label>Conta do cliente para geração <input required data-testid="finance-generation-client-account" placeholder="ID da conta do cliente para geração" value={generationClientAccountId} onChange={e=>setGenerationClientAccountId(e.target.value)}/></label><form onSubmit={createRule}><input required placeholder="ID do contrato" value={newRule.contract_id} onChange={e=>setNewRule({...newRule,contract_id:e.target.value})}/><input required placeholder="Identificador da regra" value={newRule.recurrence_id} onChange={e=>setNewRule({...newRule,recurrence_id:e.target.value})}/><input required type="date" value={newRule.start_date} onChange={e=>setNewRule({...newRule,start_date:e.target.value})}/><input required type="number" min="1" placeholder="Valor em centavos" value={newRule.amount_cents} onChange={e=>setNewRule({...newRule,amount_cents:e.target.value})}/><button>Criar regra</button></form><ul>{rules.length===0?<li data-testid="finance-recurrence-empty">Nenhuma regra encontrada.</li>:rules.map(rule=><li data-testid={`finance-rule-${rule.id}`} key={rule.id}>Contrato {rule.contract_id} · {money(rule.amount_cents)} · {rule.is_approved?"aprovada":"pendente"} <button disabled={rule.is_approved} onClick={()=>approve(rule)}>Aprovar</button> <button disabled={!rule.is_approved||!rule.is_active} onClick={()=>generate(rule)}>Gerar cobrança</button></li>)}</ul></section>}
    {tab==="payments"&&<section data-testid="finance-payments"><h2>Pagamentos</h2><PaymentTable payments={payments}/>{selected&&<><h3>Conta {selected.protocol}</h3><p>Saldo pago: {money(selected.amount_paid_cents)} de {money(selected.amount_cents)} · status {selected.status}</p><form onSubmit={pay}><input required type="number" min="1" placeholder="Baixa em centavos" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)}/><input required minLength={10} maxLength={1000} placeholder="Motivo (10 a 1000 caracteres)" value={reason} onChange={e=>setReason(e.target.value)}/><button>Dar baixa</button></form><ul>{history.map((item,i)=><li key={i}>{String(item.reason||"Histórico sem motivo")} · {String(item.next_status||"")}</li>)}</ul>{payments.filter(p=>p.receivable_id===selected.id&&!p.is_estorno).map(p=><button key={p.id} onClick={()=>setEstorno(p)}>Estornar pagamento de {money(p.amount_cents)}</button>)}{estorno&&<button onClick={doEstorno}>Confirmar estorno</button>}</>}</section>}
    {tab==="reconciliation"&&<section data-testid="finance-reconciliation"><h2>FIN-05 — Conciliação bancária sintética</h2><p>Importe somente um extrato sintético local, escolha o recebível já selecionado, gere uma sugestão e confirme-a. Este fluxo não busca arquivos, não chama provedor e não cria baixa financeira.</p><form onSubmit={importStatement}><select aria-label="Origem do extrato" value={statementForm.source} onChange={e=>setStatementForm({...statementForm,source:e.target.value})}><option value="importacao">Importação sintética</option><option value="extrato">Extrato sintético</option><option value="provedor">Provedor simulado</option></select><input required placeholder="Nome do extrato sintético" value={statementForm.file_name} onChange={e=>setStatementForm({...statementForm,file_name:e.target.value})}/><input placeholder="Chave sintética do extrato" value={statementForm.storage_key} onChange={e=>setStatementForm({...statementForm,storage_key:e.target.value})}/><input required type="date" aria-label="Data de importação" value={statementForm.import_date} onChange={e=>setStatementForm({...statementForm,import_date:e.target.value})}/><input required type="date" aria-label="Data do movimento" value={statementForm.transaction_date} onChange={e=>setStatementForm({...statementForm,transaction_date:e.target.value})}/><input required type="number" placeholder="Valor do movimento em centavos" value={statementForm.amount_cents} onChange={e=>setStatementForm({...statementForm,amount_cents:e.target.value})}/><input required minLength={3} placeholder="Descrição do movimento sintético" value={statementForm.description} onChange={e=>setStatementForm({...statementForm,description:e.target.value})}/><input required minLength={3} placeholder="Referência bancária sintética" value={statementForm.bank_ref} onChange={e=>setStatementForm({...statementForm,bank_ref:e.target.value})}/><button disabled={busy}>Importar extrato sintético</button></form>
      <h3>Extratos importados</h3><StatementTable statements={statements}/><h3>Sugerir conciliação</h3><p data-testid="finance-selected-receivable">{selected?`Recebível selecionado: ${selected.protocol} (${money(selected.amount_remaining_cents ?? selected.amount_cents)})`:"Nenhum recebível selecionado. Volte à aba Recebíveis e selecione uma linha."}</p><label>Movimento bancário <select data-testid="finance-bank-transaction" value={selectedBankTransactionId} onChange={e=>setSelectedBankTransactionId(e.target.value)}><option value="">Selecione</option>{bankTransactions.filter(item=>!item.is_conciliated).map(item=><option key={item.id} value={item.id}>{item.bank_ref} · {money(item.amount_cents)} · {item.description}</option>)}</select></label><button disabled={busy||!selected} onClick={suggestConciliation}>Sugerir conciliação</button>
      <h3>Conciliações</h3><table data-testid="finance-conciliations-table"><thead><tr><th>Movimento</th><th>Conta</th><th>Valor</th><th>Status</th><th>Ação</th></tr></thead><tbody>{conciliations.length===0?<tr><td colSpan={5}>Nenhuma conciliação encontrada.</td></tr>:conciliations.map(item=><tr key={item.id} data-testid={`finance-conciliation-${item.id}`}><td>{item.bank_ref}</td><td>{item.receivable_protocol||item.payable_protocol||"Conta ausente"}</td><td>{money(item.amount_matched_cents)}</td><td>{item.status}</td><td>{item.status==="sugerida"?<button disabled={busy} onClick={()=>confirmConciliation(item)}>Confirmar conciliação</button>:"Resolvida"}</td></tr>)}</tbody></table>
    </section>}
  </main>;
}
function AccountTable({accounts,onSelect}:{accounts:Account[];onSelect:(a:Account)=>void}) { return <table data-testid="finance-receivables-table"><thead><tr><th>Protocolo</th><th>Contrato</th><th>Valor</th><th>Status</th></tr></thead><tbody>{accounts.length===0?<tr><td colSpan={4} data-testid="finance-receivables-empty">Nenhum recebível encontrado.</td></tr>:accounts.map(a=><tr key={a.id} onClick={()=>onSelect(a)}><td>{a.protocol}</td><td>{a.contract_id||"Contrato ausente"}</td><td>{money(a.amount_cents)}</td><td>{a.status}</td></tr>)}</tbody></table>; }
function PaymentTable({payments}:{payments:Payment[]}) { return <table data-testid="finance-payments-table"><thead><tr><th>Conta</th><th>Valor</th><th>Tipo</th></tr></thead><tbody>{payments.length===0?<tr><td colSpan={3}>Nenhum pagamento encontrado.</td></tr>:payments.map(p=><tr key={p.id}><td>{p.receivable_id||p.payable_id||"Conta ausente"}</td><td>{money(p.amount_cents)}</td><td>{p.is_estorno?"Estorno":"Baixa"}</td></tr>)}</tbody></table>; }
function StatementTable({statements}:{statements:BankStatement[]}) { return <table data-testid="finance-bank-statements-table"><thead><tr><th>Protocolo</th><th>Origem</th><th>Arquivo</th><th>Movimentos</th><th>Total</th></tr></thead><tbody>{statements.length===0?<tr><td colSpan={5}>Nenhum extrato encontrado.</td></tr>:statements.map(item=><tr key={item.id}><td>{item.protocol}</td><td>{item.source}</td><td>{item.file_name}</td><td>{item.total_transactions}</td><td>{money(item.total_amount_cents)}</td></tr>)}</tbody></table>; }
