"use client";

import { FormEvent, useEffect, useState } from "react";

type Account = { id:string; protocol:string; contract_id:string|null; client_account_id:string|null; competence_date:string; due_date:string; amount_cents:string|number; amount_paid_cents:string|number; status:string; description?:string|null };
type Rule = { id:string; contract_id:string; recurrence_id:string; amount_cents:string|number; start_date:string; is_approved:boolean; is_active:boolean; suspension_enabled:boolean };
type Payment = { id:string; account_type:string; receivable_id:string|null; payable_id:string|null; amount_cents:string|number; is_estorno:boolean; created_at:string };

const money = (value: string|number|undefined) => value == null ? "Dado ausente" : `R$ ${(Number(value)/100).toFixed(2).replace(".",",")}`;
async function api(path:string, init?:RequestInit) { const response=await fetch(path, { ...init, headers:{ "Content-Type":"application/json", ...(init?.headers||{}) } }); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.error || `Erro ${response.status}`); return data; }

export default function FinanceiroWorkspace() {
  const [tab,setTab] = useState<"receivables"|"recurrence"|"payments">("receivables");
  const [accounts,setAccounts] = useState<Account[]>([]); const [rules,setRules] = useState<Rule[]>([]); const [payments,setPayments] = useState<Payment[]>([]);
  const [contractFilter,setContractFilter] = useState(""); const [selected,setSelected] = useState<Account|null>(null); const [busy,setBusy] = useState(false); const [error,setError] = useState(""); const [notice,setNotice] = useState("");
  const [newAccount,setNewAccount] = useState({ client_account_id:"", contract_id:"", competence_date:"", due_date:"", amount_cents:"", description:"" });
  const [newRule,setNewRule] = useState({ contract_id:"", recurrence_id:"", start_date:"", amount_cents:"" }); const [generationClientAccountId,setGenerationClientAccountId] = useState("");
  const [paymentAmount,setPaymentAmount] = useState(""); const [reason,setReason] = useState(""); const [estorno,setEstorno] = useState<Payment|null>(null); const [history,setHistory] = useState<Record<string,unknown>[]>([]);
  const run = async (fn:()=>Promise<void>) => { setBusy(true); setError(""); setNotice(""); try { await fn(); } catch(e) { setError(e instanceof Error?e.message:"Falha inesperada"); } finally { setBusy(false); } };
  const load = () => run(async()=> { const [a,r,p] = await Promise.all([api(`/api/fin/receivables${contractFilter?`?contract_id=${encodeURIComponent(contractFilter)}`:""}`), api("/api/fin/recurrence-rules"), api("/api/fin/payments")]); const nextAccounts:Account[]=a.receivables||[]; setAccounts(nextAccounts); setRules(r.rules||[]); setPayments(p.payments||[]); if(selected){ setSelected(nextAccounts.find(item=>item.id===selected.id)||selected); const h=await api(`/api/fin/payment-history?receivable_id=${selected.id}`); setHistory(h.history||[]); } });
  useEffect(()=>{ load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const createAccount = async (event:FormEvent) => { event.preventDefault(); await run(async()=> { await api("/api/fin/receivables", {method:"POST",body:JSON.stringify({...newAccount, amount_cents:Number(newAccount.amount_cents), is_recurring:false})}); setNotice("Recebível criado"); setNewAccount({client_account_id:"",contract_id:"",competence_date:"",due_date:"",amount_cents:"",description:""}); await load(); }); };
  const createRule = async (event:FormEvent) => { event.preventDefault(); await run(async()=> { await api("/api/fin/recurrence-rules", {method:"POST",body:JSON.stringify({...newRule, amount_cents:Number(newRule.amount_cents), recurrence_type:"mensal"})}); setNotice("Regra criada e aguardando aprovação"); setNewRule({contract_id:"",recurrence_id:"",start_date:"",amount_cents:""}); await load(); }); };
  const approve = (rule:Rule) => run(async()=> { await api("/api/fin/recurrence-rules",{method:"PATCH",body:JSON.stringify({id:rule.id,is_approved:true})}); setNotice("Regra aprovada"); await load(); });
  const generate = (rule:Rule) => run(async()=> { if(!generationClientAccountId) throw new Error("Informe a conta do cliente para gerar a cobrança"); const date=rule.start_date.slice(0,10); await api("/api/fin/generate-recurring",{method:"POST",body:JSON.stringify({recurrence_rule_id:rule.id,competence_date:date,due_date:date,client_account_id:generationClientAccountId,contract_id:rule.contract_id,amount_cents:Number(rule.amount_cents)})}); setNotice("Cobrança gerada"); await load(); });
  const pay = async (event:FormEvent) => { event.preventDefault(); if(!selected) return; await run(async()=> { const data=await api("/api/fin/payments",{method:"POST",body:JSON.stringify({account_type:"receber",receivable_id:selected.id,amount_cents:Number(paymentAmount),reason,is_partial:true})}); setNotice(data.note||"Baixa registrada"); setPaymentAmount(""); setReason(""); await load(); }); };
  const doEstorno = async () => { if(!selected||!estorno) return; await run(async()=> { await api("/api/fin/payments",{method:"POST",body:JSON.stringify({account_type:"receber",receivable_id:selected.id,amount_cents:Number(estorno.amount_cents),reason,is_estorno:true,previous_payment_id:estorno.id})}); setNotice("Estorno registrado"); setEstorno(null); setReason(""); await load(); }); };
  const openAccount = (account:Account) => run(async()=> { setSelected(account); const data=await api(`/api/fin/payment-history?receivable_id=${account.id}`); setHistory(data.history||[]); });
  return <main data-testid="financeiro-workspace" style={{padding:"2rem",maxWidth:1200,margin:"auto"}}>
    <header><h1>Financeiro</h1><p>Contas, recorrência e pagamentos com auditoria transacional.</p></header>
    <nav aria-label="Abas financeiras" style={{display:"flex",gap:8,margin:"1rem 0"}}>{[["receivables","Recebíveis"],["recurrence","Recorrência"],["payments","Pagamentos"]].map(([id,label])=><button key={id} data-testid={`finance-tab-${id}`} onClick={()=>setTab(id as typeof tab)} aria-selected={tab===id}>{label}</button>)}</nav>
    {error&&<p role="alert" data-testid="finance-error">{error}</p>}{notice&&<p role="status" data-testid="finance-notice">{notice}</p>}{busy&&<p data-testid="finance-loading">Carregando...</p>}
    {tab==="receivables"&&<section data-testid="finance-receivables"><h2>Recebíveis</h2><form onSubmit={createAccount}><input required placeholder="ID da conta do cliente" value={newAccount.client_account_id} onChange={e=>setNewAccount({...newAccount,client_account_id:e.target.value})}/><input placeholder="ID do contrato" value={newAccount.contract_id} onChange={e=>setNewAccount({...newAccount,contract_id:e.target.value})}/><input required type="date" aria-label="Competência" value={newAccount.competence_date} onChange={e=>setNewAccount({...newAccount,competence_date:e.target.value})}/><input required type="date" aria-label="Vencimento" value={newAccount.due_date} onChange={e=>setNewAccount({...newAccount,due_date:e.target.value})}/><input required type="number" min="1" placeholder="Valor em centavos" value={newAccount.amount_cents} onChange={e=>setNewAccount({...newAccount,amount_cents:e.target.value})}/><button disabled={busy}>Criar recebível</button></form><hr/><form onSubmit={e=>{e.preventDefault();load()}}><input data-testid="finance-contract-filter" placeholder="Filtrar por contrato" value={contractFilter} onChange={e=>setContractFilter(e.target.value)}/><button>Filtrar</button></form><AccountTable accounts={accounts} onSelect={openAccount}/></section>}
    {tab==="recurrence"&&<section data-testid="finance-recurrence"><h2>Recorrência</h2><label>Conta do cliente para geração <input required data-testid="finance-generation-client-account" placeholder="ID da conta do cliente para geração" value={generationClientAccountId} onChange={e=>setGenerationClientAccountId(e.target.value)}/></label><form onSubmit={createRule}><input required placeholder="ID do contrato" value={newRule.contract_id} onChange={e=>setNewRule({...newRule,contract_id:e.target.value})}/><input required placeholder="Identificador da regra" value={newRule.recurrence_id} onChange={e=>setNewRule({...newRule,recurrence_id:e.target.value})}/><input required type="date" value={newRule.start_date} onChange={e=>setNewRule({...newRule,start_date:e.target.value})}/><input required type="number" min="1" placeholder="Valor em centavos" value={newRule.amount_cents} onChange={e=>setNewRule({...newRule,amount_cents:e.target.value})}/><button>Criar regra</button></form><ul>{rules.length===0?<li data-testid="finance-recurrence-empty">Nenhuma regra encontrada.</li>:rules.map(rule=><li data-testid={`finance-rule-${rule.id}`} key={rule.id}>Contrato {rule.contract_id} · {money(rule.amount_cents)} · {rule.is_approved?"aprovada":"pendente"} <button disabled={rule.is_approved} onClick={()=>approve(rule)}>Aprovar</button> <button disabled={!rule.is_approved||!rule.is_active} onClick={()=>generate(rule)}>Gerar cobrança</button></li>)}</ul></section>}
    {tab==="payments"&&<section data-testid="finance-payments"><h2>Pagamentos</h2><PaymentTable payments={payments}/>{selected&&<><h3>Conta {selected.protocol}</h3><p>Saldo pago: {money(selected.amount_paid_cents)} de {money(selected.amount_cents)} · status {selected.status}</p><form onSubmit={pay}><input required type="number" min="1" placeholder="Baixa em centavos" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)}/><input required minLength={10} maxLength={1000} placeholder="Motivo (10 a 1000 caracteres)" value={reason} onChange={e=>setReason(e.target.value)}/><button>Dar baixa</button></form><ul>{history.map((item,i)=><li key={i}>{String(item.reason||"Histórico sem motivo")} · {String(item.next_status||"")}</li>)}</ul>{payments.filter(p=>p.receivable_id===selected.id&&!p.is_estorno).map(p=><button key={p.id} onClick={()=>setEstorno(p)}>Estornar pagamento de {money(p.amount_cents)}</button>)}{estorno&&<button onClick={doEstorno}>Confirmar estorno</button>}</>}</section>}
  </main>;
}
function AccountTable({accounts,onSelect}:{accounts:Account[];onSelect:(a:Account)=>void}) { return <table data-testid="finance-receivables-table"><thead><tr><th>Protocolo</th><th>Contrato</th><th>Valor</th><th>Status</th></tr></thead><tbody>{accounts.length===0?<tr><td colSpan={4} data-testid="finance-receivables-empty">Nenhum recebível encontrado.</td></tr>:accounts.map(a=><tr key={a.id} onClick={()=>onSelect(a)}><td>{a.protocol}</td><td>{a.contract_id||"Contrato ausente"}</td><td>{money(a.amount_cents)}</td><td>{a.status}</td></tr>)}</tbody></table>; }
function PaymentTable({payments}:{payments:Payment[]}) { return <table data-testid="finance-payments-table"><thead><tr><th>Conta</th><th>Valor</th><th>Tipo</th></tr></thead><tbody>{payments.length===0?<tr><td colSpan={3}>Nenhum pagamento encontrado.</td></tr>:payments.map(p=><tr key={p.id}><td>{p.receivable_id||p.payable_id||"Conta ausente"}</td><td>{money(p.amount_cents)}</td><td>{p.is_estorno?"Estorno":"Baixa"}</td></tr>)}</tbody></table>; }
