"use client";
import { FormEvent, useEffect, useState } from "react";

type Result = { id:string; protocol:string; competence_date:string; status:string; is_complete:boolean; margin_cents:number|null; incomplete_reason:string|null };
const api = async (path:string, options:RequestInit={}) => { const r=await fetch(path,{...options,headers:{"content-type":"application/json",...(options.headers||{})}}); const b=await r.json().catch(()=>({})); if(!r.ok) throw new Error(b.error||"Falha no resultado gerencial"); return b; };
export default function ManagementResultsWorkspace(){
 const [rows,setRows]=useState<Result[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
 const [form,setForm]=useState({contract_id:"",client_account_id:"",competence_date:"",received:"",costs:"",reason:""});
 const load=async()=>{const b=await api("/api/fin/management-results");setRows(b.results||[])}; useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");setNotice("");try{await api("/api/fin/management-results",{method:"POST",body:JSON.stringify({contract_id:form.contract_id||null,client_account_id:form.client_account_id||null,competence_date:form.competence_date,revenue_received_cents:Number(form.received),costs_cents:Number(form.costs),is_complete:false,incomplete_reason:form.reason})});setNotice("Resultado gerencial incompleto registrado");setForm({...form,competence_date:"",received:"",costs:"",reason:""});await load()}catch(e){setError(e instanceof Error?e.message:"Falha inesperada")}finally{setBusy(false)}};
 return <section data-testid="fin09-results" style={{padding:"1rem"}}><h2>Resultado gerencial</h2><p>Receita recebida, custos, caixa e margem por contrato; dados ausentes permanecem incompletos.</p>{error&&<p role="alert" data-testid="fin09-error">{error}</p>}{notice&&<p role="status" data-testid="fin09-notice">{notice}</p>}<form onSubmit={submit}><input data-testid="fin09-contract" placeholder="ID do contrato" value={form.contract_id} onChange={e=>setForm({...form,contract_id:e.target.value})}/><input data-testid="fin09-account" placeholder="ID da conta do cliente" value={form.client_account_id} onChange={e=>setForm({...form,client_account_id:e.target.value})}/><input required data-testid="fin09-competence" type="date" value={form.competence_date} onChange={e=>setForm({...form,competence_date:e.target.value})}/><input required data-testid="fin09-received" type="number" min="0" placeholder="Recebido em centavos" value={form.received} onChange={e=>setForm({...form,received:e.target.value})}/><input required data-testid="fin09-costs" type="number" min="0" placeholder="Custos em centavos" value={form.costs} onChange={e=>setForm({...form,costs:e.target.value})}/><input required minLength={10} data-testid="fin09-reason" placeholder="Motivo dos dados incompletos" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><button data-testid="fin09-create" disabled={busy}>Registrar resultado</button></form><ul data-testid="fin09-list">{rows.map(r=><li key={r.id}>{r.protocol} · {r.competence_date} · {r.status} · {r.incomplete_reason||"completo"}</li>)}</ul></section>;
}
