export type AnalyticsErrorDescriptor = { kind: string; title: string; detail: string; status: number; canRetry: boolean; code: string | null };
export function describeAnalyticsError(code: string | null | undefined, status?: number): AnalyticsErrorDescriptor;
export function analyticsErrorMessage(code: string | null | undefined, status?: number): string;
export function analyticsErrorVariant(descriptor: AnalyticsErrorDescriptor): 'denied' | 'error';
export function analyticsErrorFootnote(descriptor: AnalyticsErrorDescriptor): string;
export function enumLabel(group: string, value: unknown): string;
export function enumTone(group: string, value: unknown): string;
export function experimentStatusLabel(value: unknown): string;
export function experimentStatusTone(value: unknown): string;
export function variantLabel(value: unknown): string;
export function variantTone(value: unknown): string;
export function sourceTypeLabel(value: unknown): string;
export function sourceTypeTone(value: unknown): string;
export function honestDate(value: unknown): string;
export function honestDateTime(value: unknown): string;
export function count(value: unknown): string;
export function decimal(value: unknown): string;
export function honestPercent(part: unknown, total: unknown): string;
export function honestText(value: unknown): string;
export const ABSENT: string;
