export type ContinuityErrorKind='denied'|'invalid'|'conflict'|'not_found'|'unavailable'|'error';
export type ContinuityErrorDescriptor={code:string|null;status:number;kind:ContinuityErrorKind;title:string;detail:string;canRetry:boolean};
export const CONTINUITY_ERROR_CODES:readonly string[];
export const CONTINUITY_TRANSITIONS:Readonly<Record<string,readonly string[]>>;
export const CONTINUITY_STATUSES:readonly string[];
export const CONTINUITY_GRANTS:readonly string[];
export const CLIENT_PUBLISHABLE:readonly string[];
export const READ_SCOPES:readonly string[];
export function describeContinuityError(code?:string|null,status?:number):ContinuityErrorDescriptor;
export function continuityErrorFootnote(error?:ContinuityErrorDescriptor):string;
export function continuityServerMessage(payload:unknown):string;
export const continuityStatusLabels:Readonly<Record<string,string>>;
export const continuityStatusTones:Readonly<Record<string,string>>;
export const continuityTransitionLabels:Readonly<Record<string,string>>;
export function honestDate(value:unknown,absent?:string):string;
export function honestTestDate(value:unknown):string;
export function honestNextTest(value:unknown):string;
export function honestCount(value:unknown,label?:string):string;
export const ABSENT:string;
export const GRANT_SCOPES:readonly string[];
