export type ContractTone = 'neutral' | 'info' | 'success' | 'warning' | 'danger';
export type ContractErrorKind = 'auth' | 'denied' | 'retry' | 'invalid' | 'conflict' | 'network';
export type ContractErrorDescriptor = {
  code: string | null;
  kind: ContractErrorKind;
  title: string;
  detail: string;
  status: number;
  canRetry: boolean;
};

export function describeContractError(code: string | null | undefined, status?: number): ContractErrorDescriptor;
export function contractErrorVariant(descriptor: ContractErrorDescriptor | null | undefined): 'denied' | 'error';
export function contractErrorFootnote(descriptor: ContractErrorDescriptor | null | undefined): string;
export function contractErrorMessage(code: string | null | undefined, status?: number): string;

export function contractStatusLabel(value: string | null | undefined): string;
export function contractStatusTone(value: string | null | undefined): ContractTone;
export function contractOriginLabel(value: string | null | undefined): string;
export function implantationStatusLabel(value: string | null | undefined): string;
export function implantationStatusTone(value: string | null | undefined): ContractTone;
export function implantationStepLabel(value: string | null | undefined): string;
export function stepStatusLabel(value: string | null | undefined): string;
export function stepStatusTone(value: string | null | undefined): ContractTone;
export function blockTypeLabel(value: string | null | undefined): string;
export function exceptionStatusLabel(value: string | null | undefined): string;
export function exceptionStatusTone(value: string | null | undefined): ContractTone;
export function amendmentTypeLabel(value: string | null | undefined): string;
export function amendmentBaseLabel(value: string | null | undefined): string;
export function amendmentStatusLabel(value: string | null | undefined): string;
export function amendmentStatusTone(value: string | null | undefined): ContractTone;
export function alertTypeLabel(value: string | null | undefined): string;
export function alertChannelLabel(value: string | null | undefined): string;
export function alertStatusLabel(value: string | null | undefined): string;
export function alertStatusTone(value: string | null | undefined): ContractTone;
export function obligationCategoryLabel(value: string | null | undefined): string;
export function obligationPeriodicityLabel(value: string | null | undefined): string;
export function obligationStatusLabel(value: string | null | undefined): string;
export function obligationStatusTone(value: string | null | undefined): ContractTone;
export function obligationPartyLabel(value: string | null | undefined): string;
export function closureTypeLabel(value: string | null | undefined): string;
export function closureStatusLabel(value: string | null | undefined): string;
export function closureStatusTone(value: string | null | undefined): ContractTone;
export function closureStepLabel(value: string | null | undefined): string;
export function closureStepStatusLabel(value: string | null | undefined): string;
export function closureStepStatusTone(value: string | null | undefined): ContractTone;
export function dossierStatusLabel(value: string | null | undefined): string;
export function dossierStatusTone(value: string | null | undefined): ContractTone;
export function measurementStatusLabel(value: string | null | undefined): string;
export function measurementStatusTone(value: string | null | undefined): ContractTone;
export function evidenceTypeLabel(value: string | null | undefined): string;
export function diaryCategoryLabel(value: string | null | undefined): string;
export function diaryVisibilityLabel(value: string | null | undefined): string;
export function postShiftLabel(value: string | null | undefined): string;
export function slaServiceLabel(value: string | null | undefined): string;
export function activeLabel(value: unknown): string;
export function activeTone(value: unknown): ContractTone;
export function shortDate(value: string | null | undefined, ausente?: string): string;
export function brl(value: string | number | null | undefined): string;
