export type FinanceTone = 'neutral' | 'info' | 'success' | 'warning' | 'danger';
export type FinanceErrorKind = 'auth' | 'denied' | 'retry' | 'invalid' | 'conflict' | 'network';
export type FinanceErrorDescriptor = {
  code: string | null;
  kind: FinanceErrorKind;
  title: string;
  detail: string;
  status: number;
  canRetry: boolean;
};

export function describeFinanceError(code: string | null | undefined, status?: number): FinanceErrorDescriptor;
export function financeErrorVariant(descriptor: FinanceErrorDescriptor | null | undefined): 'denied' | 'error';
export function financeErrorFootnote(descriptor: FinanceErrorDescriptor | null | undefined): string;
export function financeErrorMessage(code: string | null | undefined, status?: number): string;

export function accountStatusLabel(value: string | null | undefined): string;
export function accountStatusTone(value: string | null | undefined): FinanceTone;
export function accountTypeLabel(value: string | null | undefined): string;
export function approvalStatusLabel(value: string | null | undefined): string;
export function approvalStatusTone(value: string | null | undefined): FinanceTone;
export function recurrenceTypeLabel(value: string | null | undefined): string;
export function categoryLabel(value: string | null | undefined): string;
export function paymentMethodLabel(value: string | null | undefined): string;
export function conciliationStatusLabel(value: string | null | undefined): string;
export function conciliationStatusTone(value: string | null | undefined): FinanceTone;
export function conciliationSourceLabel(value: string | null | undefined): string;
export function collectionStatusLabel(value: string | null | undefined): string;
export function collectionStatusTone(value: string | null | undefined): FinanceTone;
export function reminderTypeLabel(value: string | null | undefined): string;
export function cashflowTypeLabel(value: string | null | undefined): string;
export function cashflowTypeTone(value: string | null | undefined): FinanceTone;
export function agingBucketLabel(value: string | null | undefined): string;
export function agingBucketTone(value: string | null | undefined): FinanceTone;
export function costSourceLabel(value: string | null | undefined): string;
export function resultStatusLabel(value: string | null | undefined): string;
export function resultStatusTone(value: string | null | undefined): FinanceTone;
export function expenseTypeLabel(value: string | null | undefined): string;
export function expenseStatusLabel(value: string | null | undefined): string;
export function expenseStatusTone(value: string | null | undefined): FinanceTone;
export function fiscalDocTypeLabel(value: string | null | undefined): string;
export function fiscalDocStatusLabel(value: string | null | undefined): string;
export function fiscalDocStatusTone(value: string | null | undefined): FinanceTone;
export function fiscalProviderStatusLabel(value: string | null | undefined): string;
export function fiscalProviderStatusTone(value: string | null | undefined): FinanceTone;
export function fiscalObligationStatusLabel(value: string | null | undefined): string;
export function fiscalObligationStatusTone(value: string | null | undefined): FinanceTone;
export function jurisdictionLabel(value: string | null | undefined): string;
export function gatewayTypeLabel(value: string | null | undefined): string;
export function gatewayStatusLabel(value: string | null | undefined): string;
export function gatewayStatusTone(value: string | null | undefined): FinanceTone;
export function webhookStatusLabel(value: string | null | undefined): string;
export function webhookStatusTone(value: string | null | undefined): FinanceTone;
export function chargeStatusLabel(value: string | null | undefined): string;
export function chargeStatusTone(value: string | null | undefined): FinanceTone;
export function budgetStatusLabel(value: string | null | undefined): string;
export function budgetStatusTone(value: string | null | undefined): FinanceTone;
export function scenarioTypeLabel(value: string | null | undefined): string;
export function exportStatusLabel(value: string | null | undefined): string;
export function exportStatusTone(value: string | null | undefined): FinanceTone;
export function closureStatusLabel(value: string | null | undefined): string;
export function closureStatusTone(value: string | null | undefined): FinanceTone;
export function commissionStatusLabel(value: string | null | undefined): string;
export function commissionStatusTone(value: string | null | undefined): FinanceTone;
export function activeLabel(value: boolean | null | undefined): string;
export function activeTone(value: boolean | null | undefined): FinanceTone;
export function money(cents: string | number | null | undefined): string;
