"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import styles from '../../../components/ui/UiWorkspace.module.css';
// Fronteira externa: Não existe ator externo “terceiro” autenticado; o servidor autoriza.
import {thirdPartyRequest} from '../../../lib/third-party-request';
import {label,ABSENCE,EXTERNAL_BOUNDARY} from '../../../lib/third-party-vocabulary.mjs';

type State<T>={loading:boolean;data:T|null;error:any};
type Party={id:string;name:string;document?:string|null;category?:string|null;status:string;responsible_name?:string|null;notes?:string|null;access_situation?:any};
type List={third_parties:Party[];note?:string;source?:string[];base_date?:string;external_actor_boundary?:any};
const fresh=()=>({loading:false,data:null,error:null});
function key(prefix:string){return `${prefix}-${crypto.randomUUID()}`}
function ErrorState({error,retry,keyValue}:{error:any;retry:()=>void;keyValue?:string}){return <div className={styles.notice+" "+styles.noticeError} role="alert"><strong>{error?.kind==='denied'?'NEGADO':'Falha de comunicação'}</strong><p>{error?.title||'Falha'}</p><p>{error?.detail||'Não foi possível carregar.'} Isto não significa ausência de dados.</p><small>Código técnico: {error?.code||'sem código'}; HTTP {error?.status??'—'}</small>{keyValue&&<p>Chave de idempotência preservada para repetição segura: <code>{keyValue}</code></p>}<div className={styles.actions}><button onClick={retry}>Tentar novamente</button></div></div>}
function Tabs({active,setActive}:{active:number;setActive:(n:number)=>void}){const names=['Terceiros','Dossiê','Autorização','Documentos e regras','Avaliações e eventos'];const refs=useRef<(HTMLButtonElement|null)[]>([]);return <><div className={styles.tabs} role="tablist" aria-label="Áreas de terceiros">{names.map((n,i)=><button key={n} ref={e=>{refs.current[i]=e}} className={i===active?styles.tabActive:styles.tab} role="tab" aria-selected={i===active} aria-controls={`terceiros-panel-${i}`} tabIndex={i===active?0:-1} onClick={()=>setActive(i)} onKeyDown={e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%names.length;if(e.key==='ArrowLeft')n=(i+names.length-1)%names.length;if(e.key==='Home')n=0;if(e.key==='End')n=names.length-1;if(n!==i){e.preventDefault();setActive(n);refs.current[n]?.focus()}}}>{n}</button>)}</div></>}
export default function TerceirosWorkspace(){
 const [tab,setTab]=useState(0);const [list,setList]=useState<State<List>>({...fresh(),loading:true});const [selected,setSelected]=useState<Party|null>(null);const [detail,setDetail]=useState<State<any>>(fresh());const [decision,setDecision]=useState<State<any>>(fresh());const [form,setForm]=useState({name:'',document:'',category:'',responsible_name:'',notes:''});const [opKey,setOpKey]=useState(()=>key('ext02-tp'));const [opError,setOpError]=useState<any>(null);const loadList=useCallback(async()=>{setList({...fresh(),loading:true});const r=await thirdPartyRequest<List>('/api/ext/third-party/parties');if(r.ok)setList({loading:false,data:r.data,error:null});else setList({loading:false,data:null,error:r.error})},[]);
 const loadDetail=useCallback(async(id:string)=>{setDetail({...fresh(),loading:true});const r=await thirdPartyRequest(`/api/ext/third-party/parties/${id}`);if(r.ok)setDetail({loading:false,data:r.data,error:null});else setDetail({loading:false,data:null,error:r.error})},[]);
 const check=useCallback(async()=>{if(!selected)return;setDecision({...fresh(),loading:true});const r=await thirdPartyRequest(`/api/ext/third-party/parties/${selected.id}/authorization?scope_kind=contrato&scope_id=${encodeURIComponent('')}`);if(r.ok)setDecision({loading:false,data:r.data,error:null});else setDecision({loading:false,data:null,error:r.error})},[selected]);
 useEffect(()=>{loadList()},[loadList]);
 async function create(){setOpError(null);const r=await thirdPartyRequest('/api/ext/third-party/parties',{method:'POST',headers:{'Idempotency-Key':opKey},body:JSON.stringify(form)});if(r.ok){setForm({name:'',document:'',category:'',responsible_name:'',notes:''});setOpKey(key('ext02-tp'));loadList()}else setOpError(r.error)}
 const choose=(p:Party)=>{setSelected(p);setTab(1);loadDetail(p.id)};
 return <main className={styles.workspace}><p className={styles.kicker}>EXT-02 · TERCEIROS</p><h1>Terceiros</h1><p className={styles.lede}>{EXTERNAL_BOUNDARY}</p><Tabs active={tab} setActive={setTab}/>
 <section id={`terceiros-panel-${tab}`} role="tabpanel" className={styles.tabPanel} aria-label="Conteúdo da aba">
 {tab===0&&<><div className={styles.layout}><section className={styles.panel}><h2 className={styles.panelTitle}>Cadastrar terceiro</h2><div className={styles.fieldRow}>{(['name','document','category','responsible_name'] as const).map(k=><div className={styles.field} key={k}><label htmlFor={`tp-${k}`}>{k==='name'?'Nome':k==='document'?'Documento':k==='category'?'Categoria':'Responsável'}</label><input id={`tp-${k}`} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}</div><div className={styles.field}><label htmlFor="tp-notes">Observações escritas por quem opera</label><textarea id="tp-notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><div className={styles.actions}><button className={styles.primary} onClick={create}>Cadastrar</button></div>{opError&&<ErrorState error={opError} retry={create} keyValue={opKey}/>}</section></div>{list.loading&&<p role="status">Carregando registros canônicos…</p>}{list.error&&<ErrorState error={list.error} retry={loadList}/>} {list.data&&<section className={styles.panel}><h2 className={styles.panelTitle}>Registros canônicos</h2>{list.data.third_parties.length===0?<p>{ABSENCE.list}. A ausência é real no banco consultado.</p>:<div className={styles.tableWrap}><table className={styles.table}><caption>Lista de terceiros; base {list.data.base_date||ABSENCE.unknown}</caption><thead><tr><th>Nome</th><th>Situação</th><th>Acesso</th><th>Ação</th></tr></thead><tbody>{list.data.third_parties.map(p=><tr key={p.id}><td>{p.name}</td><td>{label('status',p.status)}</td><td>{label('access',p.access_situation?.status)}</td><td><button onClick={()=>choose(p)}>Ver dossiê</button></td></tr>)}</tbody></table></div>}</section>}</>}
 {tab===1&&<section className={styles.panel}><h2 className={styles.panelTitle}>Dossiê canônico</h2>{!selected?<p>Selecione um terceiro na primeira aba.</p>:detail.loading?<p role="status">Carregando dossiê…</p>:detail.error?<ErrorState error={detail.error} retry={()=>loadDetail(selected.id)}/>:detail.data?<div className={styles.cards}><p><strong>{detail.data.third_party?.name||selected.name}</strong> · {label('status',detail.data.third_party?.status)}</p><p>{detail.data.access_situation?.note||ABSENCE.unknown}</p><p>Documentos: {detail.data.documents?.length??ABSENCE.unknown}. Avaliações: {detail.data.evaluations?.length??ABSENCE.unknown}. Eventos: {detail.data.events?.length??ABSENCE.unknown}.</p><p className={styles.footnote}>{EXTERNAL_BOUNDARY}</p></div>:null}</section>}
 {tab===2&&<section className={styles.panel}><h2 className={styles.panelTitle}>Decisão de autorização</h2>{!selected?<p>Selecione um terceiro.</p>:decision.loading?<p role="status">Consultando o servidor…</p>:decision.error?<ErrorState error={decision.error} retry={check}/>:decision.data?<p className={styles.notice}>{decision.data.authorized?'Autorizado':'Negado'} — {decision.data.reason||ABSENCE.unknown}</p>:<button onClick={check}>Consultar autorização</button>}</section>}
 {tab===3&&<section className={styles.panel}><h2 className={styles.panelTitle}>Documentos e regras</h2>{detail.data?<><p>Documentos registrados: {detail.data.documents?.length??ABSENCE.unknown}.</p><p>Regra de antecedência: {detail.data.document_rule?`${detail.data.document_rule.alert_before_days} dias`:'Sem regra de antecedência declarada'}.</p></>:<p>O dossiê é carregado sem transformar falha em ausência.</p>}</section>}
 {tab===4&&<section className={styles.panel}><h2 className={styles.panelTitle}>Avaliações e eventos</h2>{detail.data?<><p>Avaliações registradas: {detail.data.evaluations?.length??ABSENCE.unknown}.</p><ul>{(detail.data.events||[]).map((e:any)=><li key={e.id}>{e.summary} — {e.created_at||ABSENCE.unknown}</li>)}</ul></>:<p>Selecione um terceiro para consultar a trilha canônica.</p>}</section>}
 </section></main>}
