"use client";
import { useCallback, useEffect, useRef, useState, type KeyboardEvent, type ReactNode } from 'react';
import UiState from '../../../components/ui/UiState';
import styles from '../../../components/ui/UiWorkspace.module.css';
import { thirdPartyRequest, type ThirdPartyResult } from '../../../lib/third-party-request';
import { ABSENT, EXTERNAL_BOUNDARY, honestDate, honestText, labelThirdParty } from '../../../lib/third-party-vocabulary.mjs';

type Party={id:string;name:string;status:string;document?:string|null;category?:string|null;responsible_name?:string|null;access_situation?:{status:string}};
type Listing={third_parties:Party[];third_parties_registered:boolean;note:string;base_date:string;external_actor_boundary?:{note:string}};
type Dossier={third_party:Party;access_grants:any[];documents:any[];document_rule:any|null;document_rule_absence?:string;evaluations:any[];events:any[];base_date:string};
type ReadState<T>={phase:'idle'|'loading'|'ready'|'error'|'denied';data:T|null;error:any|null};
const initial=<T,>():ReadState<T>=>({phase:'idle',data:null,error:null});
const tabs=[['cadastro','Cadastro'],['dossie','Dossiê'],['acessos','Acessos e janelas'],['documentos','Documentos'],['regras','Regras de documento'],['avaliacoes','Avaliações'],['autorizacao','Decisão de autorização'],['eventos','Eventos']] as const;
const key=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;

export default function TerceirosWorkspace(){
 const [active,setActive]=useState('cadastro'); const refs=useRef<Array<HTMLButtonElement|null>>([]);
 const [list,setList]=useState<ReadState<Listing>>({...initial(),phase:'loading'}); const [selected,setSelected]=useState('');
 const [dossier,setDossier]=useState<ReadState<Dossier>>(initial());
 const [reads,setReads]=useState<Record<string,ReadState<any>>>({acessos:initial(),documentos:initial(),regras:initial(),avaliacoes:initial(),eventos:initial(),autorizacao:initial()});
 const [form,setForm]=useState<Record<string,string>>({name:'',document:'',category:'',responsible_name:'',notes:'',status:'ativo',reason:'',contract_id:'',justification:'',scope_kind:'contrato',scope_id:'',access_start:'',access_end:'',grant_id:'',document_type:'',document_number:'',expiry_date:'',file_name:'',document_id:'',alert_before_days:'30',score:'',evaluated_on:''});
 const [keys,setKeys]=useState<Record<string,string>>(()=>({tp:key('ext02-tp'),sta:key('ext02-sta'),ctr:key('ext02-ctr'),grt:key('ext02-grt'),rev:key('ext02-rev'),doc:key('ext02-doc'),dcx:key('ext02-dcx'),rul:key('ext02-rul'),avl:key('ext02-avl')}));
 const [mutation,setMutation]=useState<{message:string;error:any;op:string}|null>(null); const [busy,setBusy]=useState(false);
 const update=(name:string,value:string)=>setForm(v=>({...v,[name]:value}));
 const loadList=useCallback(async()=>{setList({...initial(),phase:'loading'});const r=await thirdPartyRequest<Listing>('/api/ext/third-party/parties');setList(r.ok?{phase:'ready',data:r.data,error:null}:{phase:r.error.kind==='denied'?'denied':'error',data:null,error:r.error});},[]);
 useEffect(()=>{loadList();},[loadList]);
 const get=useCallback(async(name:string,url:string)=>{setReads(v=>({...v,[name]:{...initial(),phase:'loading'}}));const r=await thirdPartyRequest<any>(url);setReads(v=>({...v,[name]:r.ok?{phase:'ready',data:r.data,error:null}:{phase:r.error.kind==='denied'?'denied':'error',data:null,error:r.error}}));},[]);
 const loadDossier=useCallback(async(id:string)=>{setDossier({...initial(),phase:'loading'});const r=await thirdPartyRequest<Dossier>(`/api/ext/third-party/parties/${id}`);setDossier(r.ok?{phase:'ready',data:r.data,error:null}:{phase:r.error.kind==='denied'?'denied':'error',data:null,error:r.error});if(r.ok){setReads(v=>({...v,eventos:{phase:'ready',data:{events:r.data.events},error:null}}));}await Promise.all([get('acessos',`/api/ext/third-party/parties/${id}/access-grants`),get('documentos',`/api/ext/third-party/parties/${id}/documents`),get('regras',`/api/ext/third-party/parties/${id}/document-rules`),get('avaliacoes',`/api/ext/third-party/parties/${id}/evaluations`)]);},[get]);
 const choose=(id:string)=>{setSelected(id);setActive('dossie');void loadDossier(id)};
 const mutate=async(op:string,url:string,method:string,body:any,prefix:string)=>{setBusy(true);setMutation(null);const r:ThirdPartyResult<any>=await thirdPartyRequest(url,{method,headers:{'Idempotency-Key':keys[prefix]},body:JSON.stringify(body)});setBusy(false);if(!r.ok){setMutation({message:'Operação não confirmada',error:r.error,op});return;}setMutation({message:'Operação confirmada pelo servidor.',error:null,op});setKeys(v=>({...v,[prefix]:key(`ext02-${prefix}`)}));await loadList();if(selected)await loadDossier(selected);};
 const check=async()=>{if(!selected)return;await get('autorizacao',`/api/ext/third-party/parties/${selected}/authorization?scope_kind=${encodeURIComponent(form.scope_kind)}&scope_id=${encodeURIComponent(form.scope_id)}`)};
 const keyboard=(event:KeyboardEvent<HTMLButtonElement>,index:number)=>{let next=index;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();setActive(tabs[next][0]);refs.current[next]?.focus();};
 const state=(s:ReadState<any>,empty:string,content:(data:any)=>ReactNode)=>{if(s.phase==='loading'||s.phase==='idle')return <UiState variant="loading" title="Consultando o servidor canônico"/>;if(s.phase==='denied')return <UiState variant="denied" title="NEGADO" detail={s.error.detail}><p className={styles.footnote}>Código técnico: {s.error.code}</p></UiState>;if(s.phase==='error')return <UiState variant="error" title={s.error.title} detail={s.error.detail}><p className={styles.footnote}>Código técnico: {s.error.code??ABSENT}</p></UiState>;return content(s.data)??<UiState variant="empty" title={empty}/>;};
 const Field=({name,label,type='text'}:{name:string;label:string;type?:string})=><div className={styles.field}><label htmlFor={`third-${name}`}>{label}</label><input id={`third-${name}`} type={type} value={form[name]||''} onChange={e=>update(name,e.target.value)}/></div>;
 const reasonFields=<><Field name="reason" label="Motivo preenchido por quem opera"/><Field name="justification" label="Justificativa preenchida por quem opera"/></>;
 return <main className={styles.workspace}><p className={styles.kicker}>UX-07 · EXT-02</p><h1>Terceiros, acessos e documentos</h1><p className={styles.lede}>Cadastro interno, vínculo e concessão granular por contrato ou ordem de serviço. Ausência nunca é transformada em zero.</p><aside className={`${styles.notice} ${styles.noticeWarning}`}><strong>Fronteira externa declarada.</strong> {EXTERNAL_BOUNDARY}</aside>
 <div className={styles.tabs} role="tablist" aria-label="Áreas da jornada de terceiros">{tabs.map(([id,label],i)=><button key={id} ref={el=>{refs.current[i]=el}} id={`tab-${id}`} role="tab" aria-selected={active===id} aria-controls={`panel-${id}`} tabIndex={active===id?0:-1} className={active===id?styles.tabActive:styles.tab} onKeyDown={e=>keyboard(e,i)} onClick={()=>setActive(id)}>{label}</button>)}</div>
 {tabs.map(([id])=><section key={id} id={`panel-${id}`} role="tabpanel" aria-labelledby={`tab-${id}`} hidden={active!==id} className={styles.tabPanel}>{active===id&&<>
 {id==='cadastro'&&<div className={styles.layout}><section className={styles.panel}><h2 className={styles.panelTitle}>Lista de terceiros</h2>{state(list,'Nenhum terceiro registrado',data=>data.third_parties.length?<div className={styles.tableWrap} data-testid="third-party-table"><table className={styles.table}><caption>{data.note}</caption><thead><tr><th>Nome</th><th>Situação</th><th>Acesso</th><th>Ação</th></tr></thead><tbody>{data.third_parties.map((p:Party)=><tr key={p.id}><td>{p.name}</td><td>{labelThirdParty('status',p.status)}</td><td>{labelThirdParty('situation',p.access_situation?.status)}</td><td><button type="button" onClick={()=>choose(p.id)}>Ver dossiê</button></td></tr>)}</tbody></table></div>:<UiState variant="empty" title="Nenhum terceiro registrado" detail={data.note}/>)}</section><form className={styles.panel} onSubmit={e=>{e.preventDefault();void mutate('cadastro','/api/ext/third-party/parties','POST',{name:form.name,document:form.document||undefined,category:form.category||undefined,responsible_name:form.responsible_name||undefined,notes:form.notes||undefined},'tp')}}><h2 className={styles.panelTitle}>Cadastrar terceiro</h2><div className={styles.fieldRow}><Field name="name" label="Nome do terceiro"/><Field name="document" label="Identificação documental (opcional)"/><Field name="category" label="Categoria (opcional)"/><Field name="responsible_name" label="Responsável (opcional)"/><Field name="notes" label="Observações (opcional)"/></div><div className={styles.actions}><button className={styles.primary} disabled={busy}>Cadastrar</button></div></form></div>}
 {id==='dossie'&&state(dossier,'Selecione um terceiro',d=>d?<div className={styles.layout}><section className={styles.panel}><h2>{d.third_party.name}</h2><dl className={styles.facts}><div><dt>Situação</dt><dd>{labelThirdParty('status',d.third_party.status)}</dd></div><div><dt>Documento</dt><dd>{honestText(d.third_party.document)}</dd></div><div><dt>Responsável</dt><dd>{honestText(d.third_party.responsible_name)}</dd></div><div><dt>Data-base</dt><dd>{honestDate(d.base_date)}</dd></div></dl></section><form className={styles.panel} onSubmit={e=>{e.preventDefault();void mutate('vínculo',`/api/ext/third-party/parties/${selected}/contract`,'POST',{contract_id:form.contract_id,justification:form.justification},'ctr')}}><h2>Vincular contrato canônico</h2><div className={styles.fieldRow}><Field name="contract_id" label="UUID do contrato"/><Field name="justification" label="Justificativa preenchida por quem opera"/></div><div className={styles.actions}><button>Vincular contrato</button></div></form><form className={styles.panel} onSubmit={e=>{e.preventDefault();void mutate('situação' ,`/api/ext/third-party/parties/${selected}`,'PATCH',{status:form.status,reason:form.reason},'sta')}}><h2>Atualizar situação</h2><div className={styles.fieldRow}><div className={styles.field}><label htmlFor="third-status">Nova situação</label><select id="third-status" value={form.status} onChange={e=>update('status',e.target.value)}>{['ativo','inativo','suspenso','encerrado'].map(x=><option key={x} value={x}>{labelThirdParty('status',x)}</option>)}</select></div><Field name="reason" label="Motivo preenchido por quem opera"/></div><div className={styles.actions}><button>Atualizar</button></div></form></div>:<UiState variant="empty" title="Selecione um terceiro na lista"/>)}
 {id==='acessos'&&<>{state(reads.acessos,'Nenhuma janela registrada',d=>(d?.access_grants||[]).length?<ul className={styles.cards}>{d.access_grants.map((g:any)=><li className={styles.card} key={g.id}><strong>{labelThirdParty('scope',g.scope_kind)}</strong> — {labelThirdParty('window',g.window?.status)}<br/><small>{honestDate(g.access_start)} a {honestDate(g.access_end)}</small></li>)}</ul>:<UiState variant="empty" title="Nenhuma janela registrada"/>)}<form className={styles.panel} onSubmit={e=>{e.preventDefault();void mutate('concessão',`/api/ext/third-party/parties/${selected}/access-grants`,'POST',{scope_kind:form.scope_kind,scope_id:form.scope_id,access_start:form.access_start,access_end:form.access_end,justification:form.justification},'grt')}}><h2>Conceder acesso granular</h2><div className={styles.fieldRow}><div className={styles.field}><label htmlFor="third-scope-kind">Tipo do escopo</label><select id="third-scope-kind" value={form.scope_kind} onChange={e=>update('scope_kind',e.target.value)}><option value="contrato">Contrato</option><option value="ordem_servico">Ordem de serviço</option></select></div><Field name="scope_id" label="UUID do escopo"/><Field name="access_start" label="Início da janela" type="date"/><Field name="access_end" label="Fim da janela" type="date"/><Field name="justification" label="Justificativa preenchida por quem opera"/></div><div className={styles.actions}><button disabled={!selected}>Conceder</button></div></form><form className={styles.panel} onSubmit={e=>{e.preventDefault();void mutate('revogação',`/api/ext/third-party/access-grants/${form.grant_id}/revoke`,'POST',{reason:form.reason},'rev')}}><h2>Revogar janela</h2><div className={styles.fieldRow}><Field name="grant_id" label="UUID da janela"/><Field name="reason" label="Motivo preenchido por quem opera"/></div><div className={styles.actions}><button>Revogar</button></div></form></>}
 {id==='documentos'&&<>{state(reads.documentos,'Nenhum documento registrado',d=>(d?.documents||[]).length?<ul className={styles.cards}>{d.documents.map((x:any)=><li className={styles.card} key={x.id}><strong>{x.document_type}</strong> — {labelThirdParty('expiry',x.expiry?.status)}<br/><small>{honestText(x.document_number)} · {honestDate(x.expiry_date)}</small></li>)}</ul>:<UiState variant="empty" title="Nenhum documento registrado"/>)}<form className={styles.panel} onSubmit={e=>{e.preventDefault();void mutate('documento',`/api/ext/third-party/parties/${selected}/documents`,'POST',{document_type:form.document_type,document_number:form.document_number||undefined,expiry_date:form.expiry_date||undefined,file_name:form.file_name||undefined},'doc')}}><h2>Registrar metadados do documento</h2><p className={styles.hint}>Não há upload de bytes nesta jornada.</p><div className={styles.fieldRow}><Field name="document_type" label="Tipo do documento"/><Field name="document_number" label="Número (opcional)"/><Field name="expiry_date" label="Validade (opcional)" type="date"/><Field name="file_name" label="Nome do arquivo (opcional)"/></div><div className={styles.actions}><button>Registrar</button></div></form><form className={styles.panel} onSubmit={e=>{e.preventDefault();void mutate('desativação',`/api/ext/third-party/documents/${form.document_id}/deactivate`,'POST',{reason:form.reason},'dcx')}}><h2>Desativar documento</h2><div className={styles.fieldRow}><Field name="document_id" label="UUID do documento"/><Field name="reason" label="Motivo preenchido por quem opera"/></div><div className={styles.actions}><button>Desativar</button></div></form></>}
 {id==='regras'&&<>{state(reads.regras,'Sem regra de antecedência',d=>(d?.rules||d?.document_rules||[]).length?<pre className={styles.codeBlock}>{JSON.stringify(d.rules||d.document_rules,null,2)}</pre>:<UiState variant="empty" title="Sem regra de antecedência" detail={d?.note}/>) }<form className={styles.panel} onSubmit={e=>{e.preventDefault();void mutate('regra',`/api/ext/third-party/parties/${selected}/document-rules`,'POST',{alert_before_days:Number(form.alert_before_days),justification:form.justification},'rul')}}><h2>Registrar regra de antecedência</h2><div className={styles.fieldRow}><Field name="alert_before_days" label="Antecedência em dias" type="number"/><Field name="justification" label="Justificativa preenchida por quem opera"/></div><div className={styles.actions}><button>Registrar regra</button></div></form></>}
 {id==='avaliacoes'&&<>{state(reads.avaliacoes,'Nenhuma avaliação registrada',d=>(d?.evaluations||[]).length?<ul className={styles.cards}>{d.evaluations.map((x:any)=><li className={styles.card} key={x.id}><strong>{x.score}/10</strong> em {honestDate(x.evaluated_on)}<p>{x.justification}</p></li>)}</ul>:<UiState variant="empty" title="Nenhuma avaliação registrada" detail={d?.note}/>)}<form className={styles.panel} onSubmit={e=>{e.preventDefault();void mutate('avaliação',`/api/ext/third-party/parties/${selected}/evaluations`,'POST',{score:Number(form.score),evaluated_on:form.evaluated_on,justification:form.justification},'avl')}}><h2>Registrar avaliação</h2><div className={styles.fieldRow}><Field name="score" label="Nota de 0 a 10" type="number"/><Field name="evaluated_on" label="Data avaliada" type="date"/><Field name="justification" label="Justificativa preenchida por quem opera"/></div><div className={styles.actions}><button>Registrar avaliação</button></div></form></>}
 {id==='autorizacao'&&<><form className={styles.panel} onSubmit={e=>{e.preventDefault();void check()}}><h2>Consultar decisão do ponto de imposição</h2><div className={styles.fieldRow}><div className={styles.field}><label htmlFor="third-check-kind">Tipo do escopo</label><select id="third-check-kind" value={form.scope_kind} onChange={e=>update('scope_kind',e.target.value)}><option value="contrato">Contrato</option><option value="ordem_servico">Ordem de serviço</option></select></div><Field name="scope_id" label="UUID do escopo"/></div><div className={styles.actions}><button disabled={!selected}>Consultar decisão</button></div></form>{state(reads.autorizacao,'Consulte uma decisão',d=>d?<div className={`${styles.notice} ${d.authorized?'':styles.noticeError}`}><strong>{d.authorized?'AUTORIZADO':'NEGADO'}</strong> — {labelThirdParty('authorization',d.reason)}<p>{d.derivation}</p></div>:<UiState variant="empty" title="Consulte uma decisão"/>)}</>}
 {id==='eventos'&&state(reads.eventos,'Nenhum evento registrado',d=>(d?.events||[]).length?<ul className={styles.cards}>{d.events.map((x:any)=><li className={styles.card} key={x.id}><strong>{labelThirdParty('event',x.event_type)}</strong><p>{x.summary}</p><small>{honestDate(x.created_at)}</small></li>)}</ul>:<UiState variant="empty" title="Nenhum evento registrado"/>)}
 </>}</section>)}
 {mutation&&<aside className={`${styles.notice} ${mutation.error?styles.noticeError:''}`} role="status"><strong>{mutation.message}</strong>{mutation.error&&<><p>{mutation.error.detail}</p><p className={styles.footnote}>Código técnico: {mutation.error.code??ABSENT} · Chave preservada: {keys[mutation.op]??Object.values(keys)[0]}</p></>}</aside>}
 </main>;
}
