'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent,type KeyboardEvent} from 'react';
import UiState from '../../../components/ui/UiState';
import UiBadge from '../../../components/ui/UiBadge';
import styles from '../../../components/ui/UiWorkspace.module.css';
import {continuityRequest} from '../../../lib/continuity-request';
import {describeContinuityError,continuityErrorFootnote,continuityStatusLabels,continuityStatusTones,CONTINUITY_TRANSITIONS,continuityTransitionLabels,honestTestDate,honestNextTest,type ContinuityErrorDescriptor} from '../../../lib/continuity-vocabulary.mjs';
type Plan={id:string;protocol:string;title:string;description:string;status:string;client_account_id?:string|null;client_name?:string|null;client_visible?:boolean;responsible_name:string;last_tested_at?:string|null;next_test_due?:string|null;contingency_steps?:string[];recovery_steps?:string[]};
type Detail={plan:Plan;events:any[];exercises:any[]};
type Load<T>={phase:'loading'}|{phase:'ready';data:T}|{phase:'failed';error:ContinuityErrorDescriptor};
const operationKey=()=>`cont-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const tabs=[['planos','Planos'],['novo','Novo plano'],['detalhe','Detalhe e ações']] as const;
const tabId=(id:string)=>`continuity-tab-${id}`;const panelId=(id:string)=>`continuity-panel-${id}`;
export function ContinuityWorkspace(){
 const [active,setActive]=useState<(typeof tabs)[number][0]>('novo');const [list,setList]=useState<Load<Plan[]>>({phase:'loading'});const [detail,setDetail]=useState<Load<Detail>|null>(null);const [selected,setSelected]=useState('');const [form,setForm]=useState({title:'',description:'',responsible_name:'',client_account_id:'',steps:'',recovery:''});const [exercise,setExercise]=useState({exercise_date:'',result:'',responsible_name:'',next_due:''});const [note,setNote]=useState('');const [error,setError]=useState<ContinuityErrorDescriptor|null>(null);const [heldKey,setHeldKey]=useState('');const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');const keys=useRef<Record<string,string>>({});const tabRefs=useRef<Array<HTMLButtonElement|null>>([]);
 const load=useCallback(async()=>{setList({phase:'loading'});const r=await continuityRequest<{items:Plan[]}>('/api/ext/continuity/plans');if(!r.ok){setList({phase:'failed',error:r.error});return;}setList({phase:'ready',data:Array.isArray(r.data.items)?r.data.items:[]});},[]);useEffect(()=>{load();},[load]);
 const detailLoad=async(id:string)=>{setSelected(id);setActive('detalhe');setDetail({phase:'loading'});const r=await continuityRequest<Detail>(`/api/ext/continuity/plans/${id}`);if(!r.ok){setDetail({phase:'failed',error:r.error});return;}setDetail({phase:'ready',data:r.data});};
 // A chave de idempotência sobrevive à falha (mesma operação pode ser repetida
 // com segurança) e só é descartada depois que o servidor confirma o sucesso.
 const mutate=async(keyName:string,url:string,init:RequestInit)=>{setBusy(keyName);setError(null);setNotice('');const r=await continuityRequest(url,init);setBusy('');if(!r.ok){setError(r.error);setHeldKey(keys.current[keyName]||'');return false;}delete keys.current[keyName];setHeldKey('');setNotice('Operação registrada pelo servidor.');await load();return true;};
 const create=async(e:FormEvent)=>{e.preventDefault();const op='create';keys.current[op]??=operationKey();const account=form.client_account_id.trim();const ok=await mutate(op,'/api/ext/continuity/plans',{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':keys.current[op]},body:JSON.stringify({title:form.title,description:form.description,responsible_name:form.responsible_name,...(account?{client_account_id:account}:{}),contingency_steps:form.steps.split('\n').filter(Boolean),recovery_steps:form.recovery.split('\n').filter(Boolean)})});if(ok){setForm({title:'',description:'',responsible_name:'',client_account_id:'',steps:'',recovery:''});setActive('planos');}};
 const transition=async(status:string)=>{if(!selected)return;const op=`transition-${selected}`;keys.current[op]??=operationKey();const ok=await mutate(op,`/api/ext/continuity/plans/${selected}/transition`,{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':keys.current[op]},body:JSON.stringify({status,...(note.trim()?{justification:note.trim()}: {})})});if(ok){setNote('');await detailLoad(selected);}};
 const visibility=async(p:Plan,visible:boolean)=>{const op=`visibility-${p.id}-${visible}`;keys.current[op]??=operationKey();const ok=await mutate(op,`/api/ext/continuity/plans/${p.id}/client-visibility`,{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':keys.current[op]},body:JSON.stringify({visible,...(visible?{note}:{})})});if(ok)setNote('');};
 const addExercise=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;const op=`exercise-${selected}`;keys.current[op]??=operationKey();const ok=await mutate(op,`/api/ext/continuity/plans/${selected}/exercises`,{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':keys.current[op]},body:JSON.stringify({...exercise,next_due:exercise.next_due||null})});if(ok){setExercise({exercise_date:'',result:'',responsible_name:'',next_due:''});await detailLoad(selected);}};
 const tabKey=(e:KeyboardEvent)=>{const i=tabs.findIndex(t=>t[0]===active);let n=i;if(e.key==='ArrowRight'||e.key==='ArrowDown')n=(i+1)%tabs.length;else if(e.key==='ArrowLeft'||e.key==='ArrowUp')n=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=tabs.length-1;else return;e.preventDefault();setActive(tabs[n][0]);tabRefs.current[n]?.focus();};
 // `canRetry` vem do vocabulário e é respeitado: oferecer "tentar novamente"
 // numa recusa de grant ou num 404 de escopo convidaria o operador a repetir
 // algo que o servidor vai recusar de novo.
 const state=(x:ContinuityErrorDescriptor,onRetry?:()=>void)=><UiState variant={x.kind==='denied'?'denied':'error'} title={x.title} detail={`${x.detail} ${continuityErrorFootnote(x)}`} onRetry={x.canRetry?onRetry:undefined}/>;
 return <main className={styles.workspace}><p className={styles.kicker}>EXT-10 · CONTINUIDADE OPERACIONAL</p><h1>Continuidade de negócios e contingência</h1><p className={styles.lede}>Planos, acionamentos internos, simulados e recuperação. O sistema registra o procedimento; não envia alertas externos nem simula fornecedor de emergência. A listagem respeita o escopo por conta de cliente e a publicação é explícita, justificada e somente leitura.</p>{error&&<div className={styles.panel} data-testid="continuity-action-error">{state(error)}{heldKey&&<p className={styles.hint} data-testid="continuity-held-key">Chave preservada para repetição segura: {heldKey}</p>}</div>}{notice&&<p role="status" className={styles.notice} data-testid="continuity-notice">{notice}</p>}<div role="tablist" aria-label="Jornada de continuidade" className={styles.tabs}>{tabs.map(([id,label],i)=><button key={id} id={tabId(id)} ref={el=>{tabRefs.current[i]=el}} role="tab" aria-selected={active===id} aria-controls={panelId(id)} tabIndex={active===id?0:-1} className={active===id?styles.tabActive:styles.tab} onClick={()=>setActive(id)} onKeyDown={tabKey}>{label}</button>)}</div>
 {active==='planos'&&<section className={`${styles.panel} ${styles.tabPanel}`} role="tabpanel" id={panelId('planos')} aria-labelledby={tabId('planos')} tabIndex={0} data-testid="continuity-list"><div className={styles.rowWrap}><h2 id="plans-title">Planos registrados</h2><button type="button" onClick={load} disabled={list.phase==='loading'}>Atualizar lista</button></div>{list.phase==='loading'&&<UiState variant="loading" title="Carregando planos" detail="Consultando o escopo concedido pelo servidor."/>}{list.phase==='failed'&&state(list.error,load)}{list.phase==='ready'&&!list.data.length&&<UiState variant="empty" title="Nenhum plano neste escopo" detail="A consulta foi concluída. Isso é diferente de uma falha de leitura."/>}{list.phase==='ready'&&list.data.map(p=><article className={styles.card} key={p.id} data-testid="continuity-plan-card" data-plan={p.id}><h3 className={styles.cardTitle}>{p.title}</h3><p className={styles.hint}>{p.protocol} · <UiBadge tone={(continuityStatusTones[p.status]||'neutral') as any} srPrefix="Situação">{continuityStatusLabels[p.status]||p.status}</UiBadge></p><p>{p.description}</p><p className={styles.hint}>Responsável: {p.responsible_name} · Simulado: {honestTestDate(p.last_tested_at)} · Próximo: {honestNextTest(p.next_test_due)}</p><p className={styles.hint}>Portal do cliente: {p.client_visible?'publicado, somente leitura':'não publicado por padrão'}</p>{p.client_account_id&&!p.client_visible&&<div className={styles.rowWrap}><input aria-label={`Justificativa de publicação de ${p.title}`} placeholder="Justificativa (mín. 10 caracteres)" value={selected===p.id?note:''} onChange={e=>{setSelected(p.id);setNote(e.target.value)}}/><button type="button" disabled={busy!==''} onClick={()=>visibility(p,true)}>Publicar no portal</button></div>}<div className={styles.actions}><button type="button" onClick={()=>detailLoad(p.id)}>Abrir plano</button>{p.client_visible&&<button type="button" disabled={busy!==''} onClick={()=>visibility(p,false)}>Retirar publicação</button>}</div></article>)}</section>}
 {active==='novo'&&<section className={`${styles.panel} ${styles.tabPanel}`} role="tabpanel" id={panelId('novo')} aria-labelledby={tabId('novo')} tabIndex={0} data-testid="continuity-new"><h2>Novo plano</h2><p className={styles.hint}>A conta é opcional; quando informada, o servidor aplica o grant de escopo da conta.</p><form className={styles.stack} onSubmit={create}><label>Título<input placeholder="Título" required minLength={5} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Descrição e escopo<textarea placeholder="Descrição e escopo" required minLength={10} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Responsável<input placeholder="Responsável" required minLength={2} value={form.responsible_name} onChange={e=>setForm({...form,responsible_name:e.target.value})}/></label><label>Conta de cliente (UUID, opcional)<input value={form.client_account_id} onChange={e=>setForm({...form,client_account_id:e.target.value})}/></label><label>Passos de contingência, um por linha<textarea placeholder="Passos de contingência, um por linha" value={form.steps} onChange={e=>setForm({...form,steps:e.target.value})}/></label><label>Passos de recuperação, um por linha<textarea placeholder="Passos de recuperação, um por linha" value={form.recovery} onChange={e=>setForm({...form,recovery:e.target.value})}/></label><button type="submit" disabled={busy==='create'}>{busy==='create'?'Registrando…':'Registrar plano'}</button></form></section>}
 {active==='detalhe'&&<section className={`${styles.panel} ${styles.tabPanel}`} role="tabpanel" id={panelId('detalhe')} aria-labelledby={tabId('detalhe')} tabIndex={0} data-testid="continuity-detail">{!selected&&<UiState variant="empty" title="Selecione um plano" detail="Abra um plano na lista para consultar sua trilha e ações."/>}{detail?.phase==='loading'&&<UiState variant="loading" title="Carregando plano"/>}{detail?.phase==='failed'&&state(detail.error,()=>detailLoad(selected))}{detail?.phase==='ready'&&<><h2>{detail.data.plan.title}</h2><p>{detail.data.plan.description}</p><p className={styles.hint}>Estado: <UiBadge tone={(continuityStatusTones[detail.data.plan.status]||'neutral') as any}>{continuityStatusLabels[detail.data.plan.status]||detail.data.plan.status}</UiBadge> · Simulado: {honestTestDate(detail.data.plan.last_tested_at)} · Próximo: {honestNextTest(detail.data.plan.next_test_due)}</p><div className={styles.twoColumns}><div><h3>Transição de estado</h3>{(CONTINUITY_TRANSITIONS[detail.data.plan.status]||[]).map(s=><button className={styles.actions} key={s} type="button" onClick={()=>transition(s)}>{continuityTransitionLabels[s]||s}</button>)}<label>Justificativa, quando necessária<input value={note} onChange={e=>setNote(e.target.value)}/></label></div><form onSubmit={addExercise}><h3>Documentar simulado</h3><label>Data<input required type="date" value={exercise.exercise_date} onChange={e=>setExercise({...exercise,exercise_date:e.target.value})}/></label><label>Resultado<textarea required minLength={10} value={exercise.result} onChange={e=>setExercise({...exercise,result:e.target.value})}/></label><label>Responsável<input placeholder="Responsável" required minLength={2} value={exercise.responsible_name} onChange={e=>setExercise({...exercise,responsible_name:e.target.value})}/></label><label>Próximo teste (opcional)<input type="date" value={exercise.next_due} onChange={e=>setExercise({...exercise,next_due:e.target.value})}/></label><button type="submit">Registrar simulado</button></form></div><h3>Trilha imutável</h3><p>{detail.data.events.length} evento(s) registrados; {detail.data.exercises.length} simulado(s) documentado(s).</p></>}</section>}</main>;
}
