'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import HrClient from '../ti/HrClient';
import HrRecruitmentClient from '../ti/HrRecruitmentClient';
import HrTerminationClient from '../ti/HrTerminationClient';
import HrAbsenceClient from '../ti/HrAbsenceClient';
import HrBenefitsClient from '../ti/HrBenefitsClient';
import HrTrainingClient from '../ti/HrTrainingClient';
import HrAdvancedClient from '../ti/HrAdvancedClient';
import styles from './RhWorkspace.module.css';

type Employee={id:string;display_name:string;matricula:string;status:string;cargo:string;lotacao?:string};
type Overview={employees:Employee[];indicators:{total:number;active:number;unavailable:number;admissions:number};scopes:any[]};
type Doc={id:string;employee_id:string;employee_name:string;title:string;document_kind:string;competence?:string;status:string;source_authorized:boolean};
type SelfRequest={id:string;protocol:string;employee_id:string;employee_name:string;matricula:string;request_type:string;title:string;description:string;status:string;notes?:string;rejection_reason?:string;followups?:{status:string;message:string;created_at:string}[]};
type View='equipe'|'admissao'|'escala'|'solicitacoes'|'documentos'|'folha'|'desligamento'|'processos';
type HrProcess='cadastro'|'recrutamento'|'desligamento'|'jornada'|'beneficios'|'desenvolvimento'|'gestao';
async function api(path:string,init:RequestInit={}){const r=await fetch(path,{...init,credentials:'same-origin',headers:{accept:'application/json',...(init.body?{'content-type':'application/json'}:{}),...(init.headers||{})}});const text=await r.text();let body:any;try{body=JSON.parse(text)}catch{body={error:text}}if(!r.ok)throw new Error(body?.error||`http_${r.status}`);return body;}
async function encoded(file:File){const bytes=new Uint8Array(await file.arrayBuffer());let bin='';for(let i=0;i<bytes.length;i+=8192)bin+=String.fromCharCode(...bytes.subarray(i,i+8192));return{filename:file.name,contentType:file.type||'application/octet-stream',contentBase64:btoa(bin)}}

export default function RhWorkspace(){
  const [overview,setOverview]=useState<Overview|null>(null),[docs,setDocs]=useState<Doc[]>([]),[requests,setRequests]=useState<SelfRequest[]>([]),[view,setView]=useState<View>('equipe');
  const [message,setMessage]=useState(''),[error,setError]=useState(''),[credential,setCredential]=useState<any>(null);
  const refresh=useCallback(async()=>{try{const [o,d,r]=await Promise.all([api('/api/admin/hr/l03/overview'),api('/api/admin/hr/l03/documents'),api('/api/admin/hr/l03/self-requests')]);setOverview(o);setDocs(d.documents||[]);setRequests(r.requests||[]);setError('');}catch(e:any){setError(e.message);}},[]);
  useEffect(()=>{refresh()},[refresh]);
  async function run(task:()=>Promise<any>,success:string){setError('');setMessage('');try{const data=await task();setMessage(success);await refresh();return data}catch(e:any){setError(e.message);return null}}
  const employees=overview?.employees||[],metrics=overview?.indicators||{total:0,active:0,unavailable:0,admissions:0};
  const tabs:[View,string][]=[['equipe','Equipe'],['admissao','Admissão & acesso'],['escala','Escala'],['solicitacoes','Solicitações'],['documentos','Documentos'],['folha','Fechamento & holerite'],['desligamento','Desligamento'],['processos','Processos HR-01..24']];
  return <main className={styles.page}><header className={styles.header}><div className={styles.eyebrow}>SEG System • RH com acesso granular</div><h1>Pessoas & jornada do funcionário</h1><p>Admissão, acesso individual, escala, documentos privados, solicitações, folha demonstrativa e desligamento.</p></header><div className={styles.main}>{message&&<div className={styles.notice}>{message}</div>}{error&&<div className={`${styles.notice} ${styles.error}`}>{error==='admin_session_required'?'Entre com uma conta de staff autorizada para acessar este painel.':error}</div>}{credential&&<div className={styles.credential}><b>Credencial temporária — exibição única</b><div>{credential.email}</div><code>{credential.temporaryPassword}</code><p className={styles.muted}>Entregue por canal local controlado. O funcionário deverá trocar a senha; não há envio SMTP.</p><button className={`${styles.button} ${styles.secondary}`} onClick={()=>setCredential(null)}>Já registrei em local seguro</button></div>}<section className={styles.metrics}><div className={styles.metric}><b>{metrics.total}</b><span>cadastros no escopo</span></div><div className={styles.metric}><b>{metrics.active}</b><span>ativos</span></div><div className={styles.metric}><b>{metrics.admissions}</b><span>em admissão</span></div><div className={styles.metric}><b>{metrics.unavailable}</b><span>afastados/suspensos</span></div></section><nav className={styles.tabs}>{tabs.map(([id,label])=><button className={view===id?styles.active:''} key={id} onClick={()=>setView(id)}>{label}</button>)}</nav>{view==='equipe'&&<Team employees={employees}/>} {view==='admissao'&&<Admission employees={employees} run={run} onCredential={setCredential}/>} {view==='escala'&&<Schedule employees={employees} run={run}/>} {view==='solicitacoes'&&<RequestReviews requests={requests} run={run}/>} {view==='documentos'&&<Documents docs={docs} run={run}/>} {view==='folha'&&<Payroll employees={employees} docs={docs} run={run}/>} {view==='desligamento'&&<Termination employees={employees} run={run}/>} {view==='processos'&&<HrProcesses/>}</div></main>
}

function RequestReviews({requests,run}:{requests:SelfRequest[];run:any}){
  const [messages,setMessages]=useState<Record<string,string>>({}),[feedback,setFeedback]=useState('');
  async function review(item:SelfRequest,action:'em_analise'|'aprovar'|'rejeitar'){
    const message=(messages[item.id]||'').trim();
    if(message.length<5){setFeedback('Escreva um retorno com ao menos 5 caracteres antes de registrar a análise.');return;}
    const result=await run(()=>api('/api/admin/hr/l03/self-requests',{method:'PATCH',headers:{'Idempotency-Key':`rh-request-${crypto.randomUUID()}`},body:JSON.stringify({id:item.id,action,message})}),action==='em_analise'?'Análise registrada e visível ao funcionário.':action==='aprovar'?'Solicitação aprovada e retorno publicado.':'Solicitação rejeitada com retorno publicado.');
    if(result){setMessages(current=>({...current,[item.id]:''}));setFeedback('');}
  }
  return <section className={styles.panel}><h2>Solicitações do funcionário</h2><p className={styles.muted}>A análise exige mensagem explícita, segue a ordem solicitado → em análise → decisão e o retorno aparece somente no portal do titular. Não há envio SMTP.</p>{feedback&&<div className={`${styles.notice} ${styles.error}`}>{feedback}</div>}<div className={styles.requestList}>{requests.map(item=><article className={styles.requestCard} key={item.id}><header><div><b>{item.protocol}</b><span>{item.employee_name} • {item.matricula}</span></div><span className={styles.tag}>{item.status}</span></header><h3>{item.title}</h3><p>{item.description}</p>{Array.isArray(item.followups)&&item.followups.map((follow,index)=><p className={styles.muted} key={`${item.id}-${index}`}><b>Registro RH:</b> {follow.message} • {follow.status}</p>)}{['solicitado','em_analise'].includes(item.status)&&<><label className={styles.reviewLabel}>Retorno para {item.protocol}<textarea className={styles.textarea} aria-label={`Retorno para ${item.protocol}`} value={messages[item.id]||''} onChange={event=>setMessages(current=>({...current,[item.id]:event.target.value}))} placeholder={item.status==='solicitado'?'Descreva o início da análise':'Descreva a decisão para o funcionário'} minLength={5}/></label><div className={styles.actions}>{item.status==='solicitado'&&<button className={styles.button} onClick={()=>review(item,'em_analise')}>Iniciar análise</button>}{item.status==='em_analise'&&<><button className={styles.button} onClick={()=>review(item,'aprovar')}>Aprovar solicitação</button><button className={`${styles.button} ${styles.danger}`} onClick={()=>review(item,'rejeitar')}>Rejeitar solicitação</button></>}</div></>}</article>)}{!requests.length&&<div className={styles.muted}>Nenhuma solicitação no escopo autorizado.</div>}</div></section>
}

function HrProcesses(){
  const [process,setProcess]=useState<HrProcess>('cadastro');
  const options:[HrProcess,string,string][]=[
    ['cadastro','HR-01, 02 e 05','Cadastro, histórico e admissão'],
    ['recrutamento','HR-03, 04 e 06','Recrutamento, talentos e dossiê'],
    ['desligamento','HR-07 a 09','Desligamento, status e férias'],
    ['jornada','HR-10 a 12','Afastamento, ponto e banco de horas'],
    ['beneficios','HR-13 a 16','Benefícios, reembolsos, saúde e exportação'],
    ['desenvolvimento','HR-17 a 20','Treinamento, competências, uniformes e DP'],
    ['gestao','HR-21 a 24','Folha, avaliações, atendimento e indicadores'],
  ];
  return <section className={styles.processes}>
    <div className={styles.processIntro}><h2>Processos completos do RH</h2><p>Escolha uma frente. Cada ação usa a sessão individual de staff e permissões separadas; saúde e remuneração exigem concessões próprias. IDs técnicos são exibidos apenas onde o cadastro relacionado ainda precisa ser selecionado de forma inequívoca.</p></div>
    <nav className={styles.processNav} aria-label="Grupos de processos de RH">{options.map(([id,range,label])=><button key={id} className={process===id?styles.active:''} onClick={()=>setProcess(id)}><b>{range}</b><span>{label}</span></button>)}</nav>
    <div className={styles.legacy}>
      {process==='cadastro'&&<HrClient/>}
      {process==='recrutamento'&&<HrRecruitmentClient/>}
      {process==='desligamento'&&<HrTerminationClient/>}
      {process==='jornada'&&<HrAbsenceClient/>}
      {process==='beneficios'&&<HrBenefitsClient/>}
      {process==='desenvolvimento'&&<HrTrainingClient/>}
      {process==='gestao'&&<HrAdvancedClient/>}
    </div>
  </section>;
}
function Team({employees}:{employees:Employee[]}){return <section className={styles.panel}><h2>Equipe alcançada pelas concessões ativas</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Matrícula</th><th>Nome</th><th>Cargo</th><th>Lotação</th><th>Status</th></tr></thead><tbody>{employees.map(e=><tr key={e.id}><td>{e.matricula}</td><td>{e.display_name}</td><td>{e.cargo}</td><td>{e.lotacao||'—'}</td><td><span className={styles.tag}>{e.status}</span></td></tr>)}</tbody></table></div><p className={styles.muted}>Remuneração não integra esta listagem. A leitura salarial exige employees.compensation.read.</p></section>}
function Admission({employees,run,onCredential}:{employees:Employee[];run:any;onCredential:(v:any)=>void}){async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));await run(async()=>{const made=await api('/api/hr/employees',{method:'POST',body:JSON.stringify({...f,status:'em_admissao',employment_type:'clt'})});await api('/api/hr/admissions',{method:'POST',body:JSON.stringify({employee_id:made.employee.id,cargo:String(f.cargo||'').toLowerCase(),responsible_name:'RH via SEG System',notes:'Admissão iniciada pela interface L03'})});return made;},'Cadastro profissional e fluxo de admissão criados.');}async function provision(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const out=await run(()=>api(`/api/admin/hr/employees/${f.employeeId}/access`,{method:'POST',body:JSON.stringify({email:f.email})}),'Acesso individual criado.');if(out)onCredential(out)}return <div className={styles.layout}><section className={styles.panel}><h2>Novo cadastro profissional</h2><form className={styles.form} onSubmit={create}><div className={styles.row}><input className={styles.input} name="matricula" placeholder="Matrícula" required/><input className={styles.input} name="display_name" placeholder="Nome completo" minLength={3} required/></div><div className={styles.row}><input className={styles.input} name="cargo" placeholder="Cargo" required/><input className={styles.input} name="lotacao" placeholder="Lotação"/></div><div className={styles.row}><input className={styles.input} name="empregador" placeholder="Empregador"/><input className={styles.input} name="admission_date" type="date"/></div><button className={styles.button}>Criar cadastro separado do login</button></form></section><section className={styles.panel}><h2>Criar acesso do funcionário</h2><form className={styles.form} onSubmit={provision}><EmployeeSelect employees={employees.filter(e=>['ativo','em_admissao'].includes(e.status))}/><input className={styles.input} name="email" type="email" placeholder="E-mail individual" required/><button className={styles.button}>Gerar credencial temporária</button></form><p className={styles.muted}>O funcionário nunca recebe sessão de staff/RH. O vínculo é um-para-um.</p></section></div>}
function Schedule({employees,run}:{employees:Employee[];run:any}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));await run(async()=>{const v=await api('/api/hr/schedule-versions',{method:'POST',body:JSON.stringify({title:f.title,period_start:f.periodStart,period_end:f.periodEnd})});await api('/api/hr/schedule-entries',{method:'POST',body:JSON.stringify({version_id:v.version.id,employee_id:f.employeeId,entry_date:f.entryDate,start_time:f.startTime,end_time:f.endTime,location:f.location})});await api('/api/hr/shift-assignments',{method:'POST',body:JSON.stringify({employee_id:f.employeeId,shift_date:f.entryDate,start_time:f.startTime,end_time:f.endTime,location:f.location,function_name:'Plantão publicado',orientations:'Consulte a versão de escala e confirme ciência',required_items:['Documento funcional'],status:'publicado',is_next_shift:true})});return api('/api/hr/schedule-versions',{method:'PATCH',body:JSON.stringify({id:v.version.id,status:'publicado'})});},'Escala versionada e publicada; ciência pendente no portal do funcionário.');}return <section className={styles.panel}><h2>Publicar escala versionada</h2><form className={styles.form} onSubmit={submit}><EmployeeSelect employees={employees}/><div className={styles.row}><input className={styles.input} name="title" placeholder="Título da versão" required/><input className={styles.input} name="location" placeholder="Posto/local" required/></div><div className={styles.row}><label>Início do período<input className={styles.input} name="periodStart" type="date" required/></label><label>Fim do período<input className={styles.input} name="periodEnd" type="date" required/></label></div><div className={styles.row}><input className={styles.input} name="entryDate" type="date" required/><span className={styles.row}><input className={styles.input} name="startTime" type="time" required/><input className={styles.input} name="endTime" type="time" required/></span></div><button className={styles.button}>Criar versão, incluir turno e publicar</button></form></section>}
function Documents({docs,run}:{docs:Doc[];run:any}){return <section className={styles.panel}><h2>Envios privados aguardando revisão</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Funcionário</th><th>Documento</th><th>Tipo</th><th>Status</th><th>Ação</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td>{d.employee_name}</td><td>{d.title}</td><td>{d.document_kind}</td><td><span className={styles.tag}>{d.status}</span></td><td className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} onClick={()=>run(()=>api('/api/admin/hr/l03/documents',{method:'PATCH',body:JSON.stringify({id:d.id,status:'approved'})}),'Documento aprovado após revisão.')}>Aprovar</button><a className={`${styles.button} ${styles.secondary}`} href={`/api/admin/hr/l03/documents/${d.id}/download`}>Baixar</a></td></tr>)}</tbody></table></div></section>}
function Payroll({employees,docs,run}:{employees:Employee[];docs:Doc[];run:any}){async function close(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));await run(()=>api('/api/hr/dp-closures',{method:'POST',body:JSON.stringify({competence:f.competence,action:'fechar',notes:'Fechamento demonstrativo confirmado pela interface'})}),'Competência demonstrativa fechada.');}async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,fd=new FormData(form),file=fd.get('file') as File;const p=await encoded(file);await run(async()=>{const made=await api('/api/admin/hr/l03/documents',{method:'POST',body:JSON.stringify({...p,employeeId:fd.get('employeeId'),documentKind:'payroll',category:'folha',title:`Holerite ${fd.get('competence')}`,competence:fd.get('competence'),sourceAuthorized:true,sourceLabel:'Fonte de folha autorizada pelo operador'})});return api('/api/admin/hr/l03/documents',{method:'PATCH',body:JSON.stringify({id:made.document.id,status:'published'})});},'Holerite privado publicado para o titular.');form.reset()}return <div className={styles.layout}><section className={styles.panel}><h2>Fechar período demonstrativo</h2><form className={styles.form} onSubmit={close}><input className={styles.input} name="competence" placeholder="AAAA-MM" pattern="\d{4}-\d{2}" required/><button className={styles.button}>Validar divergências e fechar</button></form></section><section className={styles.panel}><h2>Publicar holerite próprio</h2><form className={styles.form} onSubmit={upload}><EmployeeSelect employees={employees}/><input className={styles.input} name="competence" placeholder="AAAA-MM" pattern="\d{4}-\d{2}" required/><input className={styles.input} name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.txt" required/><button className={styles.button}>Enviar de fonte autorizada e publicar</button></form><p className={styles.muted}>Exige concessão separada employees.compensation.write; o arquivo não possui URL pública.</p></section><section className={`${styles.panel} ${styles.full}`}><h2>Publicações salariais</h2>{docs.filter(d=>d.document_kind==='payroll').map(d=><span className={styles.tag} key={d.id}>{d.employee_name} • {d.competence} • {d.status}</span>)}</section></div>}
function Termination({employees,run}:{employees:Employee[];run:any}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(!confirm('Concluir desligamento e revogar imediatamente a sessão do funcionário?'))return;await run(async()=>{const made=await api('/api/hr/terminations',{method:'POST',body:JSON.stringify({employee_id:f.employeeId,type:f.type,termination_date:f.date,reason:f.reason,responsible_name:'RH via SEG System'})});return api('/api/hr/terminations',{method:'PATCH',body:JSON.stringify({id:made.termination.id,status:'concluido'})});},'Desligamento concluído e sessões existentes revogadas.');}return <section className={styles.panel}><h2>Desligamento com revogação</h2><form className={styles.form} onSubmit={submit}><EmployeeSelect employees={employees.filter(e=>e.status!=='desligado')}/><div className={styles.row}><select className={styles.select} name="type"><option value="termino_contrato">Término de contrato</option><option value="pedido_demissao">Pedido de demissão</option><option value="dispensa_sem_justa">Dispensa sem justa causa</option><option value="outro">Outro</option></select><input className={styles.input} name="date" type="date" required/></div><textarea className={styles.textarea} name="reason" minLength={10} placeholder="Motivo documentado" required/><button className={`${styles.button} ${styles.danger}`}>Concluir e revogar acesso</button></form></section>}
function EmployeeSelect({employees}:{employees:Employee[]}){return <select className={styles.select} name="employeeId" required><option value="">Selecione o funcionário</option>{employees.map(e=><option key={e.id} value={e.id}>{e.display_name} • {e.matricula} • {e.status}</option>)}</select>}
