'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import UiTaskWorkspace from '@/components/ui/UiTaskWorkspace';
import {hrRequest} from '@/lib/hr-request';
async function api(url:string,init:RequestInit={}){const r=await hrRequest<any>(url,init);if(!r.ok)throw Error(`${r.error.title}. ${r.error.detail}`);return r.data;}
type Correction={id:string;employee_name:string;matricula:string;time_entry_id:string;employee_id:string;entry_date:string;reason:string;status:string;requested_changes:Record<string,unknown>;original_snapshot:Record<string,unknown>;approved_changes?:Record<string,unknown>;clock_in:string|null;clock_out:string|null;hours_worked:number|null;rejection_reason?:string};
export default function TimeCorrectionReviews({employees}:{employees:{id:string;display_name:string;matricula:string}[]}){
 const [items,setItems]=useState<Correction[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const load=useCallback(async()=>{setLoading(true);setMessage('');try{const d=await api('/api/admin/hr/l03/time-corrections');setItems(d.corrections);}catch(e){setItems([]);setMessage(e instanceof Error?e.message:'Consulta indisponível.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 return <UiTaskWorkspace aria-busy={loading}><ClockHistory employees={employees}/><h3>Ajustes de ponto solicitados pelos funcionários</h3><p>Leia o motivo e confira os horários e as horas efetivamente trabalhadas, descontando os intervalos. Aprovar atualiza o resumo da jornada; as marcações e a localização originais permanecem preservadas.</p><p role="status">{message}</p><button type="button" disabled={loading} onClick={()=>void load()}>Atualizar pedidos</button>{loading&&<p role="status">Consultando pedidos…</p>}{!loading&&!message&&!items.length&&<p>Nenhum pedido no seu escopo de acesso.</p>}{items.map(c=><Review key={c.id+':'+c.status} item={c} refresh={load}/>)}</UiTaskWorkspace>;
}
function ClockHistory({employees}:{employees:{id:string;display_name:string;matricula:string}[]}){
 const [employeeId,setEmployeeId]=useState(''),[entries,setEntries]=useState<{id:string;entry_date:string;clock_in:string;clock_out:string;hours_worked:number;status:string}[]|null>(null),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[proofs,setProofs]=useState<{id:string;kind:string;recorded_at:string;latitude:number;longitude:number;accuracy_m:number}[]|null>(null);
 useEffect(()=>{let active=true;setEntries(null);setProofs(null);setMessage('');if(!employeeId){setLoading(false);return;}setLoading(true);api(`/api/admin/hr/l03/time-clock?employee_id=${encodeURIComponent(employeeId)}`).then(d=>{if(active)setEntries(d.entries);}).catch(e=>{if(active)setMessage(e instanceof Error?e.message:'Leitura indisponível.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[employeeId]);
 async function show(entryId:string){setLoading(true);setProofs(null);setMessage('');try{const d=await api(`/api/admin/hr/l03/time-punches?employee_id=${encodeURIComponent(employeeId)}&entry_id=${encodeURIComponent(entryId)}`);setProofs(d.punches);}catch(e){setMessage(e instanceof Error?e.message:'Leitura indisponível.');}finally{setLoading(false);}}
 return <section><h3>Consultar ponto por funcionário</h3><label>Funcionário<select disabled={loading} value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Selecione</option>{employees.map(e=><option key={e.id} value={e.id}>{e.display_name} · {e.matricula}</option>)}</select></label><p role="status">{loading?'Consultando ponto…':message}</p>{entries?.map(e=><article key={e.id}><p>{String(e.entry_date).slice(0,10)} · {e.clock_in||'—'}–{e.clock_out||'—'} · {e.hours_worked??'—'} h · {e.status}</p><button type="button" disabled={loading} onClick={()=>void show(e.id)}>Ver marcações e localização</button></article>)}{entries?.length===0&&<p>Sem registros para este funcionário.</p>}{proofs&&<div><h4>Marcações originais da jornada selecionada</h4>{!proofs.length&&<p>Sem marcações geográficas: registro manual/importado.</p>}{proofs.map(p=><p key={p.id}>{p.kind} · {new Date(p.recorded_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} · {p.latitude.toFixed(5)}, {p.longitude.toFixed(5)} · precisão {Math.round(p.accuracy_m)} m</p>)}</div>}</section>;
}
function Review({item:c,refresh}:{item:Correction;refresh:()=>Promise<void>}){
 const [clockIn,setClockIn]=useState(String(c.requested_changes.clock_in||c.clock_in||'').slice(0,5)),[clockOut,setClockOut]=useState(String(c.requested_changes.clock_out||c.clock_out||'').slice(0,5)),[hours,setHours]=useState(c.requested_changes.hours_worked==null?'':String(c.requested_changes.hours_worked)),[reason,setReason]=useState(''),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [punches,setPunches]=useState<{id:string;kind:string;recorded_at:string;latitude:number;longitude:number;accuracy_m:number}[]|null>(null);
 const lock=useRef(false);const pending=['solicitado','em_analise'].includes(c.status);
 async function decide(status:string){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{
  if(status==='aprovado'&&(!reviewed||hours===''||!Number.isFinite(Number(hours))||Number(hours)<0||Number(hours)>24)){setMessage('Revise os dados e informe as horas trabalhadas entre 0 e 24.');return;}
  await api('/api/admin/hr/l03/time-corrections',{method:'PATCH',body:JSON.stringify({id:c.id,status,rejection_reason:reason,approved_changes:status==='aprovado'?{clock_in:clockIn,clock_out:clockOut,hours_worked:Number(hours)}:undefined})});await refresh();
 }catch(e){setMessage(e instanceof Error?e.message:'Decisão não confirmada.');}finally{lock.current=false;setBusy(false);}}
 async function proofs(){setBusy(true);try{const d=await api(`/api/admin/hr/l03/time-punches?employee_id=${encodeURIComponent(c.employee_id)}&entry_id=${encodeURIComponent(c.time_entry_id)}`);setPunches(d.punches);}catch(e){setMessage(e instanceof Error?e.message:'Comprovantes indisponíveis.');}finally{setBusy(false);}}
 return <article style={{border:'1px solid var(--ux-color-border)',borderRadius:12,padding:16,marginTop:16}}><h4>{c.employee_name} · {c.matricula} · {String(c.entry_date).slice(0,10)}</h4><p>Status: {c.status} · Registro atual: {c.clock_in||'—'}–{c.clock_out||'—'} · {c.hours_worked??'—'} h</p><p>Motivo: {c.reason}</p>{c.rejection_reason&&<p>Rejeição: {c.rejection_reason}</p>}<details><summary>Original preservado e alteração solicitada</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify({original:c.original_snapshot,solicitado:c.requested_changes,aprovado:c.approved_changes},null,2)}</pre></details><button type="button" disabled={busy} onClick={()=>void proofs()}>Consultar marcações e localização</button>{punches&&<div>{!punches.length&&<p>Registro manual/importado sem marcações geográficas.</p>}{punches.map(p=><p key={p.id}>{p.kind} · {new Date(p.recorded_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} · {p.latitude.toFixed(5)}, {p.longitude.toFixed(5)} · precisão {Math.round(p.accuracy_m)} m</p>)}</div>}
 {pending&&<fieldset disabled={busy}><legend>Decisão do RH</legend><label>Entrada aprovada<input type="time" value={clockIn} onChange={e=>setClockIn(e.target.value)}/></label><label>Saída aprovada<input type="time" value={clockOut} onChange={e=>setClockOut(e.target.value)}/></label><label>Horas trabalhadas após ajuste<input type="number" min="0" max="24" step="0.01" value={hours} onChange={e=>setHours(e.target.value)}/></label><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>Revisei o original, a solicitação e as horas trabalhadas.</label><button type="button" onClick={()=>void decide('em_analise')}>Colocar em análise</button><button type="button" disabled={!reviewed||hours===''} onClick={()=>void decide('aprovado')}>Aprovar ajuste</button><label>Motivo da rejeição<textarea minLength={5} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" disabled={reason.trim().length<5} onClick={()=>void decide('rejeitado')}>Rejeitar ajuste</button></fieldset>}
 <p role="status">{message}</p></article>;
}
