// EXT-06: PostgreSQL real + servidor HTTP real; somente fixtures .invalid.
import test,{before,after} from "node:test";import assert from "node:assert/strict";import {spawn} from "node:child_process";import {createHash,randomBytes,randomUUID} from "node:crypto";import path from "node:path";import pg from "pg";import {hashPassword} from "../src/lib/client-auth-core.mjs";
const RUN=process.env.RUN_DATABASE_INTEGRATION==="1"&&process.env.DATABASE_URL,REQUIRE=process.env.QA_EXT06_REQUIRE_DB==="1",root=path.resolve(import.meta.dirname,"..");test("EXT-06 gate exige PostgreSQL real",()=>{if(REQUIRE)assert.ok(RUN)});
let server,base,pool,ti,rh,clientId,accountId,cookieTi,cookieRh,cookieClient;const idem=t=>`ext06-${t}-${randomUUID()}`;
async function wait(){for(let i=0;i<180;i++){try{if([200,401].includes((await fetch(`${base}/api/admin/session`)).status))return}catch{}await new Promise(r=>setTimeout(r,400))}throw Error("server_did_not_start")}
async function staff(role){const id=randomUUID(),email=`ext06-${role}-${id.slice(0,8)}@example.invalid`,password="Senha-Sintetica-9!";await pool.query(`INSERT INTO auth_identities(id,kind,email,display_name,status) VALUES($1,'staff',$2,$3,'active')`,[id,email,`QA EXT06 ${role}`]);await pool.query(`INSERT INTO auth_credentials(identity_id,password_hash) VALUES($1,$2)`,[id,await hashPassword(password)]);await pool.query(`INSERT INTO auth_staff_profiles(identity_id,role,assigned_by) VALUES($1,$2,'admin_system')`,[id,role]);return{id,email,password}}
async function login(s){const r=await fetch(`${base}/api/admin/session`,{method:"POST",headers:{"content-type":"application/json",origin:base},body:JSON.stringify({email:s.email,password:s.password})});assert.equal(r.status,200);return r.headers.getSetCookie().find(x=>x.startsWith("seg_admin_session=")).split(";")[0]}
async function api(url,{method="GET",cookie=cookieTi,body,key,origin=base,raw}={}){const headers={accept:"application/json",origin,...(cookie?{cookie}:{}),...(method!=="GET"?{"idempotency-key":key===null?"":key||idem("request")}:{})};if(raw===undefined&&body!==undefined)headers["content-type"]="application/json";const r=await fetch(base+url,{method,headers,body:raw===undefined?(body===undefined?undefined:JSON.stringify(body)):raw});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}}return{status:r.status,body:data,text}}
const config=(over={})=>({client_account_id:accountId,target_identity_id:clientId,survey_type:"pos_atendimento",purpose:"Medir atendimento sintético para QA.",methodology:"generica",methodology_source:"Política sintética QA versão 1.",scale_min:0,scale_max:10,follow_up_threshold:6,reference_start:null,reference_end:null,...over});
async function create(over={},options={}){const x=await api("/api/ext/satisfaction/surveys",{method:"POST",body:config(over),...options});assert.equal(x.status,201,x.text);return x.body.survey}
async function answer(id,score=3,options={}){return api("/api/client/satisfaction-surveys",{method:"POST",cookie:cookieClient,body:{survey_id:id,score,feedback:"Comentário sintético suficientemente detalhado para a prova."},...options})}
before(async()=>{if(!RUN)return;pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:10});const port=3400+Math.floor(Math.random()*900);base=`http://127.0.0.1:${port}`;server=spawn(process.execPath,["server.mjs","--dev"],{cwd:root,env:{...process.env,PORT:String(port),BIND_HOST:"127.0.0.1",NODE_ENV:"development",NEXT_DIST_DIR:".next/integration-ext06",SITE_ADMIN_SESSION_SECRET:randomUUID().repeat(2),CLIENT_MFA_ENCRYPTION_KEY:randomBytes(32).toString("base64url"),SITE_ADMIN_LEGACY_TOKENS:"",OLLAMA_ENABLED:"false",MAIL_HOST:"",NEXT_TELEMETRY_DISABLED:"1"},stdio:["ignore","pipe","pipe"]});let logs="";server.stdout.on("data",x=>logs+=x);server.stderr.on("data",x=>logs+=x);try{await wait()}catch(e){throw Error(`${e.message}\n${logs.slice(-3000)}`)}ti=await staff("ti");rh=await staff("rh");cookieTi=await login(ti);cookieRh=await login(rh);clientId=randomUUID();accountId=randomUUID();const token=randomBytes(32).toString("hex");await pool.query(`INSERT INTO auth_identities(id,kind,email,display_name,status,verification_method,verified_at) VALUES($1,'client',$2,'Cliente QA','active','email_link',NOW())`,[clientId,`cliente-${clientId.slice(0,8)}@example.invalid`]);await pool.query(`INSERT INTO client_accounts(id,display_name,created_by) VALUES($1,'Conta sintética EXT06','ti')`,[accountId]);await pool.query(`INSERT INTO client_access_grants(id,identity_id,client_account_id,reason,granted_by) VALUES($1,$2,$3,'Escopo sintético EXT06','ti')`,[randomUUID(),clientId,accountId]);await pool.query(`INSERT INTO auth_sessions(id,identity_id,token_hash,expires_at) VALUES($1,$2,$3,NOW()+INTERVAL '1 hour')`,[randomUUID(),clientId,createHash("sha256").update(token).digest("hex")]);cookieClient=`seg_client_session=${token}`});
after(async()=>{await pool?.end().catch(()=>{});if(server&&!server.killed){server.kill("SIGTERM");await new Promise(r=>setTimeout(r,300));server.kill("SIGKILL")}});const opt={skip:!RUN};
test("EXT-06 HTTP staff anônimo 401",opt,async()=>assert.equal((await api("/api/ext/satisfaction/surveys",{cookie:null})).status,401));
test("EXT-06 HTTP staff papel negado 403",opt,async()=>assert.equal((await api("/api/ext/satisfaction/surveys",{cookie:cookieRh})).status,403));
test("EXT-06 HTTP cliente anônimo 401",opt,async()=>assert.equal((await api(`/api/client/satisfaction-surveys?account=${accountId}`,{cookie:null})).status,401));
test("EXT-06 HTTP cliente sem grant 403 sem pesquisa",opt,async()=>assert.equal((await api(`/api/client/satisfaction-surveys?account=${randomUUID()}`,{cookie:cookieClient})).status,403));
test("EXT-06 HTTP same-origin",opt,async()=>assert.equal((await api("/api/ext/satisfaction/surveys",{method:"POST",body:config(),origin:"https://attacker.invalid"})).status,403));
test("EXT-06 HTTP chave obrigatória",opt,async()=>assert.equal((await api("/api/ext/satisfaction/surveys",{method:"POST",body:config(),key:null})).status,400));
test("EXT-06 HTTP JSON inválido",opt,async()=>assert.equal((await api("/api/ext/satisfaction/surveys",{method:"POST",raw:"{"})).status,400));
test("EXT-06 HTTP corpo grande",opt,async()=>assert.equal((await api("/api/ext/satisfaction/surveys",{method:"POST",raw:JSON.stringify({x:"x".repeat(40000)})})).status,413));
test("EXT-06 HTTP vínculo/UUID forjado recusado",opt,async()=>assert.equal((await api("/api/ext/satisfaction/surveys",{method:"POST",body:config({client_account_id:"bad"})})).status,400));
test("EXT-06 HTTP destinatário sem grant recusado",opt,async()=>assert.equal((await api("/api/ext/satisfaction/surveys",{method:"POST",body:config({target_identity_id:randomUUID()})})).status,400));
test("EXT-06 metodologia NPS exige 0-10",opt,async()=>assert.equal((await api("/api/ext/satisfaction/surveys",{method:"POST",body:config({methodology:"nps",scale_min:1,scale_max:5})})).status,400));
test("EXT-06 metodologia CSAT exige 1-5",opt,async()=>assert.equal((await api("/api/ext/satisfaction/surveys",{method:"POST",body:config({methodology:"csat",scale_min:0,scale_max:10})})).status,400));
test("EXT-06 genérica não vira NPS/CSAT",opt,async()=>{const s=await create();assert.equal(s.methodology,"generica")});
test("EXT-06 UI staff real",opt,async()=>{const r=await fetch(`${base}/admin/satisfacao`),t=await r.text();assert.equal(r.status,200);assert.match(t,/Satisfação|satisfação/)});
test("EXT-06 UI cliente real",opt,async()=>assert.equal((await fetch(`${base}/cliente/app/satisfacao`)).status,200));
test("EXT-06 cluster limpo não teve seed",opt,async()=>{const x=await pool.query(`SELECT count(*)::int n FROM cli_satisfaction_surveys WHERE created_by_identity IS NULL AND origin='ext06_canonica'`);assert.equal(x.rows[0].n,0)});
test("EXT-06 criação deriva autor e estado",opt,async()=>{const s=await create({created_by_identity:randomUUID(),status:"concluida"});assert.equal(s.created_by_identity,ti.id);assert.equal(s.status,"pendente")});
test("EXT-06 retry criação não duplica",opt,async()=>{const key=idem("retry"),a=await api("/api/ext/satisfaction/surveys",{method:"POST",body:config(),key}),b=await api("/api/ext/satisfaction/surveys",{method:"POST",body:config(),key});assert.equal(a.status,201);assert.equal(b.status,200);assert.equal(a.body.survey.id,b.body.survey.id)});
test("EXT-06 chave divergente 409",opt,async()=>{const key=idem("conflict");await api("/api/ext/satisfaction/surveys",{method:"POST",body:config(),key});assert.equal((await api("/api/ext/satisfaction/surveys",{method:"POST",body:config({purpose:"Finalidade divergente sintética."}),key})).status,409)});
test("EXT-06 nota fora da escala",opt,async()=>{const s=await create({methodology:"csat",scale_min:1,scale_max:5,follow_up_threshold:2});assert.equal((await answer(s.id,7)).status,400)});
test("EXT-06 cliente não responde pesquisa de outro destinatário",opt,async()=>{const s=await create();await pool.query(`UPDATE cli_satisfaction_surveys SET target_identity_id=$2 WHERE id=$1`,[s.id,randomUUID()]).catch(()=>{});/* trigger impede adulteração: use pesquisa histórica sintética */const other=randomUUID();await pool.query(`INSERT INTO auth_identities(id,kind,email,status) VALUES($1,'client',$2,'active')`,[other,`${other}@example.invalid`]);const q=await pool.query(`INSERT INTO cli_satisfaction_surveys(protocol,client_account_id,survey_type,target_identity_id,origin,purpose,methodology,methodology_source,scale_min,scale_max,classification_rule,follow_up_operator,follow_up_threshold,created_by_identity) VALUES($1,$2,'outro',$3,'ext06_canonica','Finalidade sintética','generica','Fonte sintética',0,10,'{}','lte',6,$4) RETURNING id`,[`SAT-CLI-20261003-${randomBytes(2).toString("hex").toUpperCase()}`,accountId,other,ti.id]);assert.equal((await answer(q.rows[0].id)).status,403)});
test("EXT-06 resposta cria histórico imutável",opt,async()=>{const s=await create(),x=await answer(s.id,8);assert.equal(x.status,200,x.text);const r=await pool.query(`SELECT * FROM cli_satisfaction_responses WHERE survey_id=$1`,[s.id]);assert.equal(r.rowCount,1);await assert.rejects(pool.query(`UPDATE cli_satisfaction_responses SET score=1 WHERE survey_id=$1`,[s.id]),/immutable/)});
test("EXT-06 retry resposta não duplica",opt,async()=>{const s=await create(),key=idem("response"),a=await answer(s.id,8,{key}),b=await answer(s.id,8,{key});assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(b.body.replayed,true);assert.equal((await pool.query(`SELECT count(*)::int n FROM cli_satisfaction_responses WHERE survey_id=$1`,[s.id])).rows[0].n,1)});
test("EXT-06 concorrência produz uma resposta",opt,async()=>{const s=await create(),key=idem("race"),rs=await Promise.all([answer(s.id,8,{key}),answer(s.id,8,{key})]);assert.deepEqual(rs.map(x=>x.status).sort(),[200,200]);assert.equal((await pool.query(`SELECT count(*)::int n FROM cli_satisfaction_responses WHERE survey_id=$1`,[s.id])).rows[0].n,1)});
test("EXT-06 sem responsável fica fail-closed",opt,async()=>{const s=await create(),x=await answer(s.id,2);assert.equal(x.status,200);const q=await pool.query(`SELECT action_plan_pending_reason,status FROM cli_satisfaction_surveys WHERE id=$1`,[s.id]);assert.match(q.rows[0].action_plan_pending_reason,/pendente/);assert.equal((await pool.query(`SELECT count(*)::int n FROM cli_satisfaction_action_plans WHERE survey_id=$1`,[s.id])).rows[0].n,0)});
test("EXT-06 responsável canônico gera um único acompanhamento com regra/fatos",opt,async()=>{const company=randomUUID();await pool.query(`INSERT INTO crm_companies(id,display_name,type,status,responsible_id,responsible_name,created_by) VALUES($1,'Empresa sintética','client','active',$2,'Nome legado ignorado','ti')`,[company,ti.id]);await pool.query(`UPDATE client_accounts SET crm_company_id=$2 WHERE id=$1`,[accountId,company]);const s=await create(),x=await answer(s.id,2);assert.equal(x.status,200,x.text);const p=await pool.query(`SELECT * FROM cli_satisfaction_action_plans WHERE survey_id=$1`,[s.id]);assert.equal(p.rowCount,1);assert.equal(p.rows[0].responsible_identity_id,ti.id);assert.equal(p.rows[0].trigger_rule.observed,2)});
test("EXT-06 acompanhamento inicia e conclui com resultado",opt,async()=>{const s=await create(),x=await answer(s.id,2);assert.equal(x.status,200);const p=(await pool.query(`SELECT id FROM cli_satisfaction_action_plans WHERE survey_id=$1`,[s.id])).rows[0];assert.equal((await api(`/api/ext/satisfaction/plans/${p.id}/start`,{method:"POST",body:{note:"Início sintético registrado."}})).status,200);assert.equal((await api(`/api/ext/satisfaction/plans/${p.id}/complete`,{method:"POST",body:{result:"Resultado sintético da recuperação concluída."}})).status,200);assert.equal((await pool.query(`SELECT status FROM cli_satisfaction_surveys WHERE id=$1`,[s.id])).rows[0].status,"concluida")});
test("EXT-06 terminal não reabre silenciosamente",opt,async()=>{const p=(await pool.query(`SELECT id FROM cli_satisfaction_action_plans WHERE status='concluida' ORDER BY created_at DESC LIMIT 1`)).rows[0];assert.equal((await api(`/api/ext/satisfaction/plans/${p.id}/start`,{method:"POST",body:{note:"Tentativa de reabertura sintética."}})).status,409);await assert.rejects(pool.query(`UPDATE cli_satisfaction_action_plans SET status='aberta' WHERE id=$1`,[p.id]),/terminal|transition/)});
test("EXT-06 cancelamento exige justificativa e fica terminal",opt,async()=>{const s=await create(),x=await answer(s.id,2);assert.equal(x.status,200);const p=(await pool.query(`SELECT id FROM cli_satisfaction_action_plans WHERE survey_id=$1`,[s.id])).rows[0];assert.equal((await api(`/api/ext/satisfaction/plans/${p.id}/cancel`,{method:"POST",body:{justification:"curta"}})).status,400);assert.equal((await api(`/api/ext/satisfaction/plans/${p.id}/cancel`,{method:"POST",body:{justification:"Cancelamento sintético devidamente justificado."}})).status,200);assert.equal((await api(`/api/ext/satisfaction/plans/${p.id}/complete`,{method:"POST",body:{result:"Tentativa terminal com resultado sintético."}})).status,409)});
test("EXT-06 projeção cliente não expõe funcionário/fatos/risco/tarefa",opt,async()=>{const b=(await api(`/api/client/satisfaction-surveys?account=${accountId}`,{cookie:cookieClient})).body,raw=JSON.stringify(b);for(const word of ["responsible_identity","responsible_name","facts_json","renewal_risk","action_plan","audit"])assert.doesNotMatch(raw,new RegExp(word,"i"))});
test("EXT-06 agregado distingue ausência de zero e declara fonte",opt,async()=>{const b=(await api("/api/ext/satisfaction/surveys")).body;assert.equal(b.aggregate.source,"cli_satisfaction_responses");assert.equal(typeof b.aggregate.denominator,"number");assert.ok("absence" in b.aggregate)});
test("EXT-06 banco recusa sobrescrita da resposta",opt,async()=>{const s=await create(),x=await answer(s.id,8);assert.equal(x.status,200);await assert.rejects(pool.query(`UPDATE cli_satisfaction_surveys SET score=1 WHERE id=$1`,[s.id]),/immutable/)});
test("EXT-06 evento imutável",opt,async()=>{const s=await create(),e=await pool.query(`SELECT id FROM cli_satisfaction_events WHERE survey_id=$1`,[s.id]);await assert.rejects(pool.query(`DELETE FROM cli_satisfaction_events WHERE id=$1`,[e.rows[0].id]),/immutable/)});
test("EXT-06 legado items/401/403/410",opt,async()=>{const r=await api("/api/ext/satisfaction-surveys");assert.equal(r.status,200);assert.ok(Array.isArray(r.body.items));assert.equal((await api("/api/ext/satisfaction-surveys",{cookie:null})).status,401);assert.equal((await api("/api/ext/satisfaction-surveys",{cookie:cookieRh})).status,403);assert.equal((await api("/api/ext/satisfaction-surveys",{method:"POST",body:{}})).status,410)});
test("EXT-06 falha audit_log causa 503 e rollback",opt,async()=>{await pool.query(`CREATE FUNCTION qa_ext06_audit_fail() RETURNS TRIGGER AS $$ BEGIN IF NEW.action='ext_satisfaction_survey_create' THEN RAISE EXCEPTION 'audit fail'; END IF; RETURN NEW; END $$ LANGUAGE plpgsql`);await pool.query(`CREATE TRIGGER qa_ext06_audit_fail_trg BEFORE INSERT ON audit_log FOR EACH ROW EXECUTE FUNCTION qa_ext06_audit_fail()`);const key=idem("rollback");try{const r=await api("/api/ext/satisfaction/surveys",{method:"POST",body:config({purpose:"Rollback sintético auditável."}),key});assert.equal(r.status,503);assert.equal((await pool.query(`SELECT count(*)::int n FROM cli_satisfaction_events WHERE idempotency_key=$1`,[key])).rows[0].n,0)}finally{await pool.query(`DROP TRIGGER qa_ext06_audit_fail_trg ON audit_log`);await pool.query(`DROP FUNCTION qa_ext06_audit_fail()`)} });
