// EXT-05: servidor HTTP real + PostgreSQL real, somente dados sintéticos .invalid.
import test,{before,after} from "node:test";
import assert from "node:assert/strict";
import {spawn} from "node:child_process";
import {randomBytes,randomUUID} from "node:crypto";
import path from "node:path";
import pg from "pg";
import {hashPassword} from "../src/lib/client-auth-core.mjs";
const RUN=process.env.RUN_DATABASE_INTEGRATION==="1"&&process.env.DATABASE_URL,REQUIRE=process.env.QA_EXT05_REQUIRE_DB==="1",root=path.resolve(import.meta.dirname,"..");
test("EXT-05 gate exige banco real e não aceita skip silencioso",()=>{if(REQUIRE)assert.ok(RUN)});
let server,base,pool,ti,rh,scoped,accountA,accountB,cookieTi,cookieRh,cookieScoped;
const idem=tag=>`ext05-${tag}-${randomUUID()}`;
async function wait(){for(let i=0;i<150;i++){try{const r=await fetch(`${base}/api/admin/session`);if([200,401].includes(r.status))return}catch{}await new Promise(r=>setTimeout(r,400))}throw new Error("server_did_not_start")}
async function staff(role){const id=randomUUID(),email=`qa-ext05-${role}-${id.slice(0,8)}@example.invalid`,password="Senha-Sintetica-9!";await pool.query(`INSERT INTO auth_identities(id,kind,email,display_name,status) VALUES($1,'staff',$2,$3,'active')`,[id,email,`QA EXT05 ${role}`]);await pool.query(`INSERT INTO auth_credentials(identity_id,password_hash) VALUES($1,$2)`,[id,await hashPassword(password)]);await pool.query(`INSERT INTO auth_staff_profiles(identity_id,role,assigned_by) VALUES($1,$2,'admin_system')`,[id,role]);if(role==='ti')for(const permission of ['quality.read','quality.write'])await pool.query(`INSERT INTO auth_permissions(id,identity_id,permission,scope_type,granted_by,granted_by_role,reason) VALUES($1,$2,$3,'global',$2,'ti','QA EXT05 escopo global')`,[randomUUID(),id,permission]);return{id,email,password}}
async function login(s){const r=await fetch(`${base}/api/admin/session`,{method:"POST",headers:{"content-type":"application/json",origin:base},body:JSON.stringify({email:s.email,password:s.password})});assert.equal(r.status,200);return r.headers.getSetCookie().find(x=>x.startsWith("seg_admin_session=")).split(";")[0]}
const get=(url,cookie=cookieTi)=>fetch(`${base}${url}`,{headers:{accept:"application/json",...(cookie?{cookie}:{})}});
const post=(url,body={},options={})=>fetch(`${base}${url}`,{method:"POST",headers:{"content-type":"application/json",origin:options.origin===undefined?base:options.origin,...(options.cookie===undefined?{cookie:cookieTi}:options.cookie?{cookie:options.cookie}:{}),...(options.key===null?{}:{"idempotency-key":options.key||idem("post")})},body:JSON.stringify(body)});
async function data(r){const t=await r.text();let b;try{b=JSON.parse(t)}catch{b=null}return{r,b,t}}
async function create(tag="nc",over={}){const x=await data(await post("/api/ext/quality/nonconformities",{title:`Falha sintética ${tag}`,description:`Descrição sintética suficientemente longa para ${tag}.`,category:"processo",severity:"media",responsible_identity:ti.id,...over}));assert.equal(x.r.status,201,x.t);return x.b.nonconformity}
async function cause(id){return data(await post(`/api/ext/quality/nonconformities/${id}/causes`,{description:"Causa sintética analisada e registrada sem dado real.",declared_source:"análise interna sintética"}))}
async function action(id){const x=await data(await post(`/api/ext/quality/nonconformities/${id}/responsibles/${ti.id}/actions`,{action_type:"corretiva",description:"Ação corretiva sintética para eliminar a causa declarada.",responsible_identity:randomUUID(),nonconformity_id:randomUUID(),created_by_identity:randomUUID()}));assert.equal(x.r.status,201,x.t);return x.b.action}
async function transition(id,status){return data(await post(`/api/ext/quality/nonconformities/${id}/transition`,{status,reason:`Transição sintética justificada para ${status}.`}))}
async function verify(id,outcome="eficaz"){return data(await post(`/api/ext/quality/nonconformities/${id}/verifications`,{outcome,description:"Verificação sintética estruturada da eficácia da ação.",evidence_type:"referencia_documental",evidence_reference:`synthetic://ext05/${randomUUID()}`,evidence_source:"registro interno sintético"}))}
async function ready(tag="ready"){const n=await create(tag);assert.equal((await cause(n.id)).r.status,201);const a=await action(n.id);assert.equal((await data(await post(`/api/ext/quality/actions/${a.id}/complete`,{note:"Conclusão sintética registrada pela equipe."}))).r.status,200);for(const s of ["em_analise","em_acao_corretiva","verificacao"])assert.equal((await transition(n.id,s)).r.status,200);const v=await verify(n.id);assert.equal(v.r.status,201);return{n,a,v:v.b.verification}}
before(async()=>{if(!RUN)return;const port=3200+Math.floor(Math.random()*1200);base=`http://127.0.0.1:${port}`;server=spawn(process.execPath,["server.mjs","--dev"],{cwd:root,env:{...process.env,PORT:String(port),BIND_HOST:"127.0.0.1",NODE_ENV:"development",NEXT_DIST_DIR:".next/integration-ext05",SITE_ADMIN_SESSION_SECRET:randomUUID().repeat(2),CLIENT_MFA_ENCRYPTION_KEY:randomBytes(32).toString("base64url"),SITE_ADMIN_LEGACY_TOKENS:"",OLLAMA_ENABLED:"false",MAIL_HOST:"",NEXT_TELEMETRY_DISABLED:"1"},stdio:["ignore","pipe","pipe"]});let logs="";server.stdout.on("data",c=>logs+=c);server.stderr.on("data",c=>logs+=c);try{await wait()}catch(e){throw new Error(`${e.message}\n${logs.slice(-3000)}`)}pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:8});ti=await staff("ti");rh=await staff("rh");scoped=await staff("ti");accountA=randomUUID();accountB=randomUUID();await pool.query(`INSERT INTO client_accounts(id,display_name,created_by) VALUES($1,'QA Qualidade Conta A','ti'),($2,'QA Qualidade Conta B','ti')`,[accountA,accountB]);await pool.query(`UPDATE auth_permissions SET revoked_at=NOW(),revoked_by=$1,revoke_reason='QA troca para escopo A' WHERE identity_id=$1 AND permission IN ('quality.read','quality.write') AND revoked_at IS NULL`,[scoped.id]);for(const permission of ['quality.read','quality.write'])await pool.query(`INSERT INTO auth_permissions(id,identity_id,permission,scope_type,scope_id,granted_by,granted_by_role,reason) VALUES($1,$2,$3,'account',$4,$2,'ti','QA EXT05 somente conta A')`,[randomUUID(),scoped.id,permission,accountA]);cookieTi=await login(ti);cookieRh=await login(rh);cookieScoped=await login(scoped)});
after(async()=>{await pool?.end().catch(()=>{});if(server&&!server.killed){server.kill("SIGTERM");await new Promise(r=>setTimeout(r,300));server.kill("SIGKILL")}});
const opt={skip:!RUN};
test("EXT-05 HTTP: anônimo recebe 401",opt,async()=>assert.equal((await get("/api/ext/quality/nonconformities",null)).status,401));
test("EXT-05 HTTP: papel não autorizado recebe 403",opt,async()=>assert.equal((await get("/api/ext/quality/nonconformities",cookieRh)).status,403));
test("EXT-05 HTTP: mutação cross-origin recebe 403",opt,async()=>assert.equal((await post("/api/ext/quality/nonconformities",{}, {origin:"https://attacker.invalid"})).status,403));
test("EXT-05 HTTP: idempotency key é obrigatória",opt,async()=>assert.equal((await post("/api/ext/quality/nonconformities",{}, {key:null})).status,400));
test("EXT-05 UI: /admin/qualidade é rota real",opt,async()=>{const r=await fetch(`${base}/admin/qualidade`),t=await r.text();assert.equal(r.status,200);assert.match(t,/Qualidade|qualidade/)});
test("EXT-05 DB: cluster limpo não recebeu seed operacional",opt,async()=>{const r=await pool.query(`SELECT count(*)::int n FROM ext_quality_nonconformities WHERE created_by_identity IS NULL`);assert.equal(r.rows[0].n,0)});
test("EXT-05 HTTP: lista declara vazio/fonte/fronteira sem inventar upload",opt,async()=>{const b=await(await get("/api/ext/quality/nonconformities")).json();assert.equal(b.source,"ext_quality_nonconformities");assert.equal(b.boundary.upload,false)});
test("EXT-05 escopo: criação valida conta e grant A/B",opt,async()=>{const payload={title:"Falha escopada A",description:"Descrição sintética da não conformidade vinculada à conta A.",category:"processo",severity:"media",client_account_id:accountA};const ok=await data(await post("/api/ext/quality/nonconformities",payload,{cookie:cookieScoped}));assert.equal(ok.r.status,201,ok.t);assert.equal(ok.b.nonconformity.client_account_id,accountA);const denied=await post("/api/ext/quality/nonconformities",{...payload,title:"Falha escopada B",client_account_id:accountB},{cookie:cookieScoped});assert.equal(denied.status,403);const unscoped=await post("/api/ext/quality/nonconformities",{...payload,title:"Falha sem conta",client_account_id:""},{cookie:cookieScoped});assert.equal(unscoped.status,403)});
test("EXT-05 escopo: conta inexistente é conflito dentro da transação",opt,async()=>{const r=await post("/api/ext/quality/nonconformities",{title:"Falha conta ausente",description:"Descrição sintética para uma conta inexistente no cadastro.",category:"processo",client_account_id:randomUUID()});assert.equal(r.status,409)});
test("EXT-05 escopo: lista A não revela B nem registro sem conta",opt,async()=>{const a=await create("scope-list-a",{client_account_id:accountA}),b=await create("scope-list-b",{client_account_id:accountB}),none=await create("scope-list-none");const list=await(await get("/api/ext/quality/nonconformities",cookieScoped)).json();const ids=list.nonconformities.map(x=>x.id);assert.ok(ids.includes(a.id));assert.ok(!ids.includes(b.id));assert.ok(!ids.includes(none.id))});
test("EXT-05 escopo: detalhe e mutação B respondem 404 indistinguível",opt,async()=>{const b=await create("scope-hidden-b",{client_account_id:accountB});assert.equal((await get(`/api/ext/quality/nonconformities/${b.id}`,cookieScoped)).status,404);const r=await post(`/api/ext/quality/nonconformities/${b.id}/causes`,{description:"Causa sintética que não deve ser registrada fora do escopo.",declared_source:"QA isolamento"},{cookie:cookieScoped});assert.equal(r.status,404)});
test("EXT-05 escopo: reincidência herda conta imutável do predecessor",opt,async()=>{const a=await create("scope-recurrence-a",{client_account_id:accountA});const r=await data(await post(`/api/ext/quality/nonconformities/${a.id}/recurrences`,{title:"Reincidência escopada A",description:"Descrição sintética da reincidência vinculada à mesma conta.",category:"processo",severity:"alta",justification:"Repetição sintética explicitamente justificada no teste.",declared_criterion:"mesmo controle sintético",declared_source:"QA isolamento",client_account_id:accountB},{cookie:cookieScoped}));assert.equal(r.r.status,201,r.t);assert.equal(r.b.nonconformity.client_account_id,accountA)});
test("EXT-05 HTTP+DB: criação deriva autoria e ignora autoria/contador forjados",opt,async()=>{const forged=randomUUID(),n=await create("forged",{created_by_identity:forged,recurrence_count:999});const r=await pool.query(`SELECT created_by_identity,recurrence_count FROM ext_quality_nonconformities WHERE id=$1`,[n.id]);assert.equal(r.rows[0].created_by_identity,ti.id);assert.equal(r.rows[0].recurrence_count,0)});
test("EXT-05 HTTP: UUID inválido na URL é recusado",opt,async()=>assert.equal((await post("/api/ext/quality/nonconformities/not-uuid/causes",{})).status,404));
test("EXT-05 HTTP+DB: retry idêntico não duplica",opt,async()=>{const k=idem("retry"),body={title:"Falha retry sintética",description:"Descrição sintética longa para retry idempotente.",category:"processo",responsible_identity:ti.id};const a=await data(await post("/api/ext/quality/nonconformities",body,{key:k})),b=await data(await post("/api/ext/quality/nonconformities",body,{key:k}));assert.equal(a.r.status,201);assert.equal(b.r.status,200);assert.equal(a.b.nonconformity.id,b.b.nonconformity.id);const c=await pool.query(`SELECT count(*)::int n FROM ext_quality_events WHERE idempotency_key=$1`,[k]);assert.equal(c.rows[0].n,1)});
test("EXT-05 HTTP: mesma chave com fingerprint diferente recebe 409",opt,async()=>{const k=idem("conflict");await post("/api/ext/quality/nonconformities",{title:"Falha chave A",description:"Descrição sintética para chave divergente A.",category:"processo",responsible_identity:ti.id},{key:k});const r=await post("/api/ext/quality/nonconformities",{title:"Falha chave B",description:"Descrição sintética para chave divergente B.",category:"processo",responsible_identity:ti.id},{key:k});assert.equal(r.status,409)});
test("EXT-05 HTTP: salto arbitrário é recusado",opt,async()=>{const n=await create("jump");assert.equal((await transition(n.id,"verificacao")).r.status,409)});
test("EXT-05 HTTP: encerramento/reabertura exigem operações explícitas",opt,async()=>{const n=await create("explicit");assert.equal((await transition(n.id,"encerrada")).r.status,409);assert.equal((await transition(n.id,"reaberta")).r.status,409)});
test("EXT-05 HTTP+DB: causa tem vínculo/autoria/data e é imutável",opt,async()=>{const n=await create("cause");const x=await cause(n.id);assert.equal(x.r.status,201);assert.equal(x.b.cause.nonconformity_id,n.id);assert.equal(x.b.cause.registered_by_identity,ti.id);await assert.rejects(pool.query(`UPDATE ext_quality_causes SET description='descrição adulterada suficientemente longa' WHERE id=$1`,[x.b.cause.id]),/immutable/)});
test("EXT-05 HTTP+DB: ação deriva vínculo e usa responsável staff canônico",opt,async()=>{const n=await create("action-link"),a=await action(n.id);assert.equal(a.nonconformity_id,n.id);assert.equal(a.responsible_identity,ti.id);assert.equal(a.created_by_identity,ti.id)});
test("EXT-05 HTTP: prazo exige fonte e data-base quando declarado",opt,async()=>{const n=await create("deadline");const r=await post(`/api/ext/quality/nonconformities/${n.id}/responsibles/${ti.id}/actions`,{action_type:"corretiva",description:"Ação sintética com prazo incompleto deve falhar.",responsible_identity:ti.id,due_date:"2026-10-10"});assert.equal(r.status,400)});
test("EXT-05 HTTP+DB: conclusão usa autor e timestamp do servidor",opt,async()=>{const n=await create("complete"),a=await action(n.id),x=await data(await post(`/api/ext/quality/actions/${a.id}/complete`,{note:"Conclusão sintética explicitamente declarada."}));assert.equal(x.r.status,200);assert.equal(x.b.action.completed_by_identity,ti.id);assert.ok(x.b.action.completed_recorded_at)});
test("EXT-05 HTTP+DB: cancelamento exige justificativa e preserva terminal",opt,async()=>{const n=await create("cancel"),a=await action(n.id);assert.equal((await post(`/api/ext/quality/actions/${a.id}/cancel`,{justification:"curta"})).status,400);const x=await post(`/api/ext/quality/actions/${a.id}/cancel`,{justification:"Cancelamento sintético devidamente justificado."});assert.equal(x.status,200);assert.equal((await post(`/api/ext/quality/actions/${a.id}/complete`,{note:"Tentativa posterior sintética."})).status,409)});
test("EXT-05 HTTP+DB: verificação registra evidência declarada imutável",opt,async()=>{const n=await create("verification"),v=await verify(n.id);assert.equal(v.r.status,201);assert.equal(v.b.evidence_boundary.upload,false);await assert.rejects(pool.query(`DELETE FROM ext_quality_verifications WHERE id=$1`,[v.b.verification.id]),/immutable/)});
test("EXT-05 HTTP: fechamento sem causa identifica pré-condição",opt,async()=>{const n=await create("no-cause"),a=await action(n.id);await post(`/api/ext/quality/actions/${a.id}/complete`,{note:"Conclusão sintética da ação corretiva."});for(const s of ["em_analise","em_acao_corretiva","verificacao"])await transition(n.id,s);const v=await verify(n.id);const x=await data(await post(`/api/ext/quality/nonconformities/${n.id}/close`,{verification_id:v.b.verification.id,closure_note:"Tentativa sem causa registrada."}));assert.equal(x.r.status,409);assert.ok(x.b.missing.includes("cause"))});
test("EXT-05 HTTP: fechamento sem ação concluída identifica pré-condição",opt,async()=>{const n=await create("no-action");await cause(n.id);for(const s of ["em_analise","em_acao_corretiva","verificacao"])await transition(n.id,s);const v=await verify(n.id);const x=await data(await post(`/api/ext/quality/nonconformities/${n.id}/close`,{verification_id:v.b.verification.id,closure_note:"Tentativa sem ação concluída."}));assert.equal(x.r.status,409);assert.ok(x.b.missing.includes("completed_action"))});
test("EXT-05 HTTP: fechamento sem verificação eficaz identifica pré-condição",opt,async()=>{const n=await create("bad-verification");await cause(n.id);const a=await action(n.id);await post(`/api/ext/quality/actions/${a.id}/complete`,{note:"Ação sintética concluída para verificação."});for(const s of ["em_analise","em_acao_corretiva","verificacao"])await transition(n.id,s);const v=await verify(n.id,"ineficaz");const x=await data(await post(`/api/ext/quality/nonconformities/${n.id}/close`,{verification_id:v.b.verification.id,closure_note:"Tentativa com verificação ineficaz."}));assert.equal(x.r.status,409);assert.ok(x.b.missing.includes("effective_verification_evidence"))});
test("EXT-05 HTTP: pendência obrigatória bloqueia fechamento",opt,async()=>{const x=await ready("pending");await action(x.n.id);const r=await data(await post(`/api/ext/quality/nonconformities/${x.n.id}/close`,{verification_id:x.v.id,closure_note:"Tentativa com ação ainda pendente."}));assert.equal(r.r.status,409);assert.ok(r.b.missing.includes("pending_action"))});
test("EXT-05 HTTP+DB: fechamento válido grava registro imutável",opt,async()=>{const x=await ready("close"),r=await data(await post(`/api/ext/quality/nonconformities/${x.n.id}/close`,{verification_id:x.v.id,closure_note:"Encerramento sintético com evidência e responsável."}));assert.equal(r.r.status,200,r.t);assert.equal(r.b.nonconformity.status,"encerrada");await assert.rejects(pool.query(`DELETE FROM ext_quality_closures WHERE id=$1`,[r.b.closure.id]),/immutable/)});
test("EXT-05 DB: encerramento direto sem pré-condições é recusado",opt,async()=>{const n=await create("db-close");await assert.rejects(pool.query(`UPDATE ext_quality_nonconformities SET status='encerrada',closed_at=NOW(),closed_by_identity=$2 WHERE id=$1`,[n.id,ti.id]),/transition|prerequisites|constraint/)});
test("EXT-05 HTTP+DB: reabertura formal preserva fechamento histórico",opt,async()=>{const x=await ready("reopen");await post(`/api/ext/quality/nonconformities/${x.n.id}/close`,{verification_id:x.v.id,closure_note:"Encerramento antes da reabertura sintética."});const r=await data(await post(`/api/ext/quality/nonconformities/${x.n.id}/reopen`,{justification:"Nova evidência sintética exige reanálise formal."}));assert.equal(r.r.status,200,r.t);const c=await pool.query(`SELECT count(*)::int n FROM ext_quality_closures WHERE nonconformity_id=$1`,[x.n.id]);assert.equal(c.rows[0].n,1)});
test("EXT-05 DB: reabertura silenciosa é recusada",opt,async()=>{const x=await ready("db-reopen");await post(`/api/ext/quality/nonconformities/${x.n.id}/close`,{verification_id:x.v.id,closure_note:"Encerramento para prova de trava de banco."});await assert.rejects(pool.query(`UPDATE ext_quality_nonconformities SET status='reaberta',closed_at=NULL,closed_by_identity=NULL,closing_verification_id=NULL WHERE id=$1`,[x.n.id]),/reopening metadata|required|constraint/)});
test("EXT-05 HTTP+DB: reincidência é fato explícito e contador derivado",opt,async()=>{const n=await create("predecessor");const r=await data(await post(`/api/ext/quality/nonconformities/${n.id}/recurrences`,{title:"Falha reincidente sintética",description:"Nova ocorrência sintética vinculada explicitamente.",category:"processo",severity:"alta",responsible_identity:ti.id,justification:"Ocorrência repete critério declarado do predecessor.",declared_criterion:"mesmo controle interno declarado",declared_source:"análise sintética"}));assert.equal(r.r.status,201,r.t);const list=await(await get("/api/ext/quality/nonconformities")).json(),old=list.nonconformities.find(x=>x.id===n.id);assert.equal(old.recurrence_count_derived,1);assert.equal(old.recurrence_count,0)});
test("EXT-05 DB: evento é imutável",opt,async()=>{const n=await create("event");const e=await pool.query(`SELECT id FROM ext_quality_events WHERE nonconformity_id=$1 LIMIT 1`,[n.id]);await assert.rejects(pool.query(`DELETE FROM ext_quality_events WHERE id=$1`,[e.rows[0].id]),/immutable/)});
test("EXT-05 legado: items, 401, 403 e 410 após guardas",opt,async()=>{const read=await data(await get("/api/ext/quality-nonconformities"));assert.equal(read.r.status,200);assert.ok(Array.isArray(read.b.items));assert.equal((await get("/api/ext/quality-nonconformities",null)).status,401);assert.equal((await get("/api/ext/quality-nonconformities",cookieRh)).status,403);assert.equal((await post("/api/ext/quality-nonconformities",{})).status,410);assert.equal((await post("/api/ext/quality-nonconformities",{},{cookie:null})).status,401)});
test("EXT-05 legado ações: items e mutação 410",opt,async()=>{const b=await(await get("/api/ext/quality-actions")).json();assert.ok(Array.isArray(b.items));assert.equal((await post("/api/ext/quality-actions",{})).status,410)});
test("EXT-05 HTTP+DB: falha audit_log devolve 503 e rollback total",opt,async()=>{await pool.query(`CREATE OR REPLACE FUNCTION qa_ext05_reject_audit() RETURNS TRIGGER AS $$ BEGIN IF NEW.action='ext_quality_nonconformity_create' THEN RAISE EXCEPTION 'audit unavailable ext05 qa'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql`);await pool.query(`CREATE TRIGGER qa_ext05_reject_audit_trg BEFORE INSERT ON audit_log FOR EACH ROW EXECUTE FUNCTION qa_ext05_reject_audit()`);const title=`Falha rollback ${randomUUID().slice(0,8)}`;try{const r=await post("/api/ext/quality/nonconformities",{title,description:"Descrição sintética para rollback completo da auditoria.",category:"processo",responsible_identity:ti.id});assert.equal(r.status,503);const n=await pool.query(`SELECT count(*)::int n FROM ext_quality_nonconformities WHERE title=$1`,[title]);assert.equal(n.rows[0].n,0)}finally{await pool.query(`DROP TRIGGER qa_ext05_reject_audit_trg ON audit_log`);await pool.query(`DROP FUNCTION qa_ext05_reject_audit()`)} });
