import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {CLIENT_SURVEY_FIELDS,SATISFACTION_TRANSITIONS,createExtSatisfactionApi} from "../src/server/ext-satisfaction-api.mjs";
const id="11111111-1111-4111-8111-111111111111";
function res(){return{status:0,payload:null,writeHead(s){this.status=s},end(v){this.payload=JSON.parse(v)}}}
function req(method="GET",body){const bytes=body?[Buffer.from(JSON.stringify(body))]:[];return{method,url:"/api/ext/satisfaction/surveys",headers:{origin:"https://app.invalid",host:"app.invalid"},async *[Symbol.asyncIterator](){yield* bytes}}}
const pool={query:async()=>({rows:[]})};
test("EXT-06 promove CLI-11 e não cria terceira fonte",async()=>{const sql=await readFile(new URL("../db/migrations/152-ext06-satisfaction-journey.sql",import.meta.url),"utf8");assert.match(sql,/ALTER TABLE cli_satisfaction_surveys/);assert.match(sql,/LEGADO EXT-06/);assert.doesNotMatch(sql,/CREATE TABLE ext_satisfaction_surveys/)});
test("EXT-06 resposta e eventos são imutáveis no PostgreSQL",async()=>{const sql=await readFile(new URL("../db/migrations/152-ext06-satisfaction-journey.sql",import.meta.url),"utf8");for(const token of ["cli_satisfaction_responses","cli_satisfaction_events","satisfaction historical record is immutable","canonical satisfaction configuration is immutable","terminal satisfaction plan is immutable"])assert.match(sql,new RegExp(token,"i"))});
test("EXT-06 máquina de estados não reabre terminais",()=>{assert.deepEqual(SATISFACTION_TRANSITIONS.plan.concluida,[]);assert.deepEqual(SATISFACTION_TRANSITIONS.plan.cancelada,[]);assert.deepEqual(SATISFACTION_TRANSITIONS.survey.concluida,[])});
test("EXT-06 allowlist cliente exclui funcionário, fatos, risco, tarefa e auditoria",()=>{const joined=CLIENT_SURVEY_FIELDS.join(" ");for(const forbidden of ["responsible","identity_id","facts","risk","action_plan","audit"])assert.doesNotMatch(joined,new RegExp(forbidden,"i"))});
test("EXT-06 staff distingue 401 de 403",async()=>{let r=res();await createExtSatisfactionApi({pool,sameOrigin:()=>true,requireSession:async()=>null,requireClientSession:async()=>null}).handleList(req(),r);assert.equal(r.status,401);r=res();await createExtSatisfactionApi({pool,sameOrigin:()=>true,requireSession:async()=>({identityId:id,role:"rh"}),requireClientSession:async()=>null}).handleList(req(),r);assert.equal(r.status,403)});
test("EXT-06 cliente exige sessão antes de consultar banco",async()=>{let queried=false,r=res();await createExtSatisfactionApi({pool:{query:async()=>{queried=true;return{rows:[]}}},sameOrigin:()=>true,requireSession:async()=>null,requireClientSession:async()=>null}).handleClient({...req(),url:`/api/client/satisfaction-surveys?account=${id}`},r);assert.equal(r.status,401);assert.equal(queried,false)});
test("EXT-06 remove writer legado do ext-api e liga rotas reais",async()=>{const legacy=await readFile(new URL("../src/server/ext-api.mjs",import.meta.url),"utf8"),server=await readFile(new URL("../server.mjs",import.meta.url),"utf8");assert.doesNotMatch(legacy,/INSERT INTO ext_satisfaction_surveys/i);assert.match(server,/createExtSatisfactionApi/);assert.match(server,/\/api\/ext\/satisfaction\/surveys/);assert.match(server,/handleClient/)});
test("EXT-06 UIs declaram privacidade e preservam chave no retry",async()=>{const [staff,client]=await Promise.all([readFile(new URL("../src/app/admin/satisfacao/SatisfacaoWorkspace.tsx",import.meta.url),"utf8"),readFile(new URL("../src/app/cliente/app/satisfacao/page.tsx",import.meta.url),"utf8")]);assert.match(staff,/keys\.current\[op\]=key/);assert.match(staff,/sem expor funcionário/);assert.doesNotMatch(client,/renewal_risk|responsible_identity|facts_json|action_plan_pending_reason/)});
