import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import path from "node:path";
import {createExtEmergencyApi,readinessFromTests,validateEscalation} from "../src/server/ext-emergency-api.mjs";
const root=path.resolve(import.meta.dirname,"..");
const identity="11111111-1111-4111-8111-111111111111",channelId="22222222-2222-4222-8222-222222222222";
function req({method="GET",url="/api/ext/emergency/channels",body,headers={}}={}){const s=(async function*(){if(body!==undefined)yield Buffer.from(JSON.stringify(body));})();s.method=method;s.url=url;s.headers={origin:"https://seg.test",host:"seg.test","idempotency-key":"ext15-unit-key-001",...headers};return s;}
function response(){return{statusCode:200,body:"",writeHead(s){this.statusCode=s;},end(b){this.body+=b||"";},json(){return JSON.parse(this.body);}};}
function pool({permission=true,audit=true}={}){const statements=[];const client={async query(sql,params=[]){statements.push({sql,params});if(["BEGIN","COMMIT","ROLLBACK"].includes(sql)||sql.includes("pg_advisory"))return{rows:[]};if(sql.includes("FROM ext_emergency_events")&&sql.includes("FOR UPDATE"))return{rows:[]};if(sql.includes("INSERT INTO ext_emergency_channels"))return{rows:[{id:channelId,name:"Plantão interno",status:"rascunho",origin:"ext15_canonica"}]};if(sql.includes("INSERT INTO ext_emergency_events"))return{rows:[]};if(sql.includes("auth_access_audit")){if(!audit)throw Error("offline");return{rows:[]};}return{rows:[]};},release(){}};return{statements,async query(sql){if(sql.includes("FROM auth_permissions"))return{rows:permission?[{scope_type:"global",scope_id:null}]:[]};return{rows:[]};},async connect(){return client;}};}
const session=async()=>({identityId:identity,role:"admin"});
const payload={name:"Plantão interno de apoio",channel_type:"telefone",recipient_name:"Supervisor interno",recipient_contact:"ramal interno 101",availability:"Disponível conforme escala interna declarada 24x7.",purpose:"Receber e escalar ocorrências operacionais declaradas.",escalation_steps:[{responsible:"Gestor interno",contact:"ramal interno 102",wait_minutes:5}]};

test("EXT-15 migração 167 é aditiva, RBAC e trilhas são imutáveis",async()=>{const m=await readFile(path.join(root,"db/migrations/167-ext15-emergency-canonical-journey.sql"),"utf8");assert.match(m,/origin IN \('registro_legado','ext15_canonica'\)/);assert.match(m,/CREATE TABLE IF NOT EXISTS ext_emergency_events/);assert.match(m,/BEFORE UPDATE OR DELETE ON ext_emergency_tests/);assert.match(m,/emergency\.activate/);assert.doesNotMatch(m,/UPDATE ext_emergency_channels\s+SET origin/);});
test("EXT-15 escalonamento exige responsável, contato e espera explícitos",()=>{assert.deepEqual(validateEscalation(payload.escalation_steps),[{order:1,responsible:"Gestor interno",contact:"ramal interno 102",wait_minutes:5}]);assert.equal(validateEscalation([]),null);assert.equal(validateEscalation([{responsible:"x",contact:"y",wait_minutes:-1}]),null);});
test("EXT-15 prontidão requer recebimento e atendimento bem-sucedidos",()=>{assert.deepEqual(readinessFromTests([{test_kind:"recebimento",is_success:true}]),{receiving_ok:true,attendance_ok:false,ready:false});assert.equal(readinessFromTests([{test_kind:"recebimento",is_success:true},{test_kind:"atendimento",is_success:true}]).ready,true);assert.equal(readinessFromTests([{test_kind:"recebimento",is_success:true},{test_kind:"atendimento",is_success:false}]).ready,false);});
test("EXT-15 anônimo e permissão ausente falham fechados",async()=>{let p=pool(),api=createExtEmergencyApi({pool:p,sameOrigin:()=>true,requireSession:async()=>null}),res=response();await api.handle(req({method:"POST",body:payload}),res);assert.equal(res.statusCode,401);p=pool({permission:false});api=createExtEmergencyApi({pool:p,sameOrigin:()=>true,requireSession:session});res=response();await api.handle(req({method:"POST",body:payload}),res);assert.equal(res.statusCode,403);});
test("EXT-15 criação exige chave, usa lock, fingerprint, evento e auditoria",async()=>{const p=pool(),api=createExtEmergencyApi({pool:p,sameOrigin:()=>true,requireSession:session});let res=response();await api.handle(req({method:"POST",headers:{"idempotency-key":""},body:payload}),res);assert.equal(res.statusCode,400);res=response();await api.handle(req({method:"POST",body:payload}),res);assert.equal(res.statusCode,201);const sql=p.statements.map(x=>x.sql).join("\n");assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/request_fingerprint/);assert.match(sql,/ext_emergency_events/);assert.match(sql,/auth_access_audit/);});
test("EXT-15 tipos e escalonamento inventados são recusados",async()=>{const api=createExtEmergencyApi({pool:pool(),sameOrigin:()=>true,requireSession:session});let res=response();await api.handle(req({method:"POST",body:{...payload,channel_type:"email"}}),res);assert.equal(res.json().error,"invalid_channel_type");res=response();await api.handle(req({method:"POST",body:{...payload,escalation_steps:[]}}),res);assert.equal(res.json().error,"invalid_escalation_steps");});
test("EXT-15 same-origin é obrigatório em mutações",async()=>{const api=createExtEmergencyApi({pool:pool(),sameOrigin:()=>false,requireSession:session}),res=response();await api.handle(req({method:"POST",body:payload}),res);assert.equal(res.statusCode,403);assert.equal(res.json().error,"origin_forbidden");});
test("EXT-15 falha de auditoria reverte e responde 503",async()=>{const p=pool({audit:false}),api=createExtEmergencyApi({pool:p,sameOrigin:()=>true,requireSession:session}),res=response();await api.handle(req({method:"POST",body:payload}),res);assert.equal(res.statusCode,503);assert.ok(p.statements.map(x=>x.sql).includes("ROLLBACK"));assert.equal(p.statements.map(x=>x.sql).includes("COMMIT"),false);});
test("EXT-15 escrita legada retorna 410 depois das guardas",async()=>{const api=createExtEmergencyApi({pool:pool(),sameOrigin:()=>true,requireSession:session}),res=response();await api.handleLegacy(req({method:"POST",url:"/api/ext/emergency-channels",body:payload}),res);assert.equal(res.statusCode,410);assert.equal(res.json().canonical,"/api/ext/emergency/channels");});
test("EXT-15 servidor registra API canônica e aposenta handlers legados",async()=>{const s=await readFile(path.join(root,"server.mjs"),"utf8");assert.match(s,/createExtEmergencyApi/);assert.match(s,/pathname\.startsWith\("\/api\/ext\/emergency\/"\)/);assert.match(s,/extEmergencyApi\.handleLegacy/);assert.doesNotMatch(s,/extReportingApi\.handleEmergencyChannels/);assert.doesNotMatch(s,/extReportingApi\.handleEmergencyTests/);});
test("EXT-15 UI é protegida e declara limite de prova",async()=>{const page=await readFile(path.join(root,"src/app/admin/emergencial/page.tsx"),"utf8"),ui=await readFile(path.join(root,"src/app/admin/emergencial/EmergencyWorkspace.tsx"),"utf8");assert.match(page,/AdminGate/);assert.match(ui,/não usa handlers legados como cobertura/);assert.match(ui,/não envia telefonema/);assert.match(ui,/registro interno declarado/);assert.match(ui,/Idempotency-Key/);});
