// EXT-15 / F11 — PostgreSQL descartável + HTTP real + sessões staff.
import test,{before,after} from "node:test";
import assert from "node:assert/strict";
import {spawn} from "node:child_process";
import {randomBytes,randomUUID} from "node:crypto";
import path from "node:path";
import pg from "pg";
import {hashPassword} from "../src/lib/client-auth-core.mjs";
const RUN=process.env.RUN_DATABASE_INTEGRATION==="1"&&process.env.DATABASE_URL,REQUIRE=process.env.QA_EXT15_REQUIRE_DB==="1",root=path.resolve(import.meta.dirname,"..");
const uuid=()=>randomUUID(),idem=n=>`ext15-${n}-${uuid()}`,wait=ms=>new Promise(r=>setTimeout(r,ms));
const fetchTimeout=(url,init={})=>fetch(url,{...init,signal:AbortSignal.timeout(init.method&&init.method!=="GET"?60000:30000)});
let server,base,pool,logs="",admin,rh,cookieAdmin,cookieRh,channel;
async function staff(role){const id=uuid(),email=`ext15-${role}-${id.slice(0,8)}@example.invalid`,password="Senha-Sintetica-9!";await pool.query("INSERT INTO auth_identities (id,kind,email,display_name,status) VALUES ($1,'staff',$2,$3,'active')",[id,email,`QA EXT15 ${role}`]);await pool.query("INSERT INTO auth_credentials (identity_id,password_hash) VALUES ($1,$2)",[id,await hashPassword(password)]);await pool.query("INSERT INTO auth_staff_profiles (identity_id,role,assigned_by) VALUES ($1,$2,'admin_system')",[id,role]);return{id,email,password,role};}
async function grant(id,permission){await pool.query("INSERT INTO auth_permissions (id,identity_id,permission,scope_type,granted_by,granted_by_role,reason) VALUES ($1,$2,$3,'global',$2,'admin','QA EXT15') ON CONFLICT DO NOTHING",[uuid(),id,permission]);}
async function login(s){const r=await fetchTimeout(`${base}/api/admin/session`,{method:"POST",headers:{"content-type":"application/json",origin:base},body:JSON.stringify({email:s.email,password:s.password})});assert.equal(r.status,200);const value=r.headers.getSetCookie().find(x=>x.startsWith("seg_admin_session="));assert.ok(value);return value.split(";")[0];}
async function api(url,{method="GET",cookie=cookieAdmin,body,key,origin=base}={}){const headers={accept:"application/json",origin,...(cookie?{cookie}:{}),...(method!=="GET"?{"idempotency-key":key===null?"":key||idem("request")}:{})};if(body!==undefined)headers["content-type"]="application/json";const r=await fetchTimeout(base+url,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),text=await r.text();let parsed;try{parsed=JSON.parse(text);}catch{parsed={raw:text.slice(0,300)}}return{status:r.status,body:parsed};}
const payload=(overrides={})=>({name:"Plantão interno de apoio",channel_type:"telefone",recipient_name:"Supervisor interno",recipient_contact:"ramal interno 101",availability:"Disponibilidade declarada 24 horas por dia, sujeita a conferência humana.",purpose:"Apoio interno em ocorrências operacionais com escalonamento humano.",escalation_steps:[{responsible:"Gestor interno",contact:"ramal interno 102",wait_minutes:5}],...overrides});
const testPayload=(kind,success=true)=>({test_kind:kind,result:`Resultado interno declarado para ${kind}: ${success?"bem-sucedido":"falho"}.`,evidence_note:`Conferência manual interna do teste de ${kind}; nenhum envio automatizado.`,tested_by_name:"Operador QA interno",is_success:success});
before(async()=>{if(!RUN)return;pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:14});const port=4900+Math.floor(Math.random()*300);base=`http://127.0.0.1:${port}`;server=spawn(process.execPath,["server.mjs","--dev"],{cwd:root,env:{...process.env,PORT:String(port),BIND_HOST:"127.0.0.1",NODE_ENV:"development",NEXT_DIST_DIR:".next/integration-ext15",SITE_ADMIN_SESSION_SECRET:randomUUID().repeat(2),CLIENT_MFA_ENCRYPTION_KEY:randomBytes(32).toString("base64url"),SITE_ADMIN_LEGACY_TOKENS:"",OLLAMA_ENABLED:"false",MAIL_HOST:"",NEXT_TELEMETRY_DISABLED:"1"},stdio:["ignore","pipe","pipe"]});server.stdout.on("data",c=>logs+=c);server.stderr.on("data",c=>logs+=c);for(let i=0;i<240;i++){try{const r=await fetchTimeout(`${base}/api/admin/session`);if([200,401].includes(r.status))break;}catch{}if(i===239)throw Error(`server_did_not_start\n${logs.slice(-4000)}`);await wait(400);}admin=await staff("admin");rh=await staff("rh");for(const p of ["emergency.read","emergency.write","emergency.test","emergency.activate"])await grant(admin.id,p);cookieAdmin=await login(admin);cookieRh=await login(rh);});
after(async()=>{await pool?.end().catch(()=>{});if(server&&!server.killed){server.kill("SIGTERM");await wait(500);server.kill("SIGKILL");}if(logs.trim())console.error(`SERVER_LOGS_TAIL_BEGIN\n${logs.slice(-5000)}\nSERVER_LOGS_TAIL_END`);});
const opt={skip:!RUN};
test("EXT-15 gate exige PostgreSQL real",()=>{if(REQUIRE)assert.ok(RUN);});
test("EXT-15 cluster inicia sem registros canônicos",opt,async()=>{assert.deepEqual((await pool.query("SELECT (SELECT count(*)::int FROM ext_emergency_channels WHERE origin='ext15_canonica') channels,(SELECT count(*)::int FROM ext_emergency_events) events")).rows[0],{channels:0,events:0});const r=await api("/api/ext/emergency/channels");assert.equal(r.status,200);assert.deepEqual(r.body.items,[]);});
test("EXT-15 RBAC nega anônimo, cookie inválido e staff sem grant",opt,async()=>{assert.equal((await api("/api/ext/emergency/channels",{cookie:null})).status,401);assert.equal((await api("/api/ext/emergency/channels",{cookie:"seg_admin_session=invalid"})).status,401);assert.equal((await api("/api/ext/emergency/channels",{cookie:cookieRh})).status,403);assert.equal((await api("/api/ext/emergency/channels",{method:"POST",cookie:cookieRh,body:payload()})).status,403);});
test("EXT-15 exige same-origin e chave idempotente",opt,async()=>{assert.equal((await api("/api/ext/emergency/channels",{method:"POST",body:payload(),origin:"https://attacker.invalid"})).status,403);assert.equal((await api("/api/ext/emergency/channels",{method:"POST",body:payload(),key:null})).status,400);});
test("EXT-15 valida tipo real da 087, destinatário e escalonamento",opt,async()=>{let r=await api("/api/ext/emergency/channels",{method:"POST",body:payload({channel_type:"email"})});assert.equal(r.body.error,"invalid_channel_type");r=await api("/api/ext/emergency/channels",{method:"POST",body:payload({recipient_name:"x"})});assert.equal(r.body.error,"invalid_recipient_name");r=await api("/api/ext/emergency/channels",{method:"POST",body:payload({escalation_steps:[]})});assert.equal(r.body.error,"invalid_escalation_steps");});
test("EXT-15 cria configuração canônica por HTTP",opt,async()=>{const r=await api("/api/ext/emergency/channels",{method:"POST",body:payload()});assert.equal(r.status,201);channel=r.body.channel;assert.equal(channel.origin,"ext15_canonica");assert.equal(channel.status,"rascunho");assert.equal(channel.created_by_identity,admin.id);assert.equal(channel.is_tested,false);assert.equal(channel.escalation_steps[0].responsible,"Gestor interno");});
test("EXT-15 replay idêntico converge e payload divergente conflita",opt,async()=>{const key=idem("replay"),p=payload({name:"Canal para replay idempotente"});const first=await api("/api/ext/emergency/channels",{method:"POST",key,body:p}),replay=await api("/api/ext/emergency/channels",{method:"POST",key,body:p}),conflict=await api("/api/ext/emergency/channels",{method:"POST",key,body:{...p,name:"Canal divergente"}});assert.equal(first.status,201);assert.equal(replay.status,200);assert.equal(replay.body.replayed,true);assert.equal(conflict.status,409);assert.equal((await pool.query("SELECT count(*)::int n FROM ext_emergency_channels WHERE idempotency_key=$1",[key])).rows[0].n,1);});
test("EXT-15 concorrência da mesma chave cria um único canal",opt,async()=>{const key=idem("concurrent"),p=payload({name:"Canal concorrente interno"});const results=await Promise.all(Array.from({length:5},()=>api("/api/ext/emergency/channels",{method:"POST",key,body:p})));assert.equal(results.filter(x=>x.status===201).length,1);assert.equal(results.filter(x=>x.status===200&&x.body.replayed).length,4);assert.equal((await pool.query("SELECT count(*)::int n FROM ext_emergency_channels WHERE idempotency_key=$1",[key])).rows[0].n,1);});
test("EXT-15 não ativa antes dos dois testes bem-sucedidos",opt,async()=>{let r=await api(`/api/ext/emergency/channels/${channel.id}/transition`,{method:"POST",body:{status:"em_teste"}});assert.equal(r.status,200);r=await api(`/api/ext/emergency/channels/${channel.id}/transition`,{method:"POST",body:{status:"ativo",note:"Tentativa humana ainda sem os dois testes."}});assert.equal(r.status,409);assert.equal(r.body.error,"successful_tests_required");});
test("EXT-15 teste exige resultado booleano explícito e estado em_teste",opt,async()=>{let r=await api(`/api/ext/emergency/channels/${channel.id}/tests`,{method:"POST",body:{...testPayload("recebimento"),is_success:"sim"}});assert.equal(r.status,400);assert.equal(r.body.error,"explicit_test_result_required");const other=await api("/api/ext/emergency/channels",{method:"POST",body:payload({name:"Canal ainda em rascunho"})});r=await api(`/api/ext/emergency/channels/${other.body.channel.id}/tests`,{method:"POST",body:testPayload("recebimento")});assert.equal(r.status,409);assert.equal(r.body.error,"channel_not_in_test");});
test("EXT-15 recebimento sozinho não deixa canal pronto",opt,async()=>{const r=await api(`/api/ext/emergency/channels/${channel.id}/tests`,{method:"POST",body:testPayload("recebimento")});assert.equal(r.status,201);assert.deepEqual(r.body.readiness,{receiving_ok:true,attendance_ok:false,ready:false});assert.equal(r.body.status,"em_teste");});
test("EXT-15 teste de atendimento completa prontidão sem acionar canal",opt,async()=>{const r=await api(`/api/ext/emergency/channels/${channel.id}/tests`,{method:"POST",body:testPayload("atendimento")});assert.equal(r.status,201);assert.equal(r.body.readiness.ready,true);assert.equal(r.body.status,"testado");assert.match(r.body.note,/não é prova/);});
test("EXT-15 ativação humana ocorre apenas depois da prontidão",opt,async()=>{const r=await api(`/api/ext/emergency/channels/${channel.id}/transition`,{method:"POST",body:{status:"ativo",note:"Ativação humana após conferir recebimento e atendimento internos."}});assert.equal(r.status,200);assert.equal(r.body.channel.status,"ativo");assert.equal(r.body.channel.activated_by_identity,admin.id);assert.ok(r.body.channel.activated_at);assert.match(r.body.note,/não comprova disponibilidade externa/);});
test("EXT-15 detalhe expõe testes, eventos e prontidão rastreáveis",opt,async()=>{const r=await api(`/api/ext/emergency/channels/${channel.id}`);assert.equal(r.status,200);assert.equal(r.body.tests.length,2);assert.equal(r.body.readiness.ready,true);assert.ok(r.body.events.length>=5);assert.ok(r.body.events.every(e=>e.created_by_identity===admin.id));});
test("EXT-15 eventos e testes são append-only no PostgreSQL",opt,async()=>{await assert.rejects(pool.query("UPDATE ext_emergency_events SET summary='alteração proibida no histórico' WHERE channel_id=$1",[channel.id]),/immutable/);await assert.rejects(pool.query("DELETE FROM ext_emergency_tests WHERE channel_id=$1",[channel.id]),/immutable/);});
test("EXT-15 auditoria indisponível reverte toda a criação",opt,async()=>{await pool.query("CREATE OR REPLACE FUNCTION qa_ext15_fail_audit() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'qa audit offline'; END $$ LANGUAGE plpgsql");await pool.query("CREATE TRIGGER qa_ext15_fail_audit_trg BEFORE INSERT ON auth_access_audit FOR EACH ROW EXECUTE FUNCTION qa_ext15_fail_audit()");const key=idem("audit-fail"),r=await api("/api/ext/emergency/channels",{method:"POST",key,body:payload({name:"Canal que deve reverter"})});assert.equal(r.status,503);assert.equal(r.body.error,"audit_unavailable");assert.equal((await pool.query("SELECT count(*)::int n FROM ext_emergency_channels WHERE idempotency_key=$1",[key])).rows[0].n,0);await pool.query("DROP TRIGGER qa_ext15_fail_audit_trg ON auth_access_audit");await pool.query("DROP FUNCTION qa_ext15_fail_audit()");});
test("EXT-15 escrita legada é 410 depois das guardas",opt,async()=>{let r=await api("/api/ext/emergency-channels",{method:"POST",body:payload()});assert.equal(r.status,410);assert.equal(r.body.canonical,"/api/ext/emergency/channels");r=await api("/api/ext/emergency-tests",{method:"POST",body:{}});assert.equal(r.status,410);});
test("EXT-15 página protegida é servida e declara fronteira honesta",opt,async()=>{const r=await fetchTimeout(`${base}/admin/emergencial`,{headers:{cookie:cookieAdmin}});assert.equal(r.status,200);const html=await r.text();assert.match(html,/Apoio emergencial/);assert.doesNotMatch(html,/TypeError|Internal Server Error/);});
