// UX-07 / EXT-02 — PostgreSQL, HTTP e Chromium reais. Massa EXT-02 nasce pela
// API canônica. SQL provisiona somente sessão staff; não simula veredito da
// família. Contrato/OS de outras famílias são provisionamento mínimo quando
// o gate herdado exercita grants. Datas funcionais usam CURRENT_DATE do banco.
import test,{before,after}from'node:test';import assert from'node:assert/strict';import{spawn}from'node:child_process';import{randomUUID,randomBytes}from'node:crypto';import{createServer}from'node:net';import path from'node:path';import pg from'pg';import{chromium as pw}from'playwright';import packaged from'@sparticuz/chromium';import{provisionStaff,STAFF_TEST_PASSWORD}from'./helpers/staff-login.mjs';
const RUN=process.env.RUN_DATABASE_INTEGRATION==='1'&&process.env.DATABASE_URL;const root=path.resolve(import.meta.dirname,'..');let server,baseUrl,pool,ti,rh,cookie,party;
const mark=x=>console.log(`UX_THIRD_PARTY_SETUP: ${x}`);async function port(){return new Promise((ok,no)=>{const s=createServer();s.once('error',no);s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>ok(p))})})}async function wait(){for(let i=0;i<450;i++){try{const r=await fetch(`${baseUrl}/api/admin/session`);if([200,401].includes(r.status))return}catch{}await new Promise(r=>setTimeout(r,400))}throw Error('server_did_not_start')}
async function login(user){const r=await fetch(`${baseUrl}/api/admin/session`,{method:'POST',headers:{'content-type':'application/json',origin:baseUrl},body:JSON.stringify({email:user.email,password:STAFF_TEST_PASSWORD})});assert.equal(r.status,200);return r.headers.getSetCookie().find(x=>x.startsWith('seg_admin_session=')).split(';')[0]}
async function api(url,{method='GET',body,cookie:ck=cookie,key}={}){const r=await fetch(baseUrl+url,{method,headers:{accept:'application/json',...(body?{'content-type':'application/json'}:{}),...(method!=='GET'?{origin:baseUrl,'idempotency-key':key||`ext02-ux-${randomUUID()}`} :{}),...(ck?{cookie:ck}:{})},body:body?JSON.stringify(body):undefined});const text=await r.text();let data;try{data=JSON.parse(text)}catch{}return{status:r.status,data,text}}
before(async()=>{if(!RUN)return;mark('iniciando servidor real');pool=new pg.Pool({connectionString:process.env.DATABASE_URL});const p=await port();baseUrl=`http://127.0.0.1:${p}`;server=spawn(process.execPath,['server.mjs','--dev'],{cwd:root,env:{...process.env,PORT:String(p),BIND_HOST:'127.0.0.1',NODE_ENV:'development',NEXT_DIST_DIR:'.next/integration-ux-third-party',SITE_ADMIN_SESSION_SECRET:randomUUID().repeat(2),CLIENT_MFA_ENCRYPTION_KEY:randomBytes(32).toString('base64url'),OLLAMA_ENABLED:'false',MAIL_HOST:'',NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});server.stdout.on('data',()=>{});server.stderr.on('data',()=>{});await wait();mark('provisionando sessões sintéticas');ti=await provisionStaff(pool,{role:'ti',tag:'ux-third-ti'});rh=await provisionStaff(pool,{role:'rh',tag:'ux-third-rh'});cookie=await login(ti);const now=await pool.query('SELECT CURRENT_DATE::text AS today');assert.match(now.rows[0].today,/^\d{4}-\d{2}-\d{2}$/);mark('criando massa pela API canônica');const made=await api('/api/ext/third-party/parties',{method:'POST',body:{name:'Terceiro Sintético UX',category:'prestador',responsible_name:'Pessoa Sintética'}});assert.equal(made.status,201,made.text);party=made.data.third_party});after(async()=>{await pool?.end();if(server){server.kill('SIGTERM');await new Promise(r=>setTimeout(r,300));server.kill('SIGKILL')}});
test('sessão obrigatória e 401/403 reais',async t=>{if(!RUN)return t.skip();assert.equal((await api('/api/ext/third-party/parties',{cookie:null})).status,401);const rhCookie=await login(rh);const denied=await api('/api/ext/third-party/parties',{cookie:rhCookie});assert.equal(denied.status,403);assert.equal(denied.data.error,'forbidden_role')});
test('Chromium: conteúdo carregado, português, teclado, falha browser-only e 390px',{timeout:120000},async t=>{if(!RUN)return t.skip();const browser=await pw.launch({executablePath:await packaged.executablePath(),args:packaged.args.filter(x=>x!=='--disable-web-security'),headless:true});try{const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();await context.addCookies([{name:'seg_admin_session',value:cookie.split('=')[1],url:baseUrl}]);await page.goto(`${baseUrl}/admin/terceiros`);await page.getByRole('heading',{name:'Terceiros, acessos e documentos'}).waitFor();await page.getByText('Terceiro Sintético UX').waitFor();assert.equal(await page.getByText('Ativo',{exact:true}).count(),1);const tabs=page.getByRole('tab');await tabs.first().focus();await page.keyboard.press('ArrowRight');assert.equal(await tabs.nth(1).getAttribute('aria-selected'),'true');await page.keyboard.press('End');assert.equal(await tabs.last().getAttribute('aria-selected'),'true');const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);assert.ok(overflow<=1,`overflow ${overflow}`);await context.close();const failed=await browser.newContext();await failed.addCookies([{name:'seg_admin_session',value:cookie.split('=')[1],url:baseUrl}]);await failed.addInitScript(()=>{const real=window.fetch.bind(window);window.fetch=(input,init)=>String(input).includes('/api/ext/third-party/parties')?Promise.reject(new TypeError('falha sintética somente no browser')):real(input,init)});const p2=await failed.newPage();await p2.goto(`${baseUrl}/admin/terceiros`);await p2.getByText('Servidor não respondeu').waitFor();assert.equal(await p2.getByTestId('third-party-table').count(),0);assert.equal((await p2.locator('body').textContent()).includes('Nenhum terceiro registrado'),false)}finally{await Promise.race([browser.close(),new Promise(resolve=>setTimeout(resolve,5000))])}});
