"use client";
import { useCallback, useEffect, useState } from "react";
import { jsonInit } from "./admin-shared";
import styles from "./AdminClientes.module.css";
type Item={id:string;email:string;display_name?:string;status:string;requested_at:string;expires_at?:string};
export default function RecoveriesSection(){const [items,setItems]=useState<Item[]>([]),[error,setError]=useState(""),[reason,setReason]=useState<Record<string,string>>({}),[method,setMethod]=useState<Record<string,string>>({}),[link,setLink]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/admin/client-recoveries");const d=await r.json().catch(()=>({}));if(r.ok)setItems(d.items||[]);else setError(d.error||"Falha ao consultar recuperações.")},[]);useEffect(()=>{void load()},[load]);
 async function action(id:string,kind:"authorize"|"revoke"){setError("");setLink("");const r=await fetch(`/api/admin/client-recoveries/${id}/${kind}`,jsonInit("POST",kind==="authorize"?{method:method[id]||"",reason:reason[id]||""}:{}));const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||"Operação recusada.");return}if(d.resetUrl)setLink(d.resetUrl);await load()}
 return <section className={styles.card} aria-labelledby="recovery-title"><h2 id="recovery-title">Recuperação local de acesso — sem SMTP</h2><p>Somente TI individual com permissão pode autorizar. Confirme a identidade presencialmente ou retornando por contato conhecido. O link aparece uma única vez, vence em 15 minutos e deve ser entregue por canal restrito; nenhum e-mail é enviado.</p>{error&&<p role="alert">{error}</p>}{link&&<div role="status"><strong>Link exibido uma única vez:</strong><input aria-label="Link temporário de recuperação" readOnly value={link} style={{width:"100%"}}/></div>}{items.length===0?<p>Nenhum pedido pendente.</p>:items.map(x=><article key={x.id} style={{borderTop:"1px solid #ddd",paddingTop:12,marginTop:12}}><strong>{x.display_name||x.email}</strong><div>{x.email} · {x.status} · {new Date(x.requested_at).toLocaleString("pt-BR")}</div>{x.status==="pendente"&&<><select aria-label={`Método ${x.email}`} value={method[x.id]||""} onChange={e=>setMethod(v=>({...v,[x.id]:e.target.value}))}><option value="">Selecione a verificação</option><option value="presencial">Presencial</option><option value="retorno_contato_conhecido">Retorno por contato conhecido</option></select><textarea aria-label={`Justificativa ${x.email}`} minLength={30} maxLength={500} placeholder="Evidência e justificativa (30–500 caracteres)" value={reason[x.id]||""} onChange={e=>setReason(v=>({...v,[x.id]:e.target.value}))}/><button onClick={()=>action(x.id,"authorize")}>Autorizar e gerar link</button></>}<button onClick={()=>action(x.id,"revoke")}>Revogar pedido</button></article>)}</section>}
