"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CircleAlert, FileSearch } from "lucide-react";
import styles from "./AccessRequests.module.css";

type Mode={mode:string;is_active:boolean;requires_approval:boolean;auto_release_contracts:boolean};
type AccessRequest={id:string;protocol:string;mode:string;requested_email:string;requested_name:string;client_account_id:string;document_ref:string;status:string;verified_link:boolean;decision_reason?:string};

export default function PortalAccessRequestsPage(){
  const [modes,setModes]=useState<Mode[]>([]); const [requests,setRequests]=useState<AccessRequest[]>([]);
  const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setMessage("");try{const [m,r]=await Promise.all([fetch("/api/cli/portal-mode-configs"),fetch("/api/hr/cli-portal-access-requests")]);if(!m.ok||!r.ok)throw new Error();setModes((await m.json()).modes||[]);setRequests((await r.json()).requests||[]);}catch{setMessage("Não foi possível carregar a configuração e a fila.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function saveMode(mode:Mode){const reason=window.prompt("Motivo da alteração (10 a 500 caracteres):","")?.trim();if(!reason)return;const response=await fetch("/api/cli/portal-mode-configs",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...mode,reason})});const data=await response.json();setMessage(response.ok?"Configuração registrada com autoria e auditoria.":data.error==="autocadastro_never_releases_contracts"?"Autocadastro nunca pode liberar contratos sozinho.":"Alteração recusada.");if(response.ok)void load();}
  async function decide(item:AccessRequest,status:"aprovada"|"rejeitada"){const reason=window.prompt(status==="aprovada"?"Motivo da aprovação e da emissão do convite:":"Motivo da rejeição:","")?.trim();if(!reason)return;const response=await fetch("/api/hr/cli-portal-access-requests",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,status,reason})});const data=await response.json();setMessage(response.ok?(status==="aprovada"?`Convite canônico criado. URL manual: ${data.inviteUrl}`:"Rejeição registrada."):`Decisão recusada: ${data.error||"erro"}`);if(response.ok)void load();}
  return <main className={styles.page}><header className={styles.header}><Link href="/admin/portal" className={styles.back}><ArrowLeft size={15}/> Configuração do portal</Link><span className={styles.headerLabel}><FileSearch size={14}/> CLI-13 · ACESSOS</span></header><section className={styles.content}>
    <div className={styles.heading}><div><span className={styles.eyebrow}>JORNADA REAL · REVISÃO ADMIN/TI</span><h1>Modos e pedidos<br/><em>com decisão registrada.</em></h1><p>A aprovação emite somente o convite canônico. Conceder vínculo e escopo contratual continua sendo uma ação separada, explícita e motivada.</p></div></div>
    {message&&<div className={styles.notice} role="status"><CircleAlert size={18}/><p>{message}</p></div>}
    <section className={styles.requesterSection}><div><span className={styles.sectionLabel}>MODOS DE ENTRADA</span><h2>Configuração vigente</h2></div><div className={styles.requesterActions}>{modes.map((mode,index)=><div className={styles.requestForm} key={mode.mode}><strong>{mode.mode}</strong><label><input type="checkbox" checked={mode.is_active} onChange={e=>setModes(current=>current.map((x,i)=>i===index?{...x,is_active:e.target.checked}:x))}/> Ativo</label><label><input type="checkbox" checked={mode.requires_approval} onChange={e=>setModes(current=>current.map((x,i)=>i===index?{...x,requires_approval:e.target.checked}:x))}/> Exige aprovação</label><label><input type="checkbox" checked={mode.auto_release_contracts} disabled={mode.mode==="autocadastro"} onChange={e=>setModes(current=>current.map((x,i)=>i===index?{...x,auto_release_contracts:e.target.checked}:x))}/> Libera contratos automaticamente</label><button type="button" onClick={()=>void saveMode(mode)}>Salvar com motivo</button></div>)}</div></section>
    <section className={styles.queue}><div className={styles.queueHeader}><div><span className={styles.sectionLabel}>FILA REAL</span><h2>Solicitações</h2></div><button type="button" onClick={()=>void load()}>Atualizar</button></div>{loading?<p>Carregando…</p>:requests.length===0?<p className={styles.emptyState}>Nenhum pedido registrado.</p>:<div className={styles.demoRequestList}>{requests.map(item=><article className={styles.demoRequest} key={item.id}><strong>{item.protocol}</strong><span className={styles.demoRequestStatus}>{item.status}</span><p>{item.requested_name} · {item.requested_email}</p><p>Modo: {item.mode} · conta: {item.client_account_id}</p><p>Documento: {item.document_ref} · vínculo: {item.verified_link?"verificado no servidor":"não verificado"}</p>{item.status==="pendente"&&<div className={styles.decisionGrid}><button type="button" className={styles.decisionButton} onClick={()=>void decide(item,"aprovada")}>Aprovar e emitir convite</button><button type="button" className={styles.decisionButton} onClick={()=>void decide(item,"rejeitada")}>Rejeitar com motivo</button></div>}</article>)}</div>}</section>
  </section></main>;
}
