"use client";
import {FormEvent,useCallback,useEffect,useRef,useState} from "react";
type Item=Record<string,any>; const box:React.CSSProperties={background:"white",border:"1px solid #d1d5db",borderRadius:12,padding:16,marginBottom:16}; const input:React.CSSProperties={padding:8,border:"1px solid #9ca3af",borderRadius:6,minWidth:190};
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{error:t||r.statusText}}}
export default function ComplianceWorkspace(){
 const [obligations,setObligations]=useState<Item[]>([]),[docs,setDocs]=useState<Item[]>([]),[tasks,setTasks]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const keys=useRef<Record<string,string>>({});
 const [ob,setOb]=useState({obligation_type:"licenca",title:"",description:"",declared_source:"",applicability_scope:"",applicability_justification:"",validity_rule:"",responsible_identity:""});
 const [doc,setDoc]=useState({obligation_id:"",title:"",description:"",compliance_type:"licenca",issue_date:"",expiry_date:"",declared_reference:"",reference_source:""});
 const [renew,setRenew]=useState({document_id:"",issue_date:"",expiry_date:"",declared_reference:"",justification:""});
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [a,b,c]=await Promise.all([fetch("/api/ext/compliance/obligations"),fetch("/api/ext/compliance/documents"),fetch("/api/ext/compliance/tasks")]);const [x,y,z]=await Promise.all([read(a),read(b),read(c)]);if(!a.ok||!b.ok||!c.ok)throw Error(x.error||y.error||z.error);setObligations(x.items||[]);setDocs(y.items||[]);setTasks(z.items||[]);}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function mutate(name:string,url:string,value:unknown){const key=keys.current[name]||`ext07-${name}-${crypto.randomUUID()}`;keys.current[name]=key;setError("");try{const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json","idempotency-key":key},body:JSON.stringify(value)});const b=await read(r);if(!r.ok)throw Error(b.error||String(r.status));delete keys.current[name];return b}catch(e){setError(`${e instanceof Error?e.message:"Falha"}. Chave preservada para retry seguro.`);throw e}}
 async function createOb(e:FormEvent){e.preventDefault();try{await mutate("obligation","/api/ext/compliance/obligations",ob);setNotice("Obrigação aplicável registrada (declaração interna; não é validação jurídica).");await load()}catch{}}
 async function createDoc(e:FormEvent){e.preventDefault();try{await mutate("document","/api/ext/compliance/documents",{...doc,reference_type:"referencia_declarada"});setNotice("Referência privada confirmada; ela não é arquivo, bytes, checksum ou download.");await load()}catch{}}
 async function evaluate(){try{const b=await mutate("evaluate","/api/ext/compliance/evaluate",{});setNotice(`Avaliação ${b.evaluation_date} (fonte ${b.source}): ${b.facts.tasks_created} tarefa(s) criada(s), ${b.facts.documents_marked_a_vencer} a vencer${b.facts.failed_closed?.length?`, ${b.facts.failed_closed.length} falha(s) fechada(s) por responsável`:""}.`);await load()}catch{}}
 async function renewDoc(e:FormEvent){e.preventDefault();try{const b=await mutate("renew",`/api/ext/compliance/documents/${renew.document_id}/renew`,renew);setNotice(`Renovação v${b.document?.version_no} registrada; versão anterior substituída e imutável.`);await load()}catch{}}
 async function taskAction(t:Item,action:"start"|"complete"|"cancel"){try{const value=action==="complete"?{result:`Conclusão sintética registrada por staff para a tarefa ${t.id.slice(0,8)}.`}:action==="cancel"?{justification:`Cancelamento justificado por staff para a tarefa ${t.id.slice(0,8)}.`}:{};await mutate(`task-${action}-${t.id}`,`/api/ext/compliance/tasks/${t.id}/${action}`,value);await load()}catch{}}
 return <main style={{maxWidth:1180,margin:"24px auto",padding:16,fontFamily:"system-ui",background:"#f8fafc"}}>
 <h1>Compliance corporativo — EXT-07</h1><p><strong>Critério:</strong> vencimento gera tarefa e documento privado.</p>
 <p>Jornada interna de staff. A referência documental é privada e declarada: não representa upload, bytes, checksum, malware scan, armazenamento verificado ou download. Aplicabilidade é declaração interna, não parecer jurídico.</p>
 {loading&&<p role="status">Carregando dados reais do backend…</p>}
 {error&&<div role="alert" style={{...box,borderColor:"#dc2626"}}>{error} <button onClick={()=>void load()}>Tentar novamente</button></div>}
 {notice&&<p role="status">{notice}</p>}
 <section style={box}><h2>Obrigação aplicável</h2><form onSubmit={createOb} style={{display:"flex",gap:8,flexWrap:"wrap"}}>{(["obligation_type","title","description","declared_source","applicability_scope","applicability_justification","validity_rule","responsible_identity"] as const).map(k=><input key={k} required style={input} placeholder={k} value={ob[k]} onChange={e=>setOb({...ob,[k]:e.target.value})}/>)}<button type="submit" style={{padding:"8px 16px"}}>Registrar obrigação</button></form><p>Sem seed: vazio real não significa zero risco; agregados informam fonte e denominador.</p></section>
 <section style={box}><h2>Documento / referência privada</h2><form onSubmit={createDoc} style={{display:"flex",gap:8,flexWrap:"wrap"}}><select style={input} required value={doc.obligation_id} onChange={e=>setDoc({...doc,obligation_id:e.target.value})}><option value="">Obrigação canônica</option>{obligations.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select>{(["title","description","issue_date","expiry_date","declared_reference","reference_source"] as const).map(k=><input key={k} required style={input} type={k.includes("date")?"date":"text"} placeholder={k} value={doc[k]} onChange={e=>setDoc({...doc,[k]:e.target.value})}/>)}<button type="submit" style={{padding:"8px 16px"}}>Registrar referência</button></form><button onClick={()=>void evaluate()} style={{marginTop:8,padding:"8px 16px"}}>Avaliar vencimentos na data do servidor</button></section>
 <section style={box}><h2>Renovação (novo registro versionado)</h2><form onSubmit={renewDoc} style={{display:"flex",gap:8,flexWrap:"wrap"}}><select style={input} required value={renew.document_id} onChange={e=>setRenew({...renew,document_id:e.target.value})}><option value="">Documento corrente</option>{docs.filter(d=>["vigente","a_vencer","em_renovacao","vencida"].includes(d.status)).map(d=><option key={d.id} value={d.id}>{d.protocol} v{d.version_no} · {d.status}</option>)}</select>{(["issue_date","expiry_date","declared_reference","justification"] as const).map(k=><input key={k} required style={input} type={k.includes("date")?"date":"text"} placeholder={k} value={renew[k]} onChange={e=>setRenew({...renew,[k]:e.target.value})}/>)}<button type="submit" style={{padding:"8px 16px"}}>Renovar (substitui formalmente a versão anterior)</button></form><p>A versão anterior vira histórico imutável; nunca é sobrescrita.</p></section>
 <section style={box}><h2>Obrigações</h2>{!loading&&!obligations.length&&<p>Nenhuma obrigação no backend canônico.</p>}<ul>{obligations.map(o=><li key={o.id}>{o.title} · {o.status} · responsável canônico {o.responsible_name||o.responsible_identity}</li>)}</ul>
 <h2>Documentos</h2>{!loading&&!docs.length&&<p>Nenhum documento/referência canônica.</p>}<ul>{docs.map(d=><li key={d.id}>{d.protocol} v{d.version_no}{d.replacement_of?" (renovação)":""} — {d.title} · {d.status} · validade {d.expiry_date||"sem vencimento declarado"} · privado {String(d.is_private)}</li>)}</ul>
 <h2>Tarefas de vencimento</h2>{!loading&&!tasks.length&&<p>Nenhuma tarefa: ausência não é zero, é ausência de avaliação.</p>}<ul>{tasks.map(t=><li key={t.id}>{t.rule} · período {t.validity_period} · vence {t.due_date} · {t.status}{t.status==="aberta"&&<button style={{marginLeft:8}} onClick={()=>void taskAction(t,"start")}>Iniciar</button>}{["aberta","em_andamento"].includes(t.status)&&<button style={{marginLeft:8}} onClick={()=>void taskAction(t,"complete")}>Concluir</button>}{["aberta","em_andamento"].includes(t.status)&&<button style={{marginLeft:8}} onClick={()=>void taskAction(t,"cancel")}>Cancelar</button>}</li>)}</ul></section>
 </main>}
