"use client";
import {FormEvent,useCallback,useEffect,useRef,useState} from "react";
type Survey={id:string;protocol:string;account_name:string;survey_type:string;status:string;purpose:string;methodology:string;methodology_source:string;scale_min:number;scale_max:number;response_count:number;follow_up_count:number;created_at:string};
type Refs={accounts:{id:string;display_name:string}[];targets:{id:string;display_name:string;email:string;client_account_id:string}[]};
type Detail={survey:Survey;responses:Array<{id:string;score:number;feedback:string;responded_at:string}>;action_plans:Array<{id:string;status:string;responsible_display_name:string;trigger_rule:unknown;facts_json:unknown;created_at:string;completion_result?:string}>;events:unknown[]};
const box:React.CSSProperties={background:"#fff",border:"1px solid #cbd5e1",borderRadius:12,padding:16,marginBottom:16};const input:React.CSSProperties={padding:8,border:"1px solid #94a3b8",borderRadius:6,margin:3};const button:React.CSSProperties={...input,background:"#155e75",color:"white",cursor:"pointer"};
const initial={client_account_id:"",target_identity_id:"",survey_type:"pos_atendimento",purpose:"",methodology:"generica",methodology_source:"",scale_min:"0",scale_max:"10",follow_up_threshold:"6",reference_start:"",reference_end:""};
async function body(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{error:t||String(r.status)}}}
export default function SatisfacaoWorkspace(){const [items,setItems]=useState<Survey[]>([]),[refs,setRefs]=useState<Refs>({accounts:[],targets:[]}),[detail,setDetail]=useState<Detail|null>(null),[form,setForm]=useState(initial),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[result,setResult]=useState("");const keys=useRef<Record<string,string>>({});
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [a,b]=await Promise.all([fetch("/api/ext/satisfaction/surveys"),fetch("/api/ext/satisfaction/references")]),[x,y]=await Promise.all([body(a),body(b)]);if(!a.ok||!b.ok)throw new Error(x.error||y.error);setItems(x.surveys||[]);setRefs(y);}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar");}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 async function mutate(op:string,url:string,payload:unknown){const key=keys.current[op]||`ext06-${op}-${crypto.randomUUID()}`;keys.current[op]=key;const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json","idempotency-key":key},body:JSON.stringify(payload)}),b=await body(r);if(!r.ok){setError(`${b.error||r.status}. A mesma chave será preservada no retry: ${key}`);throw new Error(b.error)}delete keys.current[op];return b;}
 async function inspect(id:string){const r=await fetch(`/api/ext/satisfaction/surveys/${id}`),b=await body(r);if(!r.ok){setError(b.error);return}setDetail(b)}
 async function create(e:FormEvent){e.preventDefault();setError("");try{const payload={...form,scale_min:Number(form.scale_min),scale_max:Number(form.scale_max),follow_up_threshold:Number(form.follow_up_threshold),reference_start:form.reference_start||null,reference_end:form.reference_end||null};const b=await mutate("create","/api/ext/satisfaction/surveys",payload);setNotice(`Pesquisa ${b.survey.protocol} confirmada pelo servidor.`);setForm(initial);await load();await inspect(b.survey.id)}catch{}}
 async function plan(id:string,op:string){setError("");try{await mutate(`${id}-${op}`,`/api/ext/satisfaction/plans/${id}/${op}`,op==="complete"?{result}:{justification:result||"Cancelamento explicitamente justificado pela gestão."});setNotice("Acompanhamento alterado somente após confirmação do servidor.");await load();if(detail)await inspect(detail.survey.id)}catch{}}
 const targets=refs.targets.filter(t=>t.client_account_id===form.client_account_id);return <main style={{maxWidth:1180,margin:"24px auto",padding:16,fontFamily:"system-ui",background:"#f8fafc"}}><h1>Satisfação e carteira — EXT-06</h1><p><strong>Critério:</strong> Resposta gera acompanhamento sem expor funcionário.</p><p>O portal do cliente recebe uma projeção mínima; responsável, fatos, risco, notas internas, tarefa e auditoria permanecem nesta fronteira staff.</p>{loading&&<p role="status">Carregando backend real…</p>}{error&&<p role="alert">{error} <button style={button} onClick={()=>void load()}>Tentar novamente</button></p>}{notice&&<p role="status">{notice}</p>}
 <section style={box}><h2>Configurar pesquisa</h2><form onSubmit={create}><select required style={input} value={form.client_account_id} onChange={e=>setForm({...form,client_account_id:e.target.value,target_identity_id:""})}><option value="">Conta</option>{refs.accounts.map(x=><option key={x.id} value={x.id}>{x.display_name}</option>)}</select><select required style={input} value={form.target_identity_id} onChange={e=>setForm({...form,target_identity_id:e.target.value})}><option value="">Destinatário com grant</option>{targets.map(x=><option key={x.id} value={x.id}>{x.display_name||x.email}</option>)}</select><select style={input} value={form.survey_type} onChange={e=>setForm({...form,survey_type:e.target.value})}><option value="pos_atendimento">Pós-atendimento</option><option value="periodica">Periódica</option><option value="outro">Outra</option></select><input required style={input} placeholder="Finalidade" value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}/><select style={input} value={form.methodology} onChange={e=>{const m=e.target.value;setForm({...form,methodology:m,scale_min:m==="csat"?"1":"0",scale_max:m==="csat"?"5":"10"})}}><option value="generica">Genérica (não é NPS/CSAT)</option><option value="nps">NPS 0–10</option><option value="csat">CSAT 1–5</option></select><input required style={input} placeholder="Fonte/metodologia declarada" value={form.methodology_source} onChange={e=>setForm({...form,methodology_source:e.target.value})}/><input style={input} type="number" value={form.scale_min} onChange={e=>setForm({...form,scale_min:e.target.value})}/><input style={input} type="number" value={form.scale_max} onChange={e=>setForm({...form,scale_max:e.target.value})}/><label>Limiar declarado (nota ≤): <input style={input} type="number" value={form.follow_up_threshold} onChange={e=>setForm({...form,follow_up_threshold:e.target.value})}/></label><input style={input} type="date" value={form.reference_start} onChange={e=>setForm({...form,reference_start:e.target.value})}/><input style={input} type="date" value={form.reference_end} onChange={e=>setForm({...form,reference_end:e.target.value})}/><button style={button}>Criar pesquisa</button></form></section>
 <section style={box}><h2>Histórico</h2>{!loading&&!items.length&&<p>Vazio real: nenhuma pesquisa canônica; migração sem seed.</p>}<ul>{items.map(x=><li key={x.id}><button style={button} onClick={()=>void inspect(x.id)}>{x.protocol}</button> {x.account_name} · {x.methodology} {x.scale_min}–{x.scale_max} · {x.status} · respostas {x.response_count} · acompanhamentos {x.follow_up_count}</li>)}</ul></section>
 {detail&&<section style={box}><h2>{detail.survey.protocol}</h2><p>{detail.survey.purpose} · metodologia/fonte: {detail.survey.methodology} / {detail.survey.methodology_source}</p><h3>Respostas (detalhe staff autorizado)</h3><ul>{detail.responses.map(r=><li key={r.id}>Nota {r.score} em {new Date(r.responded_at).toISOString()} — {r.feedback}</li>)}</ul><h3>Acompanhamento/recuperação</h3><input style={input} placeholder="Resultado ou justificativa" value={result} onChange={e=>setResult(e.target.value)}/><ul>{detail.action_plans.map(p=><li key={p.id}>{p.status} · responsável canônico: {p.responsible_display_name||"pendente (fail-closed)"}<pre>{JSON.stringify({regra:p.trigger_rule,fatos:p.facts_json},null,2)}</pre>{p.status==="aberta"&&<button style={button} onClick={()=>void plan(p.id,"start")}>Iniciar</button>}{["aberta","em_andamento"].includes(p.status)&&<><button style={button} onClick={()=>void plan(p.id,"complete")}>Concluir com resultado</button><button style={button} onClick={()=>void plan(p.id,"cancel")}>Cancelar com justificativa</button></>}</li>)}</ul><h3>Eventos imutáveis</h3><pre>{JSON.stringify(detail.events,null,2)}</pre></section>}</main>}
