'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Check,Monitor,Smartphone,ExternalLink,Palette,ArrowRight} from 'lucide-react';
import {SITE_VISUAL_OPTIONS,isSiteVisualId,type SiteVisualId} from '@/lib/site-visuals';
import styles from './AppearanceGallery.module.css';
export default function AppearanceGallery(){
 const [active,setActive]=useState<SiteVisualId|null>(null),[selected,setSelected]=useState<SiteVisualId>('06'),[canManage,setCanManage]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[device,setDevice]=useState<'desktop'|'mobile'>('desktop'),[confirm,setConfirm]=useState(false),[reason,setReason]=useState(''),[checked,setChecked]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),applyButton=useRef<HTMLButtonElement>(null),lock=useRef(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/admin/site-visual',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(r.status===403?'Este perfil não administra a aparência do site.':r.status===401?'Entre com sua conta individual para administrar o site.':'Não foi possível consultar a configuração. Confira o banco e as migrações.');if(!isSiteVisualId(d.visual))throw Error('A configuração retornou um layout desconhecido.');setActive(d.visual);setSelected(d.visual);setCanManage(d.canManage===true);}catch(e){setCanManage(false);setError(e instanceof Error?e.message:'Consulta indisponível.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(confirm)dialog.current?.showModal();else if(dialog.current?.open){dialog.current.close();applyButton.current?.focus();}},[confirm]);
 const chosen=SITE_VISUAL_OPTIONS.find(o=>o.id===selected)!;
 async function publish(){if(lock.current||!checked||reason.trim().length<10||!active)return;lock.current=true;setBusy(true);setError('');try{
  const r=await fetch('/api/site-visual',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({visual:selected,expectedVisual:active,reason})});const d=await r.json();
  if(!r.ok)throw Error(d.error==='visual_changed_refresh'?'Outro administrador alterou o layout. Atualize a configuração antes de decidir.':r.status===403?'A sua permissão de publicação não está ativa. Solicite site.visual.write ao TI.':'A alteração não foi confirmada. Confira o servidor e tente novamente.');
  setActive(selected);setConfirm(false);setReason('');setChecked(false);setMessage(`Layout ${selected} — ${chosen.name} aplicado ao site. A mudança foi registrada na auditoria.`);window.dispatchEvent(new CustomEvent('seg-site-visual-updated',{detail:selected}));
 }catch(e){setError(e instanceof Error?e.message:'Alteração não confirmada.');}finally{lock.current=false;setBusy(false);}}
 return <section className={styles.gallery} aria-busy={busy||loading}><header className={styles.heading}><div><span className={styles.eyebrow}><Palette size={16}/>Identidade e aparência</span><h1>Escolha a apresentação do site</h1><p>Compare as dez opções. A prévia não altera o site; a aplicação exige confirmação e fica registrada na auditoria.</p></div><div className={styles.current}><span>Layout ativo</span><strong>{active?`${active} · ${SITE_VISUAL_OPTIONS.find(o=>o.id===active)?.name}`:'Não confirmado'}</strong><a href="/" target="_blank" rel="noopener noreferrer">Abrir site atual <ExternalLink size={14}/></a></div></header>
 {loading&&<p role="status">Consultando configuração…</p>}{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}{!loading&&!canManage&&!error&&<p className={styles.notice}>Você pode comparar as propostas. Para aplicar, sua conta precisa da concessão site.visual.write para toda a organização.</p>}
 <div className={styles.grid} aria-label="Dez apresentações disponíveis">{SITE_VISUAL_OPTIONS.map(o=><button key={o.id} type="button" aria-pressed={selected===o.id} disabled={busy} className={`${styles.option} ${selected===o.id?styles.selected:''}`} onClick={()=>{setSelected(o.id);setMessage('');}}><span className={styles.art} data-layout={o.id} aria-hidden="true"><span className={styles.artTop}/><span className={styles.artHero}/><span className={styles.artCards}><i/><i/><i/></span></span><span className={styles.optionTitle}>{o.name}{active===o.id&&<span className={styles.badge}><Check size={12}/>Ativo</span>}</span><span className={styles.description}>{o.descriptor}</span><span className={styles.optionFoot}>Layout {o.id}<span>{selected===o.id?'Em comparação':'Comparar'} <ArrowRight size={13}/></span></span></button>)}</div>
 <section className={styles.preview} aria-labelledby="appearance-preview"><div className={styles.previewHeader}><div><h2 id="appearance-preview">Prévia real · {chosen.name}</h2><p>As miniaturas são esquemas. A janela abaixo renderiza o layout real.</p></div><div className={styles.device} role="group" aria-label="Tamanho da prévia"><button type="button" aria-pressed={device==='desktop'} onClick={()=>setDevice('desktop')}><Monitor size={16}/>Desktop</button><button type="button" aria-pressed={device==='mobile'} onClick={()=>setDevice('mobile')}><Smartphone size={16}/>Celular</button><a href={`/layout-preview?visual=${selected}`} target="_blank" rel="noopener noreferrer">Abrir prévia <ExternalLink size={14}/></a></div></div><div className={styles.stage}><iframe key={selected} src={`/layout-preview?visual=${selected}`} title={`Prévia do layout ${selected}: ${chosen.name}`} className={device==='mobile'?styles.mobile:styles.desktop} loading="lazy"/></div></section>
 <footer className={styles.apply}><div><strong>{active===selected?'Você está comparando o layout atual':`Alteração proposta: ${active||'—'} → ${selected}`}</strong><p>O conteúdo e as regras do sistema continuam nos mesmos módulos.</p></div><button type="button" className={styles.secondary} disabled={loading||busy} onClick={()=>void load()}>Atualizar configuração</button><button type="button" ref={applyButton} className={styles.primary} disabled={!canManage||loading||busy||active===selected} onClick={()=>{setChecked(false);setConfirm(true);}}>Revisar e aplicar</button></footer>
 <dialog ref={dialog} className={styles.dialog} aria-labelledby="appearance-confirm" onCancel={e=>{e.preventDefault();if(!busy)setConfirm(false);}}><h2 id="appearance-confirm">Aplicar {chosen.name} ao site?</h2><p>O layout {selected} substituirá o layout {active} para os visitantes. Você pode retornar escolhendo a apresentação anterior na galeria.</p><label>Motivo da mudança<textarea minLength={10} maxLength={1000} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><label className={styles.review}><input type="checkbox" checked={checked} disabled={busy} onChange={e=>setChecked(e.target.checked)}/>Conferi a prévia e quero aplicar este layout.</label>{error&&<p role="alert" className={styles.error}>{error}</p>}<div className={styles.device}><button type="button" disabled={busy} onClick={()=>setConfirm(false)}>Cancelar</button><button className={styles.primary} type="button" disabled={busy||!checked||reason.trim().length<10} onClick={()=>void publish()}>{busy?'Aplicando…':'Confirmar alteração'}</button></div></dialog>
 </section>;
}
