"use client";
import {FormEvent,useCallback,useEffect,useRef,useState} from "react";
type NC={id:string;protocol:string;title:string;description:string;category:string;severity:string;status:string;responsible_identity:string;recurrence_count_derived:number};
type Staff={id:string;display_name:string;role:string};
type Detail={nonconformity:NC;causes:Array<Record<string,unknown>>;actions:Array<Record<string,unknown>>;verifications:Array<Record<string,unknown>>;closures:Array<Record<string,unknown>>;reopenings:Array<Record<string,unknown>>;recurrences:Array<Record<string,unknown>>};
const box:React.CSSProperties={background:"white",border:"1px solid #d1d5db",borderRadius:12,padding:16,marginBottom:16};
const input:React.CSSProperties={padding:8,border:"1px solid #9ca3af",borderRadius:6,minWidth:180};
const button:React.CSSProperties={padding:"9px 13px",border:0,borderRadius:6,background:"#155e75",color:"white",cursor:"pointer",margin:3};
const empty={title:"",description:"",category:"",severity:"media",responsible_identity:""};
async function json(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{error:t||`HTTP ${r.status}`}}}
export default function QualidadeWorkspace(){
 const [items,setItems]=useState<NC[]>([]),[staff,setStaff]=useState<Staff[]>([]),[selected,setSelected]=useState(""),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [form,setForm]=useState(empty),[cause,setCause]=useState({description:"",declared_source:""}),[action,setAction]=useState({description:"",action_type:"corretiva",responsible_identity:"",due_date:"",due_date_source:"",due_date_base_date:""}),[verification,setVerification]=useState({outcome:"eficaz",description:"",evidence_type:"referencia_documental",evidence_reference:"",evidence_source:""}),[reason,setReason]=useState(""),[closureNote,setClosureNote]=useState(""),[recurrence,setRecurrence]=useState({...empty,justification:"",declared_criterion:"",declared_source:""});
 const keys=useRef<Record<string,string>>({});
 const loadDetail=useCallback(async(id:string)=>{if(!id){setDetail(null);return;}const r=await fetch(`/api/ext/quality/nonconformities/${id}`);const b=await json(r);if(!r.ok)throw new Error(b.error);setDetail(b);},[]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [a,b]=await Promise.all([fetch("/api/ext/quality/nonconformities"),fetch("/api/ext/quality/references")]);const [x,y]=await Promise.all([json(a),json(b)]);if(!a.ok||!b.ok)throw new Error(x.error||y.error);setItems(x.nonconformities||[]);setStaff(y.staff||[]);if(selected)await loadDetail(selected);}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar");}finally{setLoading(false);}},[selected,loadDetail]);
 useEffect(()=>{void load()},[load]);
 async function mutate(op:string,url:string,body:unknown){const k=keys.current[op]||`ext05-${op}-${crypto.randomUUID()}`;keys.current[op]=k;setBusy(op);setError("");setNotice("");try{const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json","idempotency-key":k},body:JSON.stringify(body)});const b=await json(r);if(!r.ok)throw new Error(`${b.error||r.status}${b.missing?`: ${b.missing.join(", ")}`:""}`);delete keys.current[op];return b;}catch(e){setError(`${e instanceof Error?e.message:"Falha"}. Chave preservada para retry seguro: ${k}`);throw e;}finally{setBusy("");}}
 async function done(message:string,id=selected){await load();if(id)await loadDetail(id);setNotice(message);}
 async function create(e:FormEvent){e.preventDefault();try{const b=await mutate("create","/api/ext/quality/nonconformities",form);setSelected(b.nonconformity.id);setForm(empty);await done("Não conformidade confirmada pelo servidor.",b.nonconformity.id);}catch{}}
 async function add(op:string,path:string,body:unknown,message:string){if(!selected)return;try{await mutate(`${op}-${selected}`,`/api/ext/quality/nonconformities/${selected}/${path}`,body);await done(message);}catch{}}
 async function actionTerminal(id:string,op:"complete"|"cancel"){try{await mutate(`action-${op}-${id}`,`/api/ext/quality/actions/${id}/${op}`,op==="complete"?{note:reason||"Conclusão confirmada pela equipe interna."}:{justification:reason});await done(`Ação ${op==="complete"?"concluída":"cancelada"} pelo servidor.`);}catch{}}
 async function transition(status:string){await add(`status-${status}`,"transition",{status,reason},`Estado ${status} confirmado pelo servidor.`)}
 async function close(){const v=detail?.verifications.filter(x=>x.outcome==="eficaz").at(-1);if(!v){setError("Registre uma verificação eficaz antes de encerrar.");return;}await add("close","close",{verification_id:v.id,closure_note:closureNote},"Encerramento confirmado com evidência e responsável.")}
 async function recur(e:FormEvent){e.preventDefault();try{const b=await mutate(`recurrence-${selected}`,`/api/ext/quality/nonconformities/${selected}/recurrences`,recurrence);setSelected(b.nonconformity.id);await done("Reincidência explícita confirmada; contador é derivado.",b.nonconformity.id);}catch{}}
 return <main style={{maxWidth:1200,margin:"24px auto",padding:16,fontFamily:"system-ui",background:"#f8fafc"}}><h1>Qualidade — EXT-05</h1><p><strong>Critério:</strong> Encerrar apenas com evidência e responsável.</p><p>Jornada exclusivamente interna de staff. Referências documentais são declarações rastreáveis; não representam upload, arquivo verificado ou armazenamento confirmado.</p>
 {loading&&<p role="status">Carregando dados reais do backend…</p>}{error&&<div role="alert" style={{...box,borderColor:"#dc2626"}}>{error} <button style={button} onClick={()=>void load()}>Tentar novamente</button></div>}{notice&&<p role="status" style={{color:"#166534"}}>{notice}</p>}
 <section style={box}><h2>Nova não conformidade</h2><form onSubmit={create}>{(["title","description","category"] as const).map(k=><input key={k} style={input} required placeholder={k} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<select style={input} value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option>baixa</option><option>media</option><option>alta</option><option>critica</option></select><span>Responsável inicial: identidade da sessão staff.</span><button style={button} disabled={!!busy}>Criar</button></form></section>
 <section style={box}><h2>Não conformidades</h2>{!loading&&!items.length&&<p>Nenhuma não conformidade no backend canônico. O sistema não cria seed.</p>}<ul>{items.map(n=><li key={n.id}><button style={{...button,background:selected===n.id?"#0f172a":"#475569"}} onClick={()=>{setSelected(n.id);void loadDetail(n.id)}}>{n.protocol} — {n.title}</button> {n.status} · reincidências derivadas: {n.recurrence_count_derived||0}</li>)}</ul></section>
 {detail&&<><section style={box}><h2>{detail.nonconformity.protocol}: {detail.nonconformity.title}</h2><p>Estado: <strong>{detail.nonconformity.status}</strong> · responsável: {detail.nonconformity.responsible_identity}</p><input style={input} placeholder="Justificativa da transição/reabertura" value={reason} onChange={e=>setReason(e.target.value)}/>{detail.nonconformity.status==="aberta"&&<button style={button} onClick={()=>void transition("em_analise")}>Iniciar análise</button>}{detail.nonconformity.status==="em_analise"&&<button style={button} onClick={()=>void transition("em_acao_corretiva")}>Ir para ação corretiva</button>}{detail.nonconformity.status==="em_acao_corretiva"&&<button style={button} onClick={()=>void transition("verificacao")}>Ir para verificação</button>}{detail.nonconformity.status==="encerrada"&&<button style={button} onClick={()=>void add("reopen","reopen",{justification:reason},"Reabertura formal confirmada; encerramento histórico preservado.")}>Reabrir formalmente</button>}{detail.nonconformity.status==="reaberta"&&<button style={button} onClick={()=>void transition("em_analise")}>Retomar análise</button>}</section>
 <section style={box}><h3>Causa/análise histórica</h3><input style={input} placeholder="Descrição da causa" value={cause.description} onChange={e=>setCause({...cause,description:e.target.value})}/><input style={input} placeholder="Fonte/fundamento declarado" value={cause.declared_source} onChange={e=>setCause({...cause,declared_source:e.target.value})}/><button style={button} onClick={()=>void add("cause","causes",cause,"Causa histórica confirmada.")}>Registrar causa</button><pre>{JSON.stringify(detail.causes,null,2)}</pre></section>
 <section style={box}><h3>Ações corretivas</h3><input style={input} placeholder="Descrição" value={action.description} onChange={e=>setAction({...action,description:e.target.value})}/><select style={input} value={action.responsible_identity} onChange={e=>setAction({...action,responsible_identity:e.target.value})}><option value="">Responsável</option>{staff.map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select><input style={input} type="date" value={action.due_date} onChange={e=>setAction({...action,due_date:e.target.value})}/><input style={input} placeholder="Fonte do prazo" value={action.due_date_source} onChange={e=>setAction({...action,due_date_source:e.target.value})}/><input style={input} type="date" value={action.due_date_base_date} onChange={e=>setAction({...action,due_date_base_date:e.target.value})}/><button style={button} onClick={()=>void add("action","actions",action,"Ação confirmada com responsável canônico.")}>Criar ação</button><ul>{detail.actions.map(a=><li key={String(a.id)}>{String(a.description)} — {String(a.status)} {a.status==="pendente"&&<><button style={button} onClick={()=>void actionTerminal(String(a.id),"complete")}>Concluir</button><button style={button} onClick={()=>void actionTerminal(String(a.id),"cancel")}>Cancelar</button></>}</li>)}</ul></section>
 <section style={box}><h3>Verificação e evidência declarada</h3>{(["description","evidence_type","evidence_reference","evidence_source"] as const).map(k=><input key={k} style={input} placeholder={k} value={verification[k]} onChange={e=>setVerification({...verification,[k]:e.target.value})}/>)}<select style={input} value={verification.outcome} onChange={e=>setVerification({...verification,outcome:e.target.value})}><option value="eficaz">eficaz</option><option value="ineficaz">ineficaz</option></select><button style={button} onClick={()=>void add("verification","verifications",verification,"Verificação estruturada confirmada; referência não é upload.")}>Registrar verificação</button><pre>{JSON.stringify(detail.verifications,null,2)}</pre>{detail.nonconformity.status==="verificacao"&&<><input style={input} placeholder="Nota de encerramento" value={closureNote} onChange={e=>setClosureNote(e.target.value)}/><button style={button} onClick={()=>void close()}>Encerrar com evidência e responsável</button></>}</section>
 <section style={box}><h3>Reincidência explícita</h3><form onSubmit={recur}>{(["title","description","category","justification","declared_criterion","declared_source"] as const).map(k=><input key={k} style={input} required placeholder={k} value={recurrence[k]} onChange={e=>setRecurrence({...recurrence,[k]:e.target.value})}/>)}<span>Responsável da reincidência: identidade da sessão staff.</span><button style={button}>Registrar nova NC reincidente</button></form></section></>}
 </main>;
}
