// Conteúdo da Academia. Textos em português do Brasil, sem vídeo nesta fase.
// Cada aula tem objetivo, passos, um quiz de uma pergunta e a explicação
// (a explicação e a resposta só são enviadas após a conclusão da aula).
//
// Estrutura: BASE guarda as aulas já publicadas (texto completo, com quiz).
// O organizador abaixo monta as 24 trilhas do plano de expansão
// (docs/academia/PLANO-DE-EXPANSAO.md), reaproveitando as aulas publicadas
// pelos ids e acrescentando as demais como "em construção" (sem conteúdo).
// Aulas em construção não contam no progresso e não podem ser concluídas.

function aula(id, title, minutes, objective, steps, question, options, answer, explanation) {
  return { id, title, minutes, objective, steps, quiz: { question, options, answer, explanation } };
}

const BASE = Object.freeze([
  {
    id: 'fundamentos',
    title: 'Fundamentos do sistema',
    summary: 'Acesso, progresso e uso da base de conhecimento. Trilha comum a todos os setores.',
    audiences: ['todos'],
    lessons: [
      aula('fund-acesso', 'Primeiro acesso à Academia', 3,
        'Entrar na Academia e entender o que aparece depois do login.',
        [
          'Informe o e-mail cadastrado para você e a sua senha.',
          'Ao entrar, a tela mostra apenas as trilhas do seu setor.',
          'Seu nível, seus pontos e a próxima aula ficam no topo da página inicial.',
        ],
        'O que aparece na sua tela depois do login?',
        ['Todas as trilhas da empresa', 'Somente as trilhas do seu setor', 'Nenhuma trilha até a liberação do gestor'],
        1,
        'A tela é personalizada pelo setor. Conteúdos de outros setores não aparecem e não podem ser abertos pelo endereço.'),
      aula('fund-progresso', 'Como o progresso é contado', 3,
        'Entender pontos, níveis e selos.',
        [
          'Cada aula concluída soma pontos. Vale a primeira conclusão.',
          'Acertar o quiz na primeira resposta soma pontos extras.',
          'Concluir todas as aulas de uma trilha dá pontos de bônus e um selo.',
          'O ranking compara apenas colegas do mesmo setor.',
        ],
        'Quando os pontos de uma aula são creditados?',
        ['Ao abrir a aula', 'Na primeira conclusão da aula', 'Toda vez que o quiz for respondido'],
        1,
        'Os pontos são creditados na primeira conclusão. Reenviar a resposta não soma pontos novamente.'),
      aula('fund-base', 'Base de conhecimento e dúvidas', 2,
        'Saber onde consultar procedimentos do sistema.',
        [
          'O menu lateral de cada sistema termina com a Base de conhecimento.',
          'Use a base para consultar procedimentos e orientações da sua área.',
          'Se a resposta não estiver na base, procure seu gestor antes de decidir por conta própria.',
        ],
        'Onde consultar os procedimentos do sistema?',
        ['Na base de conhecimento do menu', 'Em uma planilha pessoal', 'Somente com colegas'],
        0,
        'A base de conhecimento do menu lateral é a referência para procedimentos do sistema.'),
    ],
  },
  {
    id: 'funcionario-ponto',
    title: 'Funcionário: ponto e ocorrências',
    summary: 'Como registrar ponto, ocorrências e pedidos pelo portal do funcionário.',
    audiences: ['funcionario'],
    lessons: [
      aula('func-ponto', 'Registrar ponto', 4,
        'Registrar entrada, rondas e saída pelo portal.',
        [
          'Abra a aba Jornada no portal do funcionário.',
          'Registre a entrada ao iniciar o posto.',
          'Registre as rondas conforme a escala do seu posto.',
          'Registre a saída ao encerrar. Se algum registro estiver errado, solicite o ajuste ao RH.',
          'Se o registro pedir localização, ela só é usada com o seu consentimento.',
        ],
        'Quando a localização pode ser usada no registro de ponto?',
        ['Sempre, por padrão', 'Somente com o seu consentimento', 'Nunca'],
        1,
        'A localização depende do consentimento registrado no portal.'),
      aula('func-ocorrencia', 'Registrar uma ocorrência', 4,
        'Registrar um fato fora do normal com as informações corretas.',
        [
          'Escolha Ocorrência no portal do funcionário.',
          'Informe a categoria e a gravidade.',
          'Informe o local e descreva o que aconteceu, com fatos objetivos.',
          'Envie. O registro segue direto para quem vai analisar.',
        ],
        'Quais informações compõem o registro de ocorrência?',
        ['Categoria, gravidade, local e o que aconteceu', 'Apenas o local', 'Somente uma foto'],
        0,
        'Esses campos são os que orientam a análise da ocorrência.'),
      aula('func-pedidos', 'Pedidos, ausências e ajustes de ponto', 3,
        'Enviar pedidos e acompanhar a resposta do RH.',
        [
          'Use Pedidos para férias, benefício, afastamento ou reembolso.',
          'Registre ausências pelo portal quando precisar.',
          'Se o ponto estiver errado, solicite o ajuste. O RH analisa a solicitação.',
          'Acompanhe o status e leia a resposta publicada para você.',
        ],
        'Quem analisa o pedido de ajuste de ponto?',
        ['O RH', 'O cliente contratante', 'Ninguém; o ajuste é automático'],
        0,
        'Ajustes de ponto são analisados pelo RH, que registra a decisão.'),
    ],
  },
  {
    id: 'cliente-portal',
    title: 'Cliente: acesso e atendimento',
    summary: 'Ativação do acesso, segurança da conta e acompanhamento de chamados.',
    audiences: ['cliente'],
    lessons: [
      aula('cli-convite', 'Ativar seu acesso pelo convite', 3,
        'Entrar no portal do cliente pela primeira vez.',
        [
          'O portal é acessado somente por convite.',
          'Abra o link do convite e aceite o convite.',
          'Confirme o seu e-mail.',
          'Entre no portal e confira os contratos e documentos da sua empresa.',
        ],
        'Qual é o primeiro passo para acessar o portal?',
        ['Aceitar o convite recebido', 'Criar conta sem convite', 'Solicitar a senha por telefone'],
        0,
        'O acesso é por convite. Criar conta sem convite não libera o portal.'),
      aula('cli-seguranca', 'Segurança: verificação em duas etapas e sessões', 3,
        'Proteger seu acesso e revisar as sessões ativas.',
        [
          'Na aba Segurança, ative a verificação em duas etapas (MFA).',
          'Revise as sessões ativas com regularidade.',
          'Encerre as sessões que você não reconhece.',
          'Confirme uma troca de e-mail somente se você a solicitou.',
        ],
        'Ao reconhecer uma sessão que não é sua, o que fazer?',
        ['Ignorar', 'Encerrar a sessão pela aba Segurança', 'Compartilhar o acesso com o gestor'],
        1,
        'Encerrar a sessão pela aba Segurança reduz o risco de acesso indevido.'),
      aula('cli-chamados', 'Chamados e documentos', 4,
        'Abrir, acompanhar e encerrar atendimentos.',
        [
          'Abra o chamado e descreva a necessidade com clareza.',
          'Acompanhe as mensagens e o status do atendimento.',
          'Quando o atendimento estiver resolvido, aceite e encerre pelo próprio chamado.',
          'Documentos compartilhados ficam em Documentos, com registro de acesso.',
        ],
        'Quando é possível aceitar e encerrar um atendimento?',
        ['Assim que o chamado for aberto', 'Depois que o chamado estiver resolvido', 'Nunca pelo cliente'],
        1,
        'O aceite só é liberado com o chamado resolvido.'),
    ],
  },
  {
    id: 'rh-processos',
    title: 'RH: admissão, acesso e desligamento',
    summary: 'Admissão, credenciais, holerite, solicitações e desligamento com revisão.',
    audiences: ['rh'],
    lessons: [
      aula('rh-admissao', 'Abrir a admissão', 4,
        'Cadastrar o profissional e abrir o processo de admissão.',
        [
          'Em Novo cadastro profissional, informe matrícula, nome, cargo, lotação, empregador e data de admissão.',
          'Confira os campos obrigatórios antes de enviar.',
          'Clique em Criar cadastro e abrir admissão.',
        ],
        'Qual ação abre o processo de admissão?',
        ['Criar cadastro e abrir admissão', 'Salvar rascunho', 'Enviar e-mail ao gestor'],
        0,
        'O botão de criação abre o cadastro e a admissão no mesmo passo.'),
      aula('rh-credencial', 'Criar acesso e credencial temporária', 4,
        'Liberar acesso individual com segurança.',
        [
          'Em Criar acesso do funcionário, escolha a pessoa.',
          'Informe o e-mail individual.',
          'Clique em Gerar credencial temporária.',
          'Entregue a credencial com cuidado: ela é exibida apenas uma vez.',
          'O acesso é individual. Não concede sessão de equipe nem de RH.',
        ],
        'Quantas vezes a credencial temporária é exibida?',
        ['Uma vez', 'A cada abertura da tela', 'Por 30 dias'],
        0,
        'Por segurança, a credencial não fica disponível para consulta posterior.'),
      aula('rh-holerite', 'Holerite e solicitações', 4,
        'Publicar holerites e decidir solicitações.',
        [
          'Feche o período demonstrativo na aba Fechamento e holerite.',
          'Publique o holerite: ele fica somente no espaço privado do titular.',
          'Em Solicitações, analise o pedido.',
          'Escolha Aprovar solicitação ou Rejeitar solicitação. O retorno é publicado para a pessoa.',
        ],
        'Onde o holerite publicado fica disponível?',
        ['No espaço privado da pessoa titular', 'Em um painel público da empresa', 'Em anexo a um e-mail'],
        0,
        'O holerite é privado e visível somente ao titular.'),
      aula('rh-desligamento', 'Desligamento com revisão', 4,
        'Concluir um desligamento com registro e revogação de acesso.',
        [
          'Informe a pessoa, o tipo e a data do desligamento.',
          'Registre o motivo com clareza.',
          'Clique em Revisar antes de concluir e confira o resumo.',
          'Conclua. As sessões ativas da pessoa são revogadas e o registro vai à trilha de auditoria.',
        ],
        'O que acontece ao concluir um desligamento?',
        ['As sessões ativas da pessoa são revogadas', 'Nada muda no acesso', 'O cadastro é apagado'],
        0,
        'A revogação acontece na conclusão e o motivo fica registrado com a sua identidade.'),
    ],
  },
  {
    id: 'comercial-funil',
    title: 'Comercial: do pedido à proposta',
    summary: 'Tratamento dos pedidos do site, funil, tarefas e propostas até o contrato.',
    audiences: ['comercial'],
    lessons: [
      aula('com-pedido', 'Converter o pedido do site', 3,
        'Transformar um pedido recebido em oportunidade.',
        [
          'Pedidos chegam pelos formulários de orçamento, contato e simulador do site.',
          'Abra o pedido em Pedidos do site.',
          'Clique em Converter pedido recebido para criar a empresa e a oportunidade.',
          'Confira os dados antes de seguir.',
        ],
        'De onde vêm os pedidos recebidos pelo site?',
        ['Formulários de orçamento, contato e simulador', 'Somente de ligações', 'Da área do cliente'],
        0,
        'Os três formulários públicos registram o pedido como lead.'),
      aula('com-funil', 'Funil, tarefas e delegação', 4,
        'Movimentar oportunidades e cuidar das tarefas.',
        [
          'Mova a oportunidade no funil conforme o avanço real.',
          'Registre interações e notas internas no histórico.',
          'Crie tarefas e agende visitas na sua agenda.',
          'Ao aceitar uma delegação, você assume a tarefa. A oportunidade continua com quem delegou.',
        ],
        'Ao aceitar uma delegação, quem continua responsável pela oportunidade?',
        ['Quem delegou', 'Quem aceitou a tarefa', 'Ninguém, até nova atribuição'],
        0,
        'A delegação transfere a tarefa, não a oportunidade.'),
      aula('com-proposta', 'Proposta, aceite e contrato', 4,
        'Levar a oportunidade até o contrato.',
        [
          'Crie a proposta a partir da oportunidade.',
          'Envie o link de aceite ao cliente.',
          'Quando o cliente aceitar uma versão, o aceite fica registrado.',
          'Em Contratos, crie o contrato a partir da proposta aceita.',
        ],
        'O que dá origem ao contrato em Contratos?',
        ['Proposta aceita', 'Pedido recebido pelo site', 'Chamado de cliente'],
        0,
        'O contrato nasce de uma proposta aceita, o que mantém a rastreabilidade.'),
    ],
  },
  {
    id: 'financeiro-receber',
    title: 'Financeiro: receber e fechar competência',
    summary: 'Recebíveis, conciliação, cobrança e fechamento de competência.',
    audiences: ['financeiro'],
    lessons: [
      aula('fin-receber', 'Contas a receber e aging', 4,
        'Acompanhar recebíveis por vencimento.',
        [
          'Lance e acompanhe as contas a receber.',
          'Registre a baixa quando o pagamento for confirmado.',
          'Use o aging de recebíveis para ver atrasos por faixa e por competência.',
        ],
        'O que o aging de recebíveis mostra?',
        ['Recebíveis por faixa de vencimento e competência', 'Somente pagamentos já feitos', 'Custos de pessoal'],
        0,
        'O aging agrupa o que está a receber por tempo de atraso e competência.'),
      aula('fin-conciliacao', 'Conciliação e cobrança', 4,
        'Conciliar extratos e tratar cobranças.',
        [
          'Importe o extrato bancário.',
          'Confirme cada lançamento conciliado ou marque a divergência, com o motivo.',
          'Crie a política de cobrança e os lembretes com critério.',
          'Os meios de pagamento usados em treinamento funcionam em ambiente de sandbox.',
        ],
        'Qual cuidado vale ao treinar cobrança e gateway de pagamento?',
        ['Tratar como sandbox, sem cobrança real', 'Usar dados reais de clientes', 'Não há cuidado especial'],
        0,
        'Em treinamento, nenhuma cobrança deve ser enviada a cliente real.'),
      aula('fin-competencia', 'Fechamento e reabertura de competência', 3,
        'Fechar e reabrir competências com registro.',
        [
          'Feche a competência somente depois de conferir lançamentos e conciliações.',
          'Para reabrir uma competência fechada, informe o motivo.',
          'As versões anteriores são preservadas, e o autor da reabertura vem da sua sessão.',
        ],
        'Para reabrir uma competência fechada, o sistema exige:',
        ['Um motivo registrado', 'Nenhuma informação', 'A aprovação do cliente'],
        0,
        'Reabrir exige motivo. O histórico da competência permanece registrado.'),
    ],
  },
  {
    id: 'operacao-escala',
    title: 'Operação e supervisão',
    summary: 'Postos, escala, cobertura, livro de ocorrências e checklists.',
    audiences: ['supervisor'],
    lessons: [
      aula('op-escala', 'Postos, escala e cobertura', 4,
        'Manter os postos cobertos.',
        [
          'Confira os postos físicos e a necessidade por turno.',
          'Publique a escala como uma nova versão.',
          'Quando faltar alguém, registre a solicitação de cobertura ou de substituição.',
          'Acompanhe as lacunas de cobertura até fechar.',
        ],
        'O que aparece em Lacunas de cobertura?',
        ['Turnos sem cobertura planejada', 'Pagamentos pendentes', 'Chamados de clientes'],
        0,
        'Lacunas são turnos que ainda não têm cobertura.'),
      aula('op-ocorrencias', 'Livro de ocorrências e passagem de plantão', 4,
        'Registrar o que aconteceu e transferir informações entre turnos.',
        [
          'Registre no livro de ocorrências o fato, com local e horário.',
          'Anexe evidências quando houver.',
          'Registre as ações tomadas e o status de cada ocorrência.',
          'Faça a passagem de plantão com as pendências do turno.',
        ],
        'Qual é o objetivo da passagem de plantão?',
        ['Transferir informações entre turnos', 'Fechar a folha de pagamento', 'Cadastrar clientes'],
        0,
        'A passagem garante que o próximo turno conheça as pendências.'),
      aula('op-checklist', 'Checklists de posto', 3,
        'Aplicar checklists e tratar não conformidades.',
        [
          'O modelo define os itens do checklist.',
          'Cada posto recebe uma instância do modelo.',
          'A execução registra o que foi verificado.',
          'Não conformidades precisam de tratamento até a correção.',
        ],
        'Qual é a ordem do ciclo do checklist?',
        ['Modelo, instância e execução', 'Execução, modelo e instância', 'Instância, execução e modelo'],
        0,
        'O modelo vem primeiro, depois a instância por posto e, por fim, a execução.'),
    ],
  },
  {
    id: 'gestao-painel',
    title: 'Gestão: painel de pendências e decisões',
    summary: 'Como ler o painel, decidir pedidos e acompanhar indicadores.',
    audiences: ['marcelo'],
    lessons: [
      aula('ges-pendencias', 'Pendências que pedem decisão', 3,
        'Ler o painel e priorizar o que exige decisão.',
        [
          'Abra o painel e escolha o período dos indicadores.',
          'Veja a seção O que exige a sua decisão neste período.',
          'Abra cada item até o registro de origem antes de decidir.',
        ],
        'O que a seção "O que exige a sua decisão" mostra?',
        ['Pendências que pedem decisão no período', 'Somente o histórico de acessos', 'Apenas o conteúdo do site'],
        0,
        'É a fila de decisões do período, com a origem de cada item.'),
      aula('ges-aprovacoes', 'Aprovação unificada e diário de decisões', 3,
        'Decidir pedidos de vários módulos em um só lugar.',
        [
          'Aprove ou recuse os pedidos na aprovação unificada.',
          'Cada decisão é registrada no diário de decisões.',
          'Confira o registro antes de comunicar a decisão.',
        ],
        'Onde as decisões ficam registradas?',
        ['No diário de decisões', 'Em anotações pessoais', 'Apenas no e-mail'],
        0,
        'O diário de decisões é o registro das decisões de gestão.'),
      aula('ges-relatorios', 'Relatórios e indicadores', 3,
        'Ler meta x realizado com a fonte e a data-base.',
        [
          'Compare a meta estimada com o realizado no período.',
          'Verifique a fonte e a data-base de cada indicador.',
          'Gere relatórios: eles são limitados e auditados.',
        ],
        'Os relatórios do painel são:',
        ['Limitados e auditados', 'Públicos', 'Sem registro'],
        0,
        'Relatórios são gerados com limites de acesso e trilha de auditoria.'),
    ],
  },
  {
    id: 'ti-controle',
    title: 'TI e administração',
    summary: 'Papéis, auditoria e acessos do portal.',
    audiences: ['ti'],
    lessons: [
      aula('ti-papeis', 'Papéis e página inicial', 3,
        'Entender como cada papel vê o sistema.',
        [
          'Cada papel tem uma página inicial e vê apenas o que pode ver.',
          'O menu organiza a navegação, mas não concede permissão.',
          'A autorização é decidida no servidor, em cada operação.',
        ],
        'Esconder um botão no menu concede ou nega acesso?',
        ['Não: a autorização é decidida no servidor', 'Sim, concede acesso', 'Sim, nega acesso sempre'],
        0,
        'O menu é apenas navegação. A permissão é verificada no servidor.'),
      aula('ti-auditoria', 'Trilha de auditoria', 3,
        'Ler uma ação sensível com autor, data e motivo.',
        [
          'Ações sensíveis registram autor, data, motivo e histórico.',
          'Consulte a trilha quando algo precisar ser explicado.',
          'Para corrigir um fato, registre a correção; não altere o registro original.',
        ],
        'Quais dados compõem a trilha de uma ação sensível?',
        ['Autor, data, motivo e histórico', 'Somente a data', 'Somente o nome do sistema'],
        0,
        'Essa combinação permite saber quem fez, quando e por quê.'),
      aula('ti-portal', 'Convites e permissões do portal', 3,
        'Conceder e revogar acessos com critério.',
        [
          'Convites são enviados e acompanhados em Acessos do portal.',
          'Permissões podem ser concedidas ou revogadas, sempre com motivo.',
          'Suspensão, desativação e reativação ficam registradas.',
        ],
        'Autocadastro concede acesso automático ao portal?',
        ['Não', 'Sim', 'Somente para clientes'],
        0,
        'Autocadastro gera uma solicitação; o acesso depende de análise.'),
    ],
  },
]);

// ---------- Organizador das trilhas do plano de expansão ----------
// Cada trilha do plano (T01–T24) vira uma entrada em TRACKS. As aulas já
// publicadas entram pelos ids (o progresso é gravado por id e não muda);
// as demais são marcadas com a origem prevista no plano:
//   [S] rotina com tela no sistema  [P] procedimento de campo, a validar
//   [T] conteúdo técnico da SEG     [D] demonstração com dados fictícios
// A T25 (supervisores de posto) fica de fora até o nome do papel ser
// confirmado com o Marcelo (decisão 1 do plano).

const PUBLICADAS = new Map();
BASE.forEach(track => track.lessons.forEach(lesson => PUBLICADAS.set(lesson.id, lesson)));

function pub(id) {
  const lesson = PUBLICADAS.get(id);
  if (!lesson) throw new Error(`Aula publicada não encontrada: ${id}`);
  return lesson;
}

function pend(id, title, tag) {
  return { id, title, minutes: 3, pending: true, tag: tag || 'S' };
}

function trilha(id, title, summary, group, audiences, lessons) {
  return { id, title, summary, group, audiences, lessons };
}

export const TAG_LABELS = Object.freeze({
  S: 'Sistema',
  P: 'Procedimento',
  T: 'Conteúdo técnico',
  D: 'Demonstração',
});

export function isPending(lesson) {
  return Boolean(lesson && lesson.pending);
}

export const TRACKS = Object.freeze([
  trilha('fundamentos', 'Fundamentos do sistema',
    'Acesso, progresso e uso da base de conhecimento. Trilha comum a todos os setores.',
    'Todos', ['todos'], [
      pub('fund-acesso'), pub('fund-progresso'), pub('fund-base'),
    ]),
  trilha('equipe-entrada', 'Equipe: entrada, papéis e navegação',
    'Primeiro acesso da equipe interna, o que cada papel vê e convites administrativos.',
    'Equipe interna', ['comercial', 'rh', 'financeiro', 'supervisor', 'marcelo', 'ti', 'admin'], [
      pub('ti-papeis'),
      pend('t02-hub', 'Hub administrativo: os módulos que o seu papel vê'),
      pend('t02-convite', 'Aceitar um convite administrativo'),
    ]),
  trilha('funcionario-ponto', 'Funcionário: rotina diária',
    'Ponto, ocorrências, ausências, ajustes, escala e passagem de plantão no portal do funcionário.',
    'Funcionário e campo', ['funcionario', 'porteiro', 'controlador_acesso', 'servicos_gerais', 'instalador', 'admin'], [
      pub('func-ponto'), pub('func-ocorrencia'),
      pend('t03-ausencia', 'Registrar ausência ou falta'),
      pend('t03-ajuste-ponto', 'Solicitar ajuste de ponto'),
      pend('t03-troca-escala', 'Solicitar troca de escala'),
      pend('t03-ciencia', 'Dar ciência de comunicados e procedimentos'),
      pend('t03-plantao', 'Receber a passagem de plantão'),
    ]),
  trilha('funcionario-pedidos', 'Funcionário: pedidos, documentos e atendimento',
    'Pedidos ao RH, uniforme, documentos, perfil, cursos, atendimento confidencial e reclamações.',
    'Funcionário e campo', ['funcionario', 'porteiro', 'controlador_acesso', 'servicos_gerais', 'instalador', 'admin'], [
      pub('func-pedidos'),
      pend('t04-uniforme', 'Solicitar uniforme e confirmar o recebimento'),
      pend('t04-documentos', 'Ver os seus documentos privados'),
      pend('t04-perfil', 'Ver e pedir atualização do seu perfil'),
      pend('t04-comprovante', 'Enviar comprovante de curso'),
      pend('t04-atendimento', 'Abrir atendimento confidencial com o RH'),
      pend('t04-reclamacao', 'Registrar uma reclamação'),
    ]),
  trilha('cliente-portal', 'Cliente: acesso e segurança',
    'Convite, primeiro acesso, verificação em duas etapas e sessões do portal do cliente.',
    'Cliente', ['cliente', 'admin'], [
      pub('cli-convite'),
      pend('t05-primeiro-acesso', 'Primeiro acesso e confirmação de e-mail'),
      pend('t05-email', 'Alterar o e-mail, com verificação'),
      pub('cli-seguranca'),
      pend('t05-sessoes', 'Ver e encerrar sessões abertas'),
      pend('t05-acesso-portal', 'Pedir acesso ao portal'),
    ]),
  trilha('cliente-servicos', 'Cliente: serviços, chamados e documentos',
    'Painel do portal, contratos, documentos, chamados, visitas, relatórios e renovação.',
    'Cliente', ['cliente', 'admin'], [
      pend('t06-painel', 'Painel: o que é seu no portal'),
      pend('t06-contratos', 'Contratos e itens de serviço'),
      pend('t06-documentos', 'Documentos: ver e baixar, com registro de acesso'),
      pub('cli-chamados'),
      pend('t06-servico', 'Pedir um serviço e acompanhar'),
      pend('t06-agenda', 'Agenda de visitas e manutenções'),
      pend('t06-relatorios', 'Relatórios de execução, medição e aceite'),
      pend('t06-satisfacao', 'Pesquisa de satisfação e plano de ação'),
      pend('t06-renovacao', 'Renovação e continuidade'),
      pend('t06-contatos', 'Contatos, escopos e delegados'),
      pend('t06-reclamacao', 'Registrar reclamação sobre um colaborador'),
    ]),
  trilha('comercial-funil', 'Comercial: do pedido ao contrato',
    'Entrada de pedidos do site, funil e relacionamento, condições e carteira, proposta e contrato.',
    'Comercial', ['comercial', 'marcelo', 'admin'], [
      pend('t07-pedido-site', 'Pedido de orçamento pelo site'),
      pend('t07-contato-simulador', 'Contato e simulador'),
      pend('t07-conteudos', 'Conteúdos, FAQ e privacidade, com solicitação de titular'),
      pend('t07-leads', 'Lista de leads: o que entra e como acompanhar'),
      pub('com-pedido'), pub('com-funil'),
      pend('t07-interacoes', 'Registrar interações e notas internas'),
      pend('t07-tarefas', 'Criar tarefas e delegar'),
      pend('t07-agenda', 'Agenda de visitas e reuniões, com conflito de agenda'),
      pend('t07-cadencias', 'Cadências manuais'),
      pend('t07-import-csv', 'Importar empresas por CSV, revisando prévia e duplicatas'),
      pend('t07-desconto', 'Pedido de desconto e aprovação'),
      pend('t07-comissao', 'Regras de comissão'),
      pend('t07-carteira', 'Carteira de clientes'),
      pend('t07-satisfacao', 'Satisfação do cliente'),
      pub('com-proposta'),
      pend('t07-link-aceite', 'Entregar a proposta por link de aceite'),
      pend('t07-versoes', 'Comparar versões da proposta'),
      pend('t07-aceite', 'Acompanhar o aceite do cliente'),
      pend('t07-contrato', 'Criar o contrato a partir da proposta aceita'),
    ]),
  trilha('gestao-painel', 'Gestão: painel, pendências e decisões',
    'Pendências do período, aprovação unificada, diário de decisões, indicadores e relatórios.',
    'Gestão', ['marcelo', 'admin'], [
      pub('ges-pendencias'), pub('ges-aprovacoes'),
      pend('t08-diario', 'Diário de decisões, com registro canônico'),
      pend('t08-indicadores', 'Indicadores: meta x realizado'),
      pub('ges-relatorios'),
      pend('t08-analises', 'Análises e relatórios gerenciais'),
    ]),
  trilha('rh-processos', 'RH: admissão e acesso',
    'Cadastro profissional, abertura da admissão, credencial temporária e documentos privados.',
    'RH', ['rh', 'admin'], [
      pub('rh-admissao'), pub('rh-credencial'),
      pend('t09-documentos', 'Documentos privados do funcionário'),
    ]),
  trilha('rh-vida', 'RH: vida funcional',
    'Escala, ponto, solicitações, férias, afastamento, benefícios e treinamento.',
    'RH', ['rh', 'admin'], [
      pend('t10-escala-ciencia', 'Publicar a escala versionada e registrar a ciência'),
      pend('t10-ponto-ajustes', 'Consultar ponto e decidir ajustes pedidos pelo funcionário'),
      pend('t10-solicitacoes', 'Decidir as solicitações: férias, afastamento, benefício e reembolso'),
      pend('t10-ferias', 'Férias: aprovação e registro (demonstração conceitual)', 'D'),
      pend('t10-afastamento', 'Processo de afastamento'),
      pend('t10-beneficios', 'Processo de benefícios'),
      pend('t10-treinamento', 'Processo de treinamento e recrutamento'),
    ]),
  trilha('rh-folha', 'RH: folha e desligamento',
    'Fechamento do período, holerite no espaço privado e desligamento com revogação de acesso.',
    'RH', ['rh', 'admin'], [
      pend('t11-fechamento', 'Fechar o período demonstrativo', 'D'),
      pub('rh-holerite'),
      pub('rh-desligamento'),
    ]),
  trilha('operacao-escala', 'Operação: postos e escala',
    'Postos, habilitação por função, alocação, escala versionada, jornada e cobertura.',
    'Operação', ['supervisor', 'marcelo', 'admin'], [
      pub('op-escala'),
      pend('t12-habilitacao', 'Habilitação e documentação exigida por função'),
      pend('t12-turnos', 'Necessidade por turno e faixa de horário'),
      pend('t12-alocacao', 'Alocação de pessoas e confronto com o planejado'),
      pend('t12-escala-ciencia', 'Escala versionada: publicar e registrar a ciência'),
      pend('t12-jornada', 'Regras de jornada e descanso'),
      pend('t12-cobertura', 'Solicitar cobertura e substituição'),
      pend('t12-lacunas', 'Lacunas de cobertura e plano de cobertura'),
    ]),
  trilha('operacao-postos', 'Operação: rotinas de posto e ocorrências',
    'Livro de ocorrências, passagem de plantão, checklists, rondas, chaves e continuidade.',
    'Operação', ['supervisor', 'marcelo', 'admin'], [
      pub('op-ocorrencias'),
      pend('t13-plantao', 'Passagem de plantão entre turnos'),
      pub('op-checklist'),
      pend('t13-rondas', 'Rondas e leituras de ronda'),
      pend('t13-limpeza', 'Rotinas de limpeza e não conformidades'),
      pend('t13-chaves', 'Movimentação de chaves'),
      pend('t13-apoio', 'Apoio emergencial'),
      pend('t13-continuidade', 'Continuidade de negócios'),
    ]),
  trilha('operacao-recursos', 'Operação: recursos, terceiros e qualidade',
    'Frota, patrimônio e almoxarifado, terceiros e qualidade.',
    'Operação', ['supervisor', 'admin'], [
      pend('t14-frota', 'Frota'),
      pend('t14-patrimonio', 'Patrimônio e almoxarifado'),
      pend('t14-terceiros', 'Terceiros'),
      pend('t14-qualidade', 'Qualidade'),
    ]),
  trilha('contratos-gestao', 'Contratos: implantação e gestão',
    'Cadastro, escopo e vigência, implantação, aditivos, alertas, obrigações e encerramento.',
    'Financeiro e compliance', ['comercial', 'financeiro', 'admin'], [
      pend('t15-cadastro', 'Cadastro manual de contrato'),
      pend('t15-escopo', 'Escopo e vigência dos itens'),
      pend('t15-implantacao', 'Implantação do contrato, por etapas'),
      pend('t15-aditivo', 'Aditivo: registrar a alteração'),
      pend('t15-alertas', 'Alertas de vencimento'),
      pend('t15-diario', 'Diário de gestão do contrato'),
      pend('t15-obrigacoes', 'Obrigações documentais'),
      pend('t15-encerramento', 'Encerramento e fechamento'),
      pend('t15-versoes', 'Versões comerciais: histórico de vistoria, orçamento, proposta e contrato'),
    ]),
  trilha('financeiro-receber', 'Financeiro: receber, pagar, competência e conciliação',
    'Contas a receber e a pagar, recorrência, aging, custos, orçamento, fechamento e conciliação.',
    'Financeiro e compliance', ['financeiro', 'marcelo', 'admin'], [
      pub('fin-receber'),
      pend('t16-recorrencia', 'Recorrência: regra e geração de lançamentos'),
      pend('t16-aging', 'Aging e fluxo de caixa'),
      pend('t16-custos', 'Custos e rateio por centro de custo'),
      pend('t16-orcamento', 'Orçamento e cenários'),
      pub('fin-competencia'),
      pend('t16-exportacoes', 'Exportações do período'),
      pub('fin-conciliacao'),
      pend('t16-cobranca', 'Cobrança e histórico de lembretes', 'D'),
      pend('t16-pagamentos', 'Pagamentos e documento fiscal (gateway em sandbox, não é fiscal real)', 'D'),
    ]),
  trilha('compliance-gestao', 'Compliance, licitações e fornecedores',
    'Obrigações, avaliação temporal, renovação, licitações e fornecedores.',
    'Financeiro e compliance', ['financeiro', 'marcelo', 'admin'], [
      pend('t17-obrigacao', 'Declarar obrigação, referência documental e plano de ação'),
      pend('t17-avaliacao', 'Avaliação temporal de compliance: agenda, resultado e tarefas por vencimento'),
      pend('t17-renovacao', 'Renovar uma obrigação'),
      pend('t17-licitacoes', 'Licitações'),
      pend('t17-fornecedores', 'Fornecedores'),
    ]),
  trilha('admin-acessos', 'Administração: acessos e portal',
    'Convites, permissões, solicitações de acesso, alertas e cadastro central de clientes.',
    'Administração e TI', ['admin', 'ti'], [
      pub('ti-portal'),
      pend('t18-permissoes', 'Permissões: conceder, revogar, suspender, desativar e reativar'),
      pend('t18-solicitacoes', 'Solicitações de acesso e autocadastro (sem acesso automático)'),
      pend('t18-alertas', 'Alertas de acesso e trocas de e-mail sinalizadas'),
      pend('t18-cadastro', 'Cadastro central de clientes e vínculos de acesso verificados'),
      pend('t18-vinculos', 'Contratos, documentos, chamados e visitas do cliente no cadastro central'),
    ]),
  trilha('admin-sistema', 'Administração: sistema, LGPD e auditoria',
    'Trilha de auditoria, papéis e permissões, site, LGPD, aparência e notificações.',
    'Administração e TI', ['admin'], [
      pub('ti-auditoria'),
      pend('t19-rbac', 'Permissões por papel (RBAC) e o motivo de cada concessão'),
      pend('t19-site', 'Publicação do site'),
      pend('t19-lgpd', 'LGPD: solicitações de titular, retenção e descarte'),
      pend('t19-aparencia', 'Aparência, tema e visual'),
      pend('t19-notificacoes', 'Fila de notificações e preferências'),
    ]),
  trilha('ti-seguranca', 'TI: segurança, backup e observabilidade',
    'Backup e restauração, observabilidade, verificação técnica e limites declarados do sistema.',
    'Administração e TI', ['ti', 'admin'], [
      pend('t20-backup', 'Backup e restauração'),
      pend('t20-observabilidade', 'Observabilidade e healthcheck'),
      pend('t20-verificacao', 'Verificação manual pelo time técnico'),
      pend('t20-limites', 'Limites declarados do sistema: RAG privado, e-mail e sandbox financeiro'),
    ]),
  trilha('portaria-rotina', 'Porteiros: portaria e rotina de posto',
    'Recepção, controle de visitantes, livro de ocorrências, chaves, rondas e emergência.',
    'Campo', ['porteiro', 'admin'], [
      pend('t21-recepcao', 'Recepção de quem chega: identificação e orientação', 'P'),
      pend('t21-visitantes', 'Controle de visitantes e veículos: registro de entrada e saída', 'P'),
      pend('t21-ocorrencias', 'Livro de ocorrências: como registrar o que aconteceu'),
      pend('t21-chaves', 'Chaves: retirada, devolução e conferência'),
      pend('t21-checklist', 'Checklist de posto de portaria'),
      pend('t21-rondas', 'Rondas e leituras de ronda'),
      pend('t21-plantao', 'Passagem de plantão'),
      pend('t21-emergencia', 'Acionar emergência e apoio'),
    ]),
  trilha('controle-acesso', 'Controladores de acesso',
    'Credenciais, acessos fora do padrão, áreas restritas, alarme, plantão e emergência.',
    'Campo', ['controlador_acesso', 'admin'], [
      pend('t22-credenciais', 'Conferir credenciais e autorização de acesso', 'P'),
      pend('t22-fora-padrao', 'Acesso fora do padrão: registrar como ocorrência'),
      pend('t22-chaves', 'Controle de chaves e de áreas restritas'),
      pend('t22-rondas', 'Rondas e checklist do controle de acesso'),
      pend('t22-alarme', 'Alarme disparado: o que fazer', 'P'),
      pend('t22-plantao', 'Passagem de plantão com pendências de acesso'),
      pend('t22-emergencia', 'Emergência e evacuação: acionar o apoio'),
    ]),
  trilha('servicos-gerais', 'Auxiliares de serviços gerais: limpeza e conservação',
    'Rotina de limpeza, não conformidades, materiais, EPI e comunicação com o posto.',
    'Campo', ['servicos_gerais', 'admin'], [
      pend('t23-ponto', 'Ponto, escala e troca de turno'),
      pend('t23-limpeza', 'Rotina de limpeza: execução e checklist'),
      pend('t23-nao-conformidade', 'Não conformidade de limpeza: registrar e tratar'),
      pend('t23-materiais', 'Materiais, almoxarifado e patrimônio'),
      pend('t23-epi', 'Segurança no trabalho e uso de EPI', 'P'),
      pend('t23-comunicacao', 'Ocorrências e comunicação com o posto'),
    ]),
  trilha('instalacao-seguranca', 'Instaladores de segurança eletrônica',
    'Visitas e ordens de serviço, frota, equipamentos, execução, segurança e sistemas instalados.',
    'Campo', ['instalador', 'admin'], [
      pend('t24-agenda', 'Agenda de visitas e ordem de serviço do cliente'),
      pend('t24-frota', 'Frota e veículo de instalação'),
      pend('t24-patrimonio', 'Patrimônio e equipamentos em uso: inventário'),
      pend('t24-checklist', 'Checklist de instalação por tipo de sistema', 'P'),
      pend('t24-execucao', 'Registro de execução: fotos, medição e relatório de aceite'),
      pend('t24-ocorrencia', 'Ocorrência durante a instalação'),
      pend('t24-seguranca', 'Segurança na instalação: altura, eletricidade e EPI', 'P'),
      pend('t24-equipamentos', 'Equipamentos: câmeras, sensores, alarmes, central e cerca elétrica', 'T'),
    ]),
]);

export function lessonCount(tracks = TRACKS) {
  return tracks.reduce((total, track) => total + track.lessons.length, 0);
}

export function publishedCount(tracks = TRACKS) {
  return tracks.reduce((total, track) => total + track.lessons.filter(lesson => !isPending(lesson)).length, 0);
}
